/**
 * Tours for the school's academic year, classes, class timetables, the
 * onboarding control room and the support desk.
 *
 * Each one stops before the button that writes: Create on a session or a set of
 * arms, Add lesson and Publish on a timetable, Mark as done on an onboarding
 * step, and Create ticket in the help panel. A `target-click` step only ever
 * opens a form the next step points into.
 *
 * Buttons that depend on the reader's role, or on the year being read-only, are
 * routed around with a `branch` step on the button itself, so a reader who
 * cannot create still reads the list and finishes on a step that says why the
 * button is missing.
 */
import { P } from "@/permissions";
import { routesPath } from "@/routes/routesPath";

import type { Walkthrough } from "../types";

const R = routesPath.PROTECTED;

export const ACADEMICS_WALKTHROUGHS = [
  {
    id: "walkthrough.school.academics.sessions-and-terms",
    guideId: "school.academics.sessions-and-terms",
    route: R.ACADEMIC_STRUCTURE.SESSIONS,
    permissions: [P.BROWSE_SESSIONS],
    prerequisites: [
      "Know the first and last day of the school year, and of every term.",
      "If your school runs several branches, know which branches follow this year.",
    ],
    version: 1,
    steps: [
      {
        id: "welcome",
        title: "Set up a school year",
        body: "This tour shows how to read your sessions and what the Create session form asks for. It may open the form, but it never saves a session or changes which year is active.",
        advance: "next",
      },
      {
        id: "summary",
        target: "sessions.summary",
        title: "The year the school is running",
        body: "Active session names the year everything else follows, or says Not set when no year is active. {Terms} running and Teaching weeks are counted from that year's {terms}.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "toolbar",
        target: "sessions.toolbar",
        title: "Find a session",
        body: "Search by name, filter by Active, Draft or Archived, and switch between cards and a table. Where your role allows it, Export downloads the list.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "list-branch",
        kind: "branch",
        target: "sessions.list",
        whenPresent: "list",
        whenMissing: "new-branch",
      },
      {
        id: "list",
        target: "sessions.list",
        title: "Read a session at a glance",
        body: "Each card shows the dates, the status and a marker per {term}, ticked once the {term} has ended. The active year has a green edge. A card opens the session's own page, and its three dots hold Edit session, Set as active, Copy structure in and Archive, as far as your role allows.",
        placement: "top",
        advance: "manual",
      },
      {
        id: "new-branch",
        kind: "branch",
        target: "sessions.new",
        whenPresent: "new-session",
        whenMissing: "no-create",
      },
      {
        id: "new-session",
        target: "sessions.new",
        title: "Open the Create session form",
        body: "Select New session to carry on. Opening the form saves nothing, and Cancel closes it without keeping what you typed.",
        placement: "bottom",
        advance: "target-click",
      },
      {
        id: "name",
        target: "session-drawer.name",
        title: "Name the year",
        body: "Use a name such as 2026/2027. Each session needs its own name, and a name already in use is refused under this box.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "dates",
        target: "session-drawer.dates",
        title: "Set when the year runs",
        body: "Choose the first and last day of the school year. The end must come after the start, and every {term} has to fall inside these dates.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "applies-branch",
        kind: "branch",
        target: "session-drawer.applies-to",
        whenPresent: "applies-to",
        whenMissing: "terms",
      },
      {
        id: "applies-to",
        target: "session-drawer.applies-to",
        title: "Choose where the year applies",
        body: "The whole school covers every branch, including a branch opened while the year is running. Selected branches lets you pick the ones that follow it. The dates are the same everywhere it applies, so a branch on a different calendar needs a session of its own.",
        placement: "left",
        advance: "manual",
      },
      {
        id: "terms",
        target: "session-drawer.terms",
        title: "Fill in each {term}",
        body: "The rows start with your school's own {term} names, in order, from Academic structure in Settings. Rename them, give each a start and end date, add a row with Add {term}, or remove one with its cross. Each {term} starts after the one before it ends, and the calendar only offers days that fit.",
        placement: "left",
        advance: "manual",
      },
      {
        id: "actions",
        target: "session-drawer.actions",
        title: "Create when the form is complete",
        body: "Create stays grey until every required field is filled in and the dates fit together. The tour stops here: select Create yourself when the year is right, or Cancel to close the form without saving.",
        placement: "top",
        advance: "manual",
      },
      {
        id: "create-rejoin",
        kind: "branch",
        target: "sessions.new",
        whenPresent: "complete",
        whenMissing: "no-create",
      },
      {
        id: "no-create",
        title: "You can read sessions but not create them",
        body: "New session appears only for roles that can create sessions. Ask a school administrator to add the year, then come back to check its {terms} and dates.",
        advance: "next",
      },
      {
        id: "complete",
        title: "Make the year active when it is ready",
        body: "When the school is ready to run a saved year, choose Set as active from its card's menu. Only one session is active at a time, so the year that was active stops being active.",
        advance: "next",
      },
    ],
  },
  {
    id: "walkthrough.school.academics.classes-and-arms",
    guideId: "school.academics.classes-and-arms",
    route: R.ACADEMIC_STRUCTURE.CLASSES,
    permissions: [P.BROWSE_CLASSES],
    prerequisites: [
      "Make sure the year you want has its levels on Programmes & Levels.",
      "Know the arms each level runs, such as A, B and C.",
    ],
    version: 1,
    steps: [
      {
        id: "welcome",
        title: "Build the classes pupils sit in",
        body: "This tour shows how to find a class, read its card, and what Generate arms asks for. It may open the Generate arms form, but it never creates, edits or archives a class.",
        advance: "next",
      },
      {
        id: "lens-branch",
        kind: "branch",
        target: "sidebar.lenses",
        whenPresent: "lens",
        whenMissing: "toolbar",
      },
      {
        id: "lens",
        target: "sidebar.lenses",
        title: "Classes belong to one year",
        body: "The year and branch chosen here decide which classes are listed. In an archived year the list is read-only, so Generate arms, Add class and Edit are not offered.",
        placement: "right",
        advance: "manual",
      },
      {
        id: "toolbar",
        target: "classes.toolbar",
        title: "Find a class",
        body: "Search by name, narrow by level, and choose Active, Archived or All statuses. Switch between cards and a table, and use Export for a spreadsheet where your role allows it.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "summary",
        target: "classes.summary",
        title: "The shape of the year",
        body: "How many classes, levels and subjects the year and branch you are looking at hold.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "list-branch",
        kind: "branch",
        target: "classes.list",
        whenPresent: "list",
        whenMissing: "create-branch",
      },
      {
        id: "list",
        target: "classes.list",
        title: "Read a class card",
        body: "Each card shows the level and arm, the class teacher, the number of subjects and the capacity. No class teacher assigned means the class still needs one. A card opens the class's page, and Edit and Archive sit on the card as far as your role allows.",
        placement: "top",
        advance: "manual",
      },
      {
        id: "create-branch",
        kind: "branch",
        target: "classes.generate-arms",
        whenPresent: "add-class",
        whenMissing: "no-create",
      },
      {
        id: "add-class",
        target: "classes.add",
        title: "Add one class at a time",
        body: "Add class opens a form where you pick a level and an arm, and the name and code are built from them. Capacity is optional: leave it blank for no limit.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "generate-arms",
        target: "classes.generate-arms",
        title: "Or make a level's arms at once",
        body: "Generate arms creates one class per arm, such as JSS1 A, JSS1 B and JSS1 C. Select it to carry on. Opening the form creates nothing.",
        placement: "bottom",
        advance: "target-click",
      },
      {
        id: "arms-level",
        target: "generate-arms.level",
        title: "Pick the level",
        body: "The new classes are named after the level. Only levels in the year and branch you are looking at are listed. If there are none, add them on Programmes & Levels first.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "arms-list",
        target: "generate-arms.arms",
        title: "List the arms",
        body: "The box opens with your school's default arms, A, B, C until your school sets its own in Settings. Edit the list, separating the arms with commas. Names like Science or Commercial work too.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "runs-at-branch",
        kind: "branch",
        target: "generate-arms.runs-at",
        whenPresent: "runs-at",
        whenMissing: "arms-preview",
      },
      {
        id: "runs-at",
        target: "generate-arms.runs-at",
        title: "Choose the branch that runs them",
        body: "A class is normally run by one branch, even when its level is shared. A level that belongs to one branch decides this for you, and so does a role that works in one branch only.",
        placement: "left",
        advance: "manual",
      },
      {
        id: "arms-preview",
        target: "generate-arms.preview",
        title: "Check what will be created",
        body: "Each row is marked New or Already there. Classes that already exist are skipped rather than refused, and the Create button counts only the new ones. The tour stops here: select Create yourself, or Cancel to leave everything as it is.",
        placement: "top",
        advance: "manual",
      },
      {
        id: "create-rejoin",
        kind: "branch",
        target: "classes.generate-arms",
        whenPresent: "complete",
        whenMissing: "no-create",
      },
      {
        id: "no-create",
        title: "Classes cannot be added here right now",
        body: "Generate arms and Add class appear only for roles that can create classes, and never in an archived year. Ask a school administrator, or switch to the year the school is running.",
        advance: "next",
      },
      {
        id: "complete",
        title: "Give every class a teacher and a capacity",
        body: "Once the classes exist, check each card for a class teacher and a capacity. Classes are what pupils, subjects and timetables are placed into.",
        advance: "next",
      },
    ],
  },
  {
    id: "walkthrough.school.timetables.build-class-timetable",
    guideId: "school.timetables.build-class-timetable",
    route: R.TIMETABLES.CLASSES,
    permissions: [P.BROWSE_TIMETABLES],
    prerequisites: [
      "Add the classes on Classes & Arms.",
      "Set up this year's periods on the Bell Schedule.",
      "Offer the subjects at the class's level, and add rooms if lessons should have one.",
    ],
    version: 1,
    steps: [
      {
        id: "welcome",
        title: "Build one class's week",
        body: "This tour shows how to read a class timetable and fill a slot. It may open a lesson form, but it never saves a lesson, copies a week, clears a grid or publishes.",
        advance: "next",
      },
      {
        id: "ready-branch",
        kind: "branch",
        target: "class-timetable.grid",
        whenPresent: "class-bar",
        whenMissing: "not-ready",
      },
      {
        id: "class-bar",
        target: "class-timetable.class-bar",
        title: "Pick the class",
        body: "The screen opens on the first class you can see. Use Timetable for to search for another. Beside it, the badge shows the timetable's status and how many teaching periods are filled.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "grid",
        target: "class-timetable.grid",
        title: "Read the week",
        body: "Periods run down the side and the weekdays across. Breaks show their name, and a dash marks a period that does not run that day. A lesson in red is part of a clash.",
        placement: "top",
        advance: "manual",
      },
      {
        id: "clash-branch",
        kind: "branch",
        target: "class-timetable.clashes",
        whenPresent: "clashes",
        whenMissing: "actions",
      },
      {
        id: "clashes",
        target: "class-timetable.clashes",
        title: "Clashes are listed above the grid",
        body: "Each line names a teacher or room booked into two places at once. The grid saves with clashes in it, but they block publishing until they are resolved.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "actions",
        target: "class-timetable.actions",
        title: "Print, copy, clear and publish",
        body: "Print makes a noticeboard copy and Export a spreadsheet. Duplicate from copies another class's week, Clear empties this one, and Publish marks the week finished. Each appears only where your role allows it, and the tour presses none of them.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "lesson-branch",
        kind: "branch",
        target: "timetable-grid.cell",
        whenPresent: "open-lesson",
        whenMissing: "complete",
      },
      {
        id: "open-lesson",
        target: "timetable-grid.cell",
        title: "Open a slot",
        body: "Select this slot to carry on. An empty slot opens Add lesson and a filled one opens Edit lesson. Opening the form saves nothing.",
        placement: "right",
        advance: "target-click",
      },
      {
        id: "lesson-fields",
        target: "lesson-drawer.fields",
        title: "Subject, teacher and room",
        body: "Subject is the only field you must fill. The teacher list covers every teacher at the school, including those who work across branches, and the room list only this class's branch. When the teacher or room is already booked, a warning names the clash before you save.",
        placement: "left",
        advance: "manual",
      },
      {
        id: "lesson-actions",
        target: "lesson-drawer.actions",
        title: "Saving is your choice",
        body: "Add lesson or Save changes writes the slot. When a clash is shown, the button waits until you tick that you know about it. Cancel closes the form without saving. The tour stops here.",
        placement: "top",
        advance: "manual",
      },
      {
        id: "grid-rejoin",
        kind: "branch",
        target: "class-timetable.grid",
        whenPresent: "complete",
        whenMissing: "not-ready",
      },
      {
        id: "not-ready",
        title: "There is no grid to build yet",
        body: "A timetable needs a class and a bell schedule. If the screen says No classes yet, add them on Classes & Arms. If it says No bell schedule yet, set up this year's periods on the Bell Schedule first.",
        advance: "next",
      },
      {
        id: "complete",
        title: "Publish when the week is right",
        body: "Fill the teaching periods, resolve every clash, then select Publish. A published week can still be edited, and editing it does not unpublish it: select Republish when it is right again.",
        advance: "next",
      },
    ],
  },
  {
    id: "walkthrough.school.setup.onboarding-checklist",
    guideId: "school.setup.onboarding-checklist",
    route: R.ONBOARDING.INDEX,
    permissions: [P.VIEW_ONBOARDING],
    prerequisites: [
      "Your school is still being set up and has not gone live.",
    ],
    version: 1,
    steps: [
      {
        id: "welcome",
        title: "Find your way to go-live",
        body: "This tour explains the Onboarding Control Room: where your school stands, the steps it needs, and how going live works. It never marks, skips or reopens a step for you.",
        advance: "next",
      },
      {
        id: "status-branch",
        kind: "branch",
        target: "onboarding.status",
        whenPresent: "strip-branch",
        whenMissing: "no-checklist",
      },
      {
        id: "strip-branch",
        kind: "branch",
        target: "onboarding.status-strip",
        whenPresent: "strip",
        whenMissing: "status",
      },
      {
        id: "strip",
        target: "onboarding.status-strip",
        title: "Only onboarding is open for now",
        body: "Until your school goes live, this strip says so on every onboarding screen and shows when your onboarding window closes. Near the end of the window, a warning counts the days left.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "status",
        target: "onboarding.status",
        title: "Read your go-live status",
        body: "The headline says where you stand: Not ready, Ready to go live, Waiting on XVS or Live, and names any required step still open. The counts show what is completed, remaining, skipped and blocking. Re-check, where your role offers it, asks XVS to look at your steps again.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "tasks",
        target: "onboarding.tasks",
        title: "Every step your school needs",
        body: "Each card shows a step, its status, and whether it is Required or Optional. Your school's list comes from XVS, so it may have more or fewer steps than another school's.",
        placement: "top",
        advance: "manual",
      },
      {
        id: "task-branch",
        kind: "branch",
        target: "onboarding.task-actions",
        whenPresent: "task-actions",
        whenMissing: "go-live",
      },
      {
        id: "task-actions",
        target: "onboarding.task-actions",
        title: "Work a step",
        body: "Where a step has its own screen, a button such as Open profile or Open import takes you there. Mark as done asks XVS to check the step, and any reason it is not done yet appears in red under the card. Optional steps offer Skip for now, and a finished step's menu offers Reopen.",
        placement: "left",
        advance: "manual",
      },
      {
        id: "go-live",
        target: "onboarding.go-live",
        title: "Going live",
        body: "This panel mirrors the go-live screen. For a school administrator, Request go-live stays greyed out until every required step is done, and a request waits while XVS reviews it by hand.",
        placement: "left",
        advance: "manual",
      },
      {
        id: "next-branch",
        kind: "branch",
        target: "onboarding.next-action",
        whenPresent: "next-action",
        whenMissing: "required",
      },
      {
        id: "next-action",
        target: "onboarding.next-action",
        title: "Your next best action",
        body: "The first required step still open, or failing that the next optional one. Continue opens the screen behind it, or scrolls to its card when it has none.",
        placement: "left",
        advance: "manual",
      },
      {
        id: "required",
        target: "onboarding.required",
        title: "Required for go-live",
        body: "Each required step is ticked here as it is done. Optional steps you skip never block go-live.",
        placement: "left",
        advance: "manual",
      },
      {
        id: "help",
        target: "onboarding.help",
        title: "Ask for help from here",
        body: "Escalate an issue opens a support ticket over this screen, so you can describe the step you are stuck on without leaving it.",
        placement: "left",
        advance: "manual",
      },
      {
        id: "status-rejoin",
        kind: "branch",
        target: "onboarding.status",
        whenPresent: "complete",
        whenMissing: "no-checklist",
      },
      {
        id: "no-checklist",
        title: "The checklist is not showing",
        body: "If the screen says it could not find your checklist, select Contact XVS. If it says you cannot open it, ask whoever set up your account to check your role. Otherwise, select Try again.",
        advance: "next",
      },
      {
        id: "complete",
        title: "Take the steps in any order",
        body: "When every required step shows Done and the headline reads Ready to go live, request go-live from the Going live panel.",
        advance: "next",
      },
    ],
  },
  {
    id: "walkthrough.school.getting-started.raise-support-ticket",
    guideId: "school.getting-started.raise-support-ticket",
    route: R.SUPPORT.INDEX,
    permissions: [],
    prerequisites: [
      "Know the screen the problem happened on.",
      "Have a screenshot ready if it helps to show the problem.",
    ],
    version: 1,
    steps: [
      {
        id: "welcome",
        title: "Raise a ticket and follow it",
        body: "This tour shows your support desk and the help panel's ticket form. It may open the panel, but it never creates a ticket or sends anything.",
        advance: "next",
      },
      {
        id: "desk",
        target: "support.heading",
        title: "Your school's support desk",
        body: "Tickets raised at your school are listed on this screen. Your school's own support team reads them first and sends on to XVS only what it cannot solve. Raise an issue opens the same form as the headset in the header.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "filters",
        target: "support.filters",
        title: "Find a ticket",
        body: "Open lists tickets still being worked on, and Resolved, Closed and All widen it. Search tickets narrows the list. Below, a ticket's Status reads With XVS once it has been sent on, and selecting a ticket opens its conversation.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "page-help",
        target: "header.page-help",
        title: "Raise a ticket from any screen",
        body: "The headset opens the help panel over whatever screen you are on, so the problem stays in view while you describe it. Select it to carry on. Opening the panel sends nothing.",
        placement: "bottom",
        advance: "target-click",
      },
      {
        id: "title",
        target: "support-ticket.title",
        title: "Give it a short title",
        body: "Say in a few words what is wrong, such as Receipt shows the wrong amount. The screen you raise it from goes with the ticket, so you do not need to name it.",
        placement: "left",
        advance: "manual",
      },
      {
        id: "description",
        target: "support-ticket.description",
        title: "Describe what happened",
        body: "Say what you did, what you expected, and what you have tried. A sentence is enough, but more detail saves a round of questions. Never include a password.",
        placement: "left",
        advance: "manual",
      },
      {
        id: "category",
        target: "support-ticket.category",
        title: "Category and priority",
        body: "Pick the category that fits, such as Bug report or Account, and a priority. Keep Urgent for something that stops work.",
        placement: "left",
        advance: "manual",
      },
      {
        id: "attachments",
        target: "support-ticket.attachments",
        title: "Add a screenshot",
        body: "Optional. Up to five files of 10 MB each: images, PDFs and spreadsheets.",
        placement: "left",
        advance: "manual",
      },
      {
        id: "guides",
        target: "support-sheet.guides",
        title: "Check the guides for this page",
        body: "This switches the panel to the guides written for the screen underneath, and back again, without losing what you typed.",
        placement: "left",
        advance: "manual",
      },
      {
        id: "create",
        target: "support-ticket.actions",
        title: "Create the ticket when you are ready",
        body: "Create ticket stays grey until the title and description are filled in. The tour stops here: select Create ticket yourself, or Close to leave without sending. A filed ticket gets a reference number to keep.",
        placement: "left",
        advance: "manual",
      },
      {
        id: "complete",
        title: "Follow the replies on the desk",
        body: "You are notified in the app and by email when somebody replies. Open the ticket from the Support desk to read and answer it. A reply sent by email does not reach the ticket.",
        advance: "next",
      },
    ],
  },
] as const satisfies readonly Walkthrough[];
