import { P } from "@/permissions";

import type { GuideRecord } from "../types";
import { OWNER, R } from "./shared";

export const ACADEMICS_GUIDES = [
  {
    id: "school.academics.structure-overview",
    slug: "read-the-academic-structure-overview",
    title: "Read the academic structure overview",
    summary: "See the school year at a glance, count what the structure holds, and find the setup steps that still need attention.",
    category: "academics",
    tags: ["academic structure", "overview", "readiness", "tree", "school year", "setup"],
    aliases: ["structure overview", "academic setup", "what is left to set up", "structure tree", "structure readiness", "academics home"],
    audiences: ["school-administrator", "branch-administrator"],
    routes: [R.ACADEMIC_STRUCTURE.INDEX],
    actionIds: ["view-academic-structure"],
    access: { mode: "any", permissions: [P.BROWSE_STRUCTURE] },
    primaryRoute: R.ACADEMIC_STRUCTURE.INDEX,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "read-the-year", title: "Read the year at the top" },
      { id: "browse-the-structure", title: "Browse the structure" },
      { id: "readiness", title: "Check structure readiness" },
      { id: "setup-order", title: "Build it in order" },
      { id: "branch-and-year", title: "Branch and year" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    estimatedMinutes: 4,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "low",
    status: "published",
    relatedGuideIds: [
      "school.academics.sessions-and-terms",
      "school.academics.departments",
      "school.academics.programmes-and-levels",
      "school.academics.classes-and-arms",
      "school.academics.subjects",
    ],
    article: () => import("../content/academics/structure-overview"),
  },
  {
    id: "school.academics.sessions-and-terms",
    slug: "set-up-sessions-and-terms",
    title: "Set up sessions and terms",
    summary: "Create a school year with its terms, choose the branches it covers, make it the active year, copy last year's structure in, and archive it when it ends.",
    category: "academics",
    tags: ["session", "term", "semester", "school year", "activate", "archive", "copy structure"],
    aliases: ["term dates", "new school year", "start a session", "add a term", "set active session", "close the year", "archive session", "roll forward", "copy last year", "semesters"],
    audiences: ["school-administrator"],
    routes: [R.ACADEMIC_STRUCTURE.SESSIONS, R.ACADEMIC_STRUCTURE.SESSION_DETAILS],
    actionIds: ["view-academic-session", "add-session"],
    access: { mode: "any", permissions: [P.BROWSE_SESSIONS] },
    primaryRoute: R.ACADEMIC_STRUCTURE.SESSIONS,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "create-a-session", title: "Create a session and its terms" },
      { id: "choose-branches", title: "Choose where the session applies" },
      { id: "read-a-session", title: "Read a session" },
      { id: "set-active", title: "Make a session the active one" },
      { id: "copy-structure", title: "Start a year from another year" },
      { id: "archive-a-session", title: "Archive a session" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    estimatedMinutes: 7,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "medium",
    featured: true,
    status: "published",
    relatedGuideIds: [
      "school.academics.structure-overview",
      "school.academics.programmes-and-levels",
      "school.calendar.plan-the-calendar",
    ],
    article: () => import("../content/academics/sessions-and-terms"),
  },
  {
    id: "school.academics.departments",
    slug: "organise-departments",
    title: "Organise departments",
    summary: "Add the departments that programmes and subjects belong to, decide which branch each one covers, and archive the ones you no longer use.",
    category: "academics",
    tags: ["department", "faculty", "structure", "archive", "restore"],
    aliases: ["add a department", "faculties", "sciences department", "rename department", "department code", "archive department"],
    audiences: ["school-administrator", "branch-administrator"],
    routes: [R.ACADEMIC_STRUCTURE.DEPARTMENTS],
    actionIds: ["view-departments", "add-department"],
    access: { mode: "any", permissions: [P.BROWSE_STRUCTURE] },
    primaryRoute: R.ACADEMIC_STRUCTURE.DEPARTMENTS,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "add-a-department", title: "Add a department" },
      { id: "choose-where-it-applies", title: "Choose where it applies" },
      { id: "open-a-department", title: "Open and edit a department" },
      { id: "archive-and-restore", title: "Archive and restore" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    estimatedMinutes: 4,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "low",
    status: "published",
    relatedGuideIds: [
      "school.academics.programmes-and-levels",
      "school.academics.subjects",
      "school.academics.structure-overview",
    ],
    article: () => import("../content/academics/departments"),
  },
  {
    id: "school.academics.programmes-and-levels",
    slug: "set-up-programmes-and-levels",
    title: "Set up programmes and levels",
    summary: "Add programmes such as Primary or Junior Secondary, put their levels in order, and say where each level's pupils go at the end of the year.",
    category: "academics",
    tags: ["programme", "program", "level", "year group", "promotion", "bulk levels"],
    aliases: ["add a level", "add levels in bulk", "junior secondary", "primary", "nursery", "promotes to", "promotion path", "last level", "graduating class", "year groups"],
    audiences: ["school-administrator", "branch-administrator"],
    routes: [R.ACADEMIC_STRUCTURE.PROGRAMS],
    actionIds: ["view-programmes", "add-programme"],
    access: { mode: "any", permissions: [P.BROWSE_STRUCTURE] },
    primaryRoute: R.ACADEMIC_STRUCTURE.PROGRAMS,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "add-a-programme", title: "Add a programme" },
      { id: "add-levels", title: "Add levels" },
      { id: "set-promotion", title: "Say where each level promotes to" },
      { id: "read-the-list", title: "Read the programme list" },
      { id: "archive-and-restore", title: "Archive and restore" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    estimatedMinutes: 7,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "medium",
    status: "published",
    relatedGuideIds: [
      "school.academics.departments",
      "school.academics.classes-and-arms",
      "school.academics.subjects",
      "school.academics.sessions-and-terms",
    ],
    article: () => import("../content/academics/programmes-and-levels"),
  },
  {
    id: "school.academics.classes-and-arms",
    slug: "create-classes-and-arms",
    title: "Create classes and arms",
    summary: "Generate a set of arms for a level or add one class at a time, then read a class's page for its teacher, capacity and pupils.",
    category: "academics",
    tags: ["class", "arm", "stream", "capacity", "class teacher", "roster"],
    aliases: ["generate arms", "add a class", "jss1 a", "class list", "class register", "class capacity", "assign class teacher", "who is in this class", "archive class"],
    audiences: ["school-administrator", "branch-administrator", "teacher"],
    routes: [R.ACADEMIC_STRUCTURE.CLASSES, R.ACADEMIC_STRUCTURE.CLASS_DETAILS],
    actionIds: ["view-classes", "add-class"],
    access: { mode: "any", permissions: [P.BROWSE_CLASSES] },
    primaryRoute: R.ACADEMIC_STRUCTURE.CLASSES,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "generate-arms", title: "Generate arms for a level" },
      { id: "add-one-class", title: "Add or edit one class" },
      { id: "find-a-class", title: "Find a class" },
      { id: "read-class-details", title: "Read a class's page" },
      { id: "archive-and-restore", title: "Archive and restore" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    estimatedMinutes: 6,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "medium",
    status: "published",
    relatedGuideIds: [
      "school.academics.programmes-and-levels",
      "school.academics.subjects",
      "school.timetables.build-class-timetable",
    ],
    article: () => import("../content/academics/classes-and-arms"),
  },
  {
    id: "school.academics.subjects",
    slug: "manage-subjects",
    title: "Manage subjects",
    summary: "Add the subjects the school teaches, mark them core or elective, and choose the levels each one is offered at this year.",
    category: "academics",
    tags: ["subject", "curriculum", "core", "elective", "offered at", "level"],
    aliases: ["add a subject", "mathematics", "elective subject", "core subject", "subject levels", "where is this subject taught", "curriculum", "archive subject"],
    audiences: ["school-administrator", "branch-administrator"],
    routes: [R.ACADEMIC_STRUCTURE.SUBJECTS],
    actionIds: ["view-subjects", "add-subject"],
    access: { mode: "any", permissions: [P.BROWSE_SUBJECTS] },
    primaryRoute: R.ACADEMIC_STRUCTURE.SUBJECTS,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "add-a-subject", title: "Add a subject" },
      { id: "choose-levels", title: "Choose the levels it is offered at" },
      { id: "read-subject-cards", title: "Read the subject list" },
      { id: "archive-and-restore", title: "Archive and restore" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    estimatedMinutes: 5,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "low",
    status: "published",
    relatedGuideIds: [
      "school.academics.programmes-and-levels",
      "school.academics.departments",
      "school.timetables.build-class-timetable",
    ],
    article: () => import("../content/academics/subjects"),
  },
] as const satisfies readonly GuideRecord[];
