import { P } from "@/permissions";

import type { GuideRecord } from "../types";
import { OWNER, R } from "./shared";

export const APPROVALS_AND_WORKFLOW_GUIDES = [
  {
    id: "school.workflow.decide-approval",
    slug: "review-and-decide-an-approval",
    title: "Review and decide an approval",
    summary: "Find a request waiting for you, read what it asks for, then approve, reject or return it with a reason.",
    category: "approvals-and-workflow",
    tags: ["approval", "approve", "reject", "return", "pending approvals", "requisition", "purchase order", "workflow"],
    aliases: ["sign off", "approve request", "approve purchase", "reject request", "send back request", "approval inbox", "waiting on me", "my approvals"],
    audiences: ["approver", "all-users"],
    routes: [R.WORKFLOW.APPROVALS, R.WORKFLOW.APPROVAL_DETAIL],
    actionIds: ["view-approvals"],
    access: { mode: "authenticated", permissions: [] },
    walkthroughId: "walkthrough.school.workflow.decide-approval",
    primaryRoute: R.WORKFLOW.APPROVALS,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "find-an-approval", title: "Find an approval" },
      { id: "review-the-request", title: "Review the request" },
      { id: "choose-a-decision", title: "Choose a decision" },
      { id: "understand-the-result", title: "Understand the result" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["school.workflow.track-and-delegate", "school.procurement.raise-requisition"],
    estimatedMinutes: 5,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "high",
    featured: true,
    status: "published",
    article: () => import("../content/approvals-and-workflow/decide-an-approval"),
  },
  {
    id: "school.workflow.track-and-delegate",
    slug: "track-your-submissions-and-delegate-approvals",
    title: "Track your submissions and delegate approvals",
    summary: "Follow a request you sent, resubmit or withdraw it, and hand your approvals to a colleague while you are away.",
    category: "approvals-and-workflow",
    tags: ["my submissions", "delegation", "resubmit", "withdraw", "revoke", "returned", "cover"],
    aliases: ["what i sent", "track my request", "returned request", "out of office", "cover for me", "delegate approval", "on leave", "term break"],
    audiences: ["approver", "all-users"],
    routes: [R.WORKFLOW.MY_SUBMISSIONS, R.WORKFLOW.SUBMISSION_DETAIL, R.WORKFLOW.DELEGATIONS],
    actionIds: ["view-my-submissions", "view-delegations"],
    access: { mode: "authenticated", permissions: [] },
    walkthroughId: "walkthrough.school.workflow.track-and-delegate",
    primaryRoute: R.WORKFLOW.MY_SUBMISSIONS,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "track-a-submission", title: "Track a submission" },
      { id: "resubmit-or-withdraw", title: "Resubmit or withdraw" },
      { id: "create-a-delegation", title: "Delegate your approvals" },
      { id: "review-and-revoke", title: "Review and revoke delegations" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["school.workflow.decide-approval", "school.procurement.raise-requisition"],
    estimatedMinutes: 6,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "medium",
    status: "published",
    article: () => import("../content/approvals-and-workflow/track-submissions-and-delegate"),
  },
  {
    id: "school.workflow.set-up-approvers",
    slug: "set-up-approver-groups-and-dynamic-roles",
    title: "Set up approver groups and Dynamic Roles",
    summary: "Build named pools of approvers, and rules that send each request to the right person by amount or requester.",
    category: "approvals-and-workflow",
    tags: ["approvers", "approver group", "dynamic role", "rules", "threshold", "members"],
    aliases: ["who approves", "approval rules", "spending limit", "approval threshold", "big purchases to proprietor", "role chosen by document", "add approver"],
    audiences: ["school-administrator"],
    routes: [R.WORKFLOW.APPROVER_GROUPS],
    actionIds: ["view-approver-groups", "view-dynamic-roles", "create-dynamic-role"],
    access: { mode: "any", permissions: [P.VIEW_APPROVER_GROUPS] },
    primaryRoute: R.WORKFLOW.APPROVER_GROUPS,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "build-a-group", title: "Build an approver group" },
      { id: "build-a-dynamic-role", title: "Build a Dynamic Role" },
      { id: "test-before-relying", title: "Test before a step relies on it" },
      { id: "switch-off-or-delete", title: "Switch off or delete" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["school.workflow.adjust-approval-path", "school.workflow.decide-approval"],
    estimatedMinutes: 9,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "high",
    status: "published",
    article: () => import("../content/approvals-and-workflow/set-up-approvers"),
  },
  {
    id: "school.workflow.adjust-approval-path",
    slug: "adjust-an-approval-path",
    title: "Adjust an approval path",
    summary: "Change who approves each step of a template, preview the result, and save your school's own version.",
    category: "approvals-and-workflow",
    tags: ["workflow template", "approval path", "stages", "steps", "approvers", "quorum"],
    aliases: ["change approval steps", "approval template", "who signs off", "add approval step", "remove approval step", "use xvs version", "approval rules"],
    audiences: ["school-administrator"],
    routes: [R.WORKFLOW.TEMPLATES, R.WORKFLOW.TEMPLATE_DETAIL, R.WORKFLOW.TEMPLATE_EDIT],
    actionIds: ["view-workflow-templates"],
    access: { mode: "any", permissions: [P.UPDATE_WORKFLOW_TEMPLATE] },
    primaryRoute: R.WORKFLOW.TEMPLATES,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "read-a-path", title: "Read an approval path" },
      { id: "adjust-the-steps", title: "Adjust the steps" },
      { id: "preview-approvers", title: "Preview who would approve" },
      { id: "save-or-go-back", title: "Save, or go back to the XVS version" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["school.workflow.set-up-approvers", "school.workflow.approval-notifications"],
    estimatedMinutes: 10,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "high",
    status: "published",
    article: () => import("../content/approvals-and-workflow/adjust-an-approval-path"),
  },
  {
    id: "school.workflow.approval-notifications",
    slug: "turn-approval-notifications-on-or-off",
    title: "Turn approval emails on or off",
    summary: "Decide in Settings whether approvals email approvers and requesters about what is happening, with one switch for the whole school.",
    category: "approvals-and-workflow",
    tags: ["notifications", "approval emails", "alerts", "workflow"],
    aliases: ["stop approval emails", "notify approvers", "approval alerts", "nobody told me it was approved"],
    audiences: ["school-administrator"],
    routes: [R.SETTINGS.NOTIFICATIONS],
    actionIds: ["view-workflow-notifications"],
    access: { mode: "any", permissions: [P.UPDATE_WORKFLOW_TEMPLATE] },
    primaryRoute: R.SETTINGS.NOTIFICATIONS,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "what-people-are-told", title: "What people are told" },
      { id: "switch-it", title: "Switch it on or off" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["school.workflow.adjust-approval-path"],
    estimatedMinutes: 2,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "medium",
    status: "published",
    article: () => import("../content/approvals-and-workflow/approval-notifications"),
  },
] as const satisfies readonly GuideRecord[];
