import { P } from "@/permissions";

import type { GuideRecord } from "../types";
import { OWNER, R } from "./shared";

export const CALENDAR_AND_TIMETABLES_GUIDES = [
  {
    id: "school.calendar.plan-the-calendar",
    slug: "plan-the-school-calendar",
    title: "Plan the school calendar",
    summary: "Read the calendar overview, then add holidays, breaks, exam periods and school events, narrow who each one covers, and mark days the school is closed.",
    category: "calendar-and-timetables",
    tags: ["calendar", "event", "holiday", "mid-term break", "exam period", "school closed"],
    aliases: ["add an event", "public holiday", "midterm", "mid term break", "term dates", "school closed", "pta meeting", "sports day", "calender", "what is coming up"],
    audiences: ["school-administrator", "branch-administrator", "teacher"],
    routes: [R.ACADEMIC_CALENDAR.INDEX, R.ACADEMIC_CALENDAR.EVENTS],
    actionIds: ["view-academic-calendar", "view-calendar-events", "add-event"],
    access: { mode: "any", permissions: [P.BROWSE_CALENDAR] },
    primaryRoute: R.ACADEMIC_CALENDAR.EVENTS,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "read-the-overview", title: "Read the calendar overview" },
      { id: "add-an-event", title: "Add an event" },
      { id: "who-it-covers", title: "Narrow who an event covers" },
      { id: "school-closed-days", title: "Mark days the school is closed" },
      { id: "find-and-change-events", title: "Find and change events" },
      { id: "warnings-after-saving", title: "Warnings after saving" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    estimatedMinutes: 6,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "low",
    status: "published",
    relatedGuideIds: [
      "school.calendar.term-view",
      "school.academics.sessions-and-terms",
      "school.timetables.schedule-exams",
    ],
    article: () => import("../content/calendar-and-timetables/plan-the-calendar"),
  },
  {
    id: "school.calendar.term-view",
    slug: "browse-the-year-in-term-view",
    title: "Browse the year in term view",
    summary: "See the school year as a timeline of terms and a month grid, and open any day to read, add or change its events.",
    category: "calendar-and-timetables",
    tags: ["term view", "month", "timeline", "calendar", "holiday", "event"],
    aliases: ["month calendar", "this term", "by term", "what is on this day", "calendar grid", "when is the break", "term calendar"],
    audiences: ["teacher", "school-administrator", "branch-administrator"],
    routes: [R.ACADEMIC_CALENDAR.TERM_VIEW],
    actionIds: ["view-term-calendar", "add-event"],
    access: { mode: "any", permissions: [P.BROWSE_CALENDAR] },
    primaryRoute: R.ACADEMIC_CALENDAR.TERM_VIEW,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "read-the-timeline", title: "Read the school year timeline" },
      { id: "use-the-month-grid", title: "Use the month calendar" },
      { id: "open-a-day", title: "Open a day" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    estimatedMinutes: 3,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "low",
    status: "published",
    relatedGuideIds: ["school.calendar.plan-the-calendar", "school.academics.sessions-and-terms"],
    article: () => import("../content/calendar-and-timetables/term-view"),
  },
  {
    id: "school.timetables.rooms-and-bell-schedule",
    slug: "set-up-rooms-and-the-bell-schedule",
    title: "Set up rooms and the bell schedule",
    summary: "Record the rooms lessons and exams happen in, then set the periods of the school day that every timetable is built on.",
    category: "calendar-and-timetables",
    tags: ["room", "classroom", "laboratory", "bell schedule", "period", "break", "lunch"],
    aliases: ["add a room", "add a period", "school day", "lesson times", "bells", "friday timetable", "short friday", "deactivate room", "venues", "labs", "halls"],
    audiences: ["school-administrator", "branch-administrator"],
    routes: [R.TIMETABLES.ROOMS, R.TIMETABLES.BELL_SCHEDULE],
    actionIds: ["view-rooms", "view-bell-schedule", "add-room", "add-period"],
    access: { mode: "any", permissions: [P.BROWSE_TIMETABLES] },
    primaryRoute: R.TIMETABLES.BELL_SCHEDULE,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "add-a-room", title: "Add a room" },
      { id: "manage-rooms", title: "Deactivate or delete a room" },
      { id: "add-periods", title: "Add the periods of the day" },
      { id: "day-schedules", title: "Give one weekday its own schedule" },
      { id: "read-the-school-day", title: "Read the school day" },
      { id: "remove-a-period", title: "Remove a period" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    estimatedMinutes: 6,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "medium",
    status: "published",
    relatedGuideIds: ["school.timetables.build-class-timetable", "school.timetables.schedule-exams"],
    article: () => import("../content/calendar-and-timetables/rooms-and-bell-schedule"),
  },
  {
    id: "school.timetables.build-class-timetable",
    slug: "build-and-publish-class-timetables",
    title: "Build and publish class timetables",
    summary: "Fill each class's week with lessons, deal with teacher and room clashes, copy a week from another class, and publish it.",
    category: "calendar-and-timetables",
    tags: ["timetable", "lesson", "clash", "publish", "duplicate", "class"],
    aliases: ["class timetable", "add a lesson", "double booked", "teacher clash", "copy timetable", "duplicate timetable", "publish timetable", "print timetable", "clear timetable", "lesson plan"],
    audiences: ["school-administrator", "branch-administrator", "teacher"],
    routes: [R.TIMETABLES.CLASSES],
    actionIds: ["view-class-timetables"],
    access: { mode: "any", permissions: [P.BROWSE_TIMETABLES] },
    walkthroughId: "walkthrough.school.timetables.build-class-timetable",
    primaryRoute: R.TIMETABLES.CLASSES,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "pick-a-class", title: "Pick a class" },
      { id: "add-lessons", title: "Add and change lessons" },
      { id: "clashes", title: "Clashes" },
      { id: "duplicate-a-week", title: "Copy another class's week" },
      { id: "publish", title: "Publish the timetable" },
      { id: "print-and-clear", title: "Print, export or clear" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    estimatedMinutes: 8,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "medium",
    featured: true,
    status: "published",
    relatedGuideIds: [
      "school.timetables.rooms-and-bell-schedule",
      "school.timetables.teacher-timetable",
      "school.academics.classes-and-arms",
      "school.academics.subjects",
    ],
    article: () => import("../content/calendar-and-timetables/build-class-timetable"),
  },
  {
    id: "school.timetables.teacher-timetable",
    slug: "read-a-teachers-timetable",
    title: "Read a teacher's timetable",
    summary: "See one teacher's week across every class they teach, including free periods and any double-bookings.",
    category: "calendar-and-timetables",
    tags: ["teacher timetable", "free period", "clash", "workload", "staff"],
    aliases: ["my timetable", "staff timetable", "who is free", "teacher schedule", "free periods", "is he double booked", "teaching load"],
    audiences: ["teacher", "school-administrator", "branch-administrator"],
    routes: [R.TIMETABLES.TEACHERS],
    actionIds: ["view-teacher-timetables"],
    access: { mode: "any", permissions: [P.BROWSE_TIMETABLES] },
    primaryRoute: R.TIMETABLES.TEACHERS,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "pick-a-teacher", title: "Pick a teacher" },
      { id: "read-the-week", title: "Read the week" },
      { id: "clashes", title: "Clashes" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    estimatedMinutes: 3,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "low",
    status: "published",
    relatedGuideIds: ["school.timetables.build-class-timetable"],
    article: () => import("../content/calendar-and-timetables/teacher-timetable"),
  },
  {
    id: "school.timetables.schedule-exams",
    slug: "schedule-exams",
    title: "Schedule exams",
    summary: "Place papers inside a dated exam period, give each a room and an invigilator, resolve clashes and publish the exam timetable.",
    category: "calendar-and-timetables",
    tags: ["exam", "paper", "invigilator", "sitting", "exam timetable", "publish"],
    aliases: ["exam timetable", "add a paper", "exam period", "invigilation", "morning paper", "afternoon paper", "sittings", "exams", "print exam timetable"],
    audiences: ["school-administrator", "branch-administrator", "teacher"],
    routes: [R.TIMETABLES.EXAMS],
    actionIds: ["view-exam-scheduling"],
    access: { mode: "any", permissions: [P.BROWSE_EXAMS] },
    primaryRoute: R.TIMETABLES.EXAMS,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "start-with-an-exam-period", title: "Start with an exam period" },
      { id: "add-papers", title: "Add papers" },
      { id: "clashes-and-refusals", title: "Clashes and refusals" },
      { id: "board-and-list", title: "Board, list and filters" },
      { id: "publish-and-print", title: "Publish and print" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    estimatedMinutes: 7,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "medium",
    status: "published",
    relatedGuideIds: [
      "school.calendar.plan-the-calendar",
      "school.timetables.rooms-and-bell-schedule",
    ],
    article: () => import("../content/calendar-and-timetables/schedule-exams"),
  },
] as const satisfies readonly GuideRecord[];
