import { P } from "@/permissions";

import type { GuideRecord } from "../types";
import { OWNER, R } from "./shared";

export const DATA_IMPORTS_AND_EXPORTS_GUIDES = [
  {
    id: "school.data.import-spreadsheet",
    slug: "import-records-from-a-spreadsheet",
    title: "Import records from a spreadsheet",
    summary: "Load many students or staff at once: fill in the template, upload it, clear every error, and confirm the import.",
    category: "data-imports-and-exports",
    tags: ["import", "spreadsheet", "upload", "CSV", "XLSX", "bulk", "template", "validation"],
    aliases: ["upload spreadsheet", "bulk upload", "import students", "import staff", "upload excel", "load class list", "import errors", "upload roll"],
    audiences: ["school-administrator", "admissions-and-records"],
    routes: [R.DATA_IMPORTS.BATCHES.NEW],
    actionIds: ["upload-import-batch"],
    access: { mode: "any", permissions: [P.UPLOAD_IMPORT_BATCH] },
    walkthroughId: "walkthrough.school.data.import-spreadsheet",
    primaryRoute: R.DATA_IMPORTS.BATCHES.NEW,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "prepare-the-file", title: "Prepare the file" },
      { id: "run-the-import", title: "Run the import" },
      { id: "fix-errors", title: "Fix errors and warnings" },
      { id: "after-the-import", title: "After the import" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["school.data.check-import", "school.data.import-templates"],
    estimatedMinutes: 10,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "high",
    status: "published",
    article: () => import("../content/data-imports-and-exports/import-from-a-spreadsheet"),
  },
  {
    id: "school.data.check-import",
    slug: "check-an-import-and-fix-its-rows",
    title: "Check an import and fix its rows",
    summary: "Find any upload in the school's import history, see what happened to each row, and correct what did not go in.",
    category: "data-imports-and-exports",
    tags: ["import batch", "import history", "issues", "row results", "failed import", "partial import"],
    aliases: ["did the import work", "import failed", "missing after import", "upload history", "partly imported", "which rows failed"],
    audiences: ["school-administrator", "admissions-and-records"],
    routes: [R.DATA_IMPORTS.BATCHES.INDEX, R.DATA_IMPORTS.BATCHES.VIEW_PATH],
    actionIds: ["view-import-batches"],
    access: { mode: "any", permissions: [P.VIEW_IMPORT_BATCHES] },
    primaryRoute: R.DATA_IMPORTS.BATCHES.INDEX,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "find-a-batch", title: "Find a batch" },
      { id: "read-the-batch", title: "Read the batch" },
      { id: "finish-or-fix", title: "Finish or fix a batch" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["school.data.import-spreadsheet", "school.data.export-and-download"],
    estimatedMinutes: 6,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "medium",
    status: "published",
    article: () => import("../content/data-imports-and-exports/check-an-import"),
  },
  {
    id: "school.data.import-templates",
    slug: "download-an-import-template",
    title: "Download an import template",
    summary: "Find the spreadsheet layout for a kind of record, read what each column expects, and download it to fill in.",
    category: "data-imports-and-exports",
    tags: ["import template", "columns", "required fields", "CSV", "XLSX", "download"],
    aliases: ["spreadsheet format", "which columns", "import format", "blank template", "download template"],
    audiences: ["school-administrator", "admissions-and-records"],
    routes: [
      R.DATA_IMPORTS.TEMPLATES.INDEX,
      R.DATA_IMPORTS.TEMPLATES.NEW,
      R.DATA_IMPORTS.TEMPLATES.VIEW_PATH,
      R.DATA_IMPORTS.TEMPLATES.EDIT_PATH,
    ],
    actionIds: ["view-import-templates"],
    access: { mode: "any", permissions: [P.VIEW_IMPORT_TEMPLATES] },
    walkthroughId: "walkthrough.school.data.import-templates",
    primaryRoute: R.DATA_IMPORTS.TEMPLATES.INDEX,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "find-a-template", title: "Find a template" },
      { id: "use-it-well", title: "Use it well" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["school.data.import-spreadsheet"],
    estimatedMinutes: 3,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "low",
    status: "published",
    article: () => import("../content/data-imports-and-exports/import-templates"),
  },
  {
    id: "school.data.saved-export",
    slug: "build-and-run-a-saved-export",
    title: "Build and run a saved export",
    summary: "Build an export once with the columns, filters and file layout you need, then run it whenever you want a fresh file.",
    category: "data-imports-and-exports",
    tags: ["export", "saved export", "builder", "columns", "filters", "Excel", "CSV", "report"],
    aliases: ["new export", "custom report", "export builder", "download report", "regular report", "export to excel"],
    audiences: ["school-administrator"],
    routes: [R.EXPORT.SAVED, R.EXPORT.NEW, R.EXPORT.EDIT_PATH],
    actionIds: ["view-saved-exports", "create-export"],
    access: { mode: "any", permissions: [P.VIEW_SAVED_EXPORTS, P.CREATE_EXPORT] },
    walkthroughId: "walkthrough.school.data.saved-export",
    primaryRoute: R.EXPORT.SAVED,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "choose-the-data", title: "Choose the data" },
      { id: "choose-columns-and-filters", title: "Choose columns and filters" },
      { id: "choose-the-file", title: "Choose the file" },
      { id: "review-save-and-run", title: "Review, save and run" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["school.data.export-and-download"],
    estimatedMinutes: 8,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "medium",
    status: "published",
    article: () => import("../content/data-imports-and-exports/build-a-saved-export"),
  },
  {
    id: "school.data.export-and-download",
    slug: "export-a-list-and-download-the-file",
    title: "Export a list and download the file",
    summary: "Use the Export button on a list, find the file under Files, and understand an export that failed or left something out.",
    category: "data-imports-and-exports",
    tags: ["export", "download", "files", "queues", "excel", "csv", "failed export"],
    aliases: ["download report", "export this list", "download to excel", "where is my file", "export failed", "file expired", "export to csv"],
    audiences: ["all-users", "school-administrator", "finance-officer", "procurement-officer"],
    routes: [R.EXPORT.FILES, R.EXPORT.RUN_PATH, R.EXPORT.QUEUES],
    actionIds: ["view-export-files", "view-export-queues"],
    access: { mode: "any", permissions: [P.VIEW_EXPORT_RUNS] },
    walkthroughId: "walkthrough.school.data.export-and-download",
    primaryRoute: R.EXPORT.FILES,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "export-a-list", title: "Export a list" },
      { id: "download-the-file", title: "Download the file" },
      { id: "when-an-export-goes-wrong", title: "When an export goes wrong" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["school.data.saved-export", "school.data.check-import"],
    estimatedMinutes: 5,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "medium",
    status: "published",
    article: () => import("../content/data-imports-and-exports/export-and-download"),
  },
] as const satisfies readonly GuideRecord[];
