import { P } from "@/permissions";

import type { GuideRecord } from "../types";
import { OWNER, R } from "./shared";

/**
 * Guides for the Finance area.
 *
 * The screens come from the shared finance package, and this app mounts only
 * the part of it a school uses: one set of books, billed in naira, with no
 * analytical dimensions. Payouts and batches are offered only where the
 * platform holds the school's online money. Every guide here names only
 * mounted screens, and each is gated on the view permission its screen's
 * sidebar entry checks.
 */
export const FINANCE_AND_PAYMENTS_GUIDES = [
  {
    id: "school.finance.bill-school-fees",
    slug: "bill-school-fees-with-fee-structures",
    title: "Bill school fees with fee structures",
    summary: "Build a {term}'s fee structure, bill the classes it is for after a preview, and check the invoices.",
    category: "finance-and-payments",
    tags: ["school fees", "fee structure", "invoice", "bill", "term fees", "customer", "billing", "receivables"],
    aliases: [
      "bill parents", "raise fee invoices", "generate invoices", "batch generate", "term bills",
      "fee schedule", "new invoice", "add customer", "new customer", "void invoice", "who owes",
      "debtors", "owing", "school fees invoice", "import opening balances", "arrears from before",
      "old fees owed",
    ],
    audiences: ["finance-officer", "school-administrator"],
    routes: [
      R.FINANCE.RECEIVABLES,
      `${R.FINANCE.RECEIVABLES}/invoices`,
      `${R.FINANCE.RECEIVABLES}/customers`,
      `${R.FINANCE.RECEIVABLES}/fee-structures`,
    ],
    access: { mode: "any", permissions: [P.FIN_VIEW_INVOICES, P.FIN_VIEW_FEE_STRUCTURES, P.FIN_VIEW_CUSTOMERS] },
    primaryRoute: `${R.FINANCE.RECEIVABLES}/fee-structures`,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "add-customers", title: "How pupils get an account" },
      { id: "build-a-fee-structure", title: "Build a fee structure" },
      { id: "generate-invoices", title: "Generate the {term}'s invoices" },
      { id: "raise-a-single-invoice", title: "Raise a single invoice" },
      { id: "check-an-invoice", title: "Check an invoice" },
      { id: "import-opening-balances", title: "Bring in fees owed from before" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: [
      "school.finance.record-fee-payments",
      "school.finance.reduce-a-fee-bill",
      "school.finance.fee-due-dates",
      "school.finance.email-fee-documents",
      "school.finance.deferred-income-deposits-and-doubtful-debts",
    ],
    estimatedMinutes: 12,
    owner: OWNER,
    reviewedAt: "2026-10-05",
    risk: "high",
    featured: true,
    status: "published",
    article: () => import("../content/finance-and-payments/bill-school-fees"),
  },
  {
    id: "school.finance.record-fee-payments",
    slug: "record-a-fee-payment-and-allocate-the-receipt",
    title: "Record a fee payment and allocate the receipt",
    summary: "Record money a parent paid, apply it to the right bills, and print, email or void the receipt.",
    category: "finance-and-payments",
    tags: ["receipt", "payment", "school fees", "allocation", "teller", "bank transfer", "cash", "receivables"],
    aliases: [
      "record payment", "parent paid", "receive fees", "fee payment", "apply payment", "allocate receipt",
      "unallocated receipt", "print receipt", "void receipt", "part payment", "overpayment", "credit balance",
    ],
    audiences: ["finance-officer"],
    routes: [`${R.FINANCE.RECEIVABLES}/receipts`],
    access: { mode: "any", permissions: [P.FIN_VIEW_PAYMENTS] },
    walkthroughId: "walkthrough.school.finance.record-fee-payments",
    primaryRoute: `${R.FINANCE.RECEIVABLES}/receipts`,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "choose-where-to-record", title: "Choose where to record it" },
      { id: "record-the-receipt", title: "Record the receipt" },
      { id: "allocate-the-receipt", title: "Allocate the receipt" },
      { id: "print-or-email", title: "Print or email the receipt" },
      { id: "void-a-receipt", title: "Void a receipt recorded in error" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: [
      "school.finance.bill-school-fees",
      "school.finance.payer-payments-and-credit-transfers",
      "school.finance.online-fee-payments",
      "school.finance.email-fee-documents",
      "school.finance.reconcile-the-bank",
    ],
    estimatedMinutes: 8,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "high",
    featured: true,
    status: "published",
    article: () => import("../content/finance-and-payments/record-fee-payments"),
  },
  {
    id: "school.finance.payer-payments-and-credit-transfers",
    slug: "one-payment-for-several-children-and-moving-credit",
    title: "One payment for several children, and moving credit",
    summary: "Link a parent or sponsor to the children they pay for, record their payment once with one receipt per child, and move credit between children.",
    category: "finance-and-payments",
    tags: ["payer", "sponsor", "siblings", "payer payment", "credit transfer", "receipt", "credit balance"],
    aliases: [
      "sponsor payment", "one payment for several children", "split a payment", "pay for siblings",
      "payer links", "move credit", "sibling credit", "transfer an overpayment", "parent pays for two children",
    ],
    audiences: ["finance-officer", "approver"],
    routes: [
      `${R.FINANCE.RECEIVABLES}/payer-payments`,
      `${R.FINANCE.RECEIVABLES}/credit-transfers`,
      `${R.FINANCE.RECEIVABLES}/customers`,
    ],
    access: { mode: "any", permissions: [P.FIN_VIEW_PAYMENTS, P.FIN_VIEW_CREDIT_TRANSFERS, P.FIN_VIEW_CUSTOMERS] },
    primaryRoute: `${R.FINANCE.RECEIVABLES}/payer-payments`,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "link-payers", title: "Link a payer to the children they pay for" },
      { id: "record-a-payer-payment", title: "Record one payment for several children" },
      { id: "other-branch", title: "A child billed at another branch" },
      { id: "void-a-payer-payment", title: "Void a payer payment" },
      { id: "credit-transfer", title: "Move credit from one child to another" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: [
      "school.finance.record-fee-payments",
      "school.finance.branches-working-together",
      "school.finance.deferred-income-deposits-and-doubtful-debts",
    ],
    estimatedMinutes: 8,
    owner: OWNER,
    reviewedAt: "2026-10-05",
    risk: "high",
    status: "published",
    article: () => import("../content/finance-and-payments/payer-payments-and-credit-transfers"),
  },
  {
    id: "school.finance.email-fee-documents",
    slug: "email-an-invoice-receipt-or-statement-to-a-parent",
    title: "Email an invoice, receipt or statement to a parent",
    summary: "Check the address, send the document, and retry a delivery that failed.",
    category: "finance-and-payments",
    tags: ["email", "invoice", "receipt", "statement", "parent", "delivery"],
    aliases: [
      "send invoice", "email invoice", "email receipt", "send statement", "statement of account",
      "parent did not get invoice", "resend receipt", "delivery failed", "wrong email address",
    ],
    audiences: ["finance-officer"],
    routes: [
      `${R.FINANCE.RECEIVABLES}/invoices`,
      `${R.FINANCE.RECEIVABLES}/receipts`,
      `${R.FINANCE.RECEIVABLES}/customers`,
    ],
    access: { mode: "any", permissions: [P.FIN_EMAIL_INVOICE, P.FIN_EMAIL_RECEIPT, P.FIN_EMAIL_STATEMENT] },
    walkthroughId: "walkthrough.school.finance.email-fee-documents",
    primaryRoute: `${R.FINANCE.RECEIVABLES}/invoices`,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "choose-the-document", title: "Choose the document" },
      { id: "check-and-send", title: "Check and send" },
      { id: "retry-a-failed-send", title: "Retry a failed send" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["school.finance.bill-school-fees", "school.finance.record-fee-payments"],
    estimatedMinutes: 4,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "medium",
    status: "published",
    article: () => import("../content/finance-and-payments/email-fee-documents"),
  },
  {
    id: "school.finance.reduce-a-fee-bill",
    slug: "reduce-a-fee-bill-with-a-concession-or-credit-note",
    title: "Reduce a fee bill with a concession or credit note",
    summary: "Give a scholarship, discount or waiver, correct an overcharge, or add a missed charge.",
    category: "finance-and-payments",
    tags: ["concession", "scholarship", "discount", "waiver", "credit note", "debit note", "school fees"],
    aliases: [
      "sibling discount", "staff child discount", "fee waiver", "grant scholarship", "reduce fees",
      "overcharged", "wrong fee", "extra charge", "issue credit note", "issue debit note",
    ],
    audiences: ["finance-officer", "approver"],
    routes: [`${R.FINANCE.RECEIVABLES}/credit-notes`, `${R.FINANCE.RECEIVABLES}/concessions`],
    access: { mode: "any", permissions: [P.FIN_VIEW_CREDIT_NOTES, P.FIN_VIEW_CONCESSIONS] },
    walkthroughId: "walkthrough.school.finance.reduce-a-fee-bill",
    primaryRoute: `${R.FINANCE.RECEIVABLES}/concessions`,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "choose-the-adjustment", title: "Choose the right adjustment" },
      { id: "grant-a-concession", title: "Grant a concession" },
      { id: "issue-a-note", title: "Issue a credit or debit note" },
      { id: "approval", title: "When approval is needed" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["school.finance.bill-school-fees", "school.finance.refund-or-write-off", "school.finance.payer-payments-and-credit-transfers"],
    estimatedMinutes: 7,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "high",
    status: "published",
    article: () => import("../content/finance-and-payments/reduce-a-fee-bill"),
  },
  {
    id: "school.finance.refund-or-write-off",
    slug: "refund-a-parent-or-write-off-unpaid-fees",
    title: "Refund a parent or write off unpaid fees",
    summary: "Pay back credit on a pupil's account, or clear fees the school will not collect, with approval.",
    category: "finance-and-payments",
    tags: ["refund", "write-off", "write off", "bad debt", "credit balance", "overpayment"],
    aliases: [
      "refund parent", "pay back overpayment", "pupil left with credit", "write off fees",
      "uncollectable fees", "bad debt", "batch refunds", "batch write-offs",
    ],
    audiences: ["finance-officer", "approver"],
    routes: [`${R.FINANCE.RECEIVABLES}/refunds`],
    access: { mode: "any", permissions: [P.FIN_VIEW_REFUNDS, P.FIN_VIEW_WRITE_OFFS] },
    walkthroughId: "walkthrough.school.finance.refund-or-write-off",
    primaryRoute: `${R.FINANCE.RECEIVABLES}/refunds`,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "refund-or-write-off", title: "Refund or write-off?" },
      { id: "process-a-refund", title: "Process a refund" },
      { id: "write-off-a-debt", title: "Write off a debt" },
      { id: "batch-actions", title: "Many at once" },
      { id: "approval-and-posting", title: "Approval and posting" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: [
      "school.finance.reduce-a-fee-bill", "school.finance.record-fee-payments", "school.finance.reconcile-the-bank",
      "school.finance.deferred-income-deposits-and-doubtful-debts",
    ],
    estimatedMinutes: 7,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "high",
    status: "published",
    article: () => import("../content/finance-and-payments/refund-or-write-off"),
  },
  {
    id: "school.finance.deferred-income-deposits-and-doubtful-debts",
    slug: "fees-billed-ahead-deposits-and-doubtful-debts",
    title: "Fees billed ahead, deposits and doubtful debts",
    summary: "Release fees billed before their {term} to income, hold and return refundable deposits, run the doubtful-debt allowance, and set the receivables rules.",
    category: "finance-and-payments",
    tags: ["deferred income", "deposit", "caution deposit", "doubtful debts", "provision", "receivables settings", "unearned fees"],
    aliases: [
      "unearned fees", "fees billed ahead", "release income", "caution deposit", "refundable deposit",
      "return deposit", "forfeit deposit", "bad debt allowance", "provision run", "receivables settings",
      "apply credit to new bills", "concession limit",
    ],
    audiences: ["finance-officer", "school-administrator", "approver"],
    routes: [
      `${R.FINANCE.RECEIVABLES}/deferred-income`,
      `${R.FINANCE.RECEIVABLES}/deposits`,
      `${R.FINANCE.RECEIVABLES}/provisions`,
      `${R.FINANCE.SETTINGS}/receivables`,
    ],
    access: { mode: "any", permissions: [P.FIN_VIEW_DEFERRED_INCOME, P.FIN_VIEW_DEPOSITS, P.FIN_VIEW_PROVISIONS, P.FIN_VIEW_SETTINGS] },
    primaryRoute: `${R.FINANCE.RECEIVABLES}/deferred-income`,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "deferred-income", title: "Fees billed ahead" },
      { id: "deposits", title: "Refundable deposits" },
      { id: "doubtful-debts", title: "Doubtful debts" },
      { id: "receivables-settings", title: "Receivables settings" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: [
      "school.finance.bill-school-fees",
      "school.finance.refund-or-write-off",
      "school.finance.close-a-period",
      "school.finance.payer-payments-and-credit-transfers",
    ],
    estimatedMinutes: 9,
    owner: OWNER,
    reviewedAt: "2026-10-05",
    risk: "high",
    status: "published",
    article: () => import("../content/finance-and-payments/deferred-income-deposits-and-doubtful-debts"),
  },
  {
    id: "school.finance.payment-plans",
    slug: "let-a-parent-pay-fees-in-installments",
    title: "Let a parent pay fees in installments",
    summary: "Spread a bill into dated installments, record each one, and cancel a plan safely.",
    category: "finance-and-payments",
    tags: ["payment plan", "installment", "instalment", "school fees", "schedule", "part payment"],
    aliases: [
      "pay in parts", "pay in installments", "instalment plan", "spread fees", "fee payment schedule",
      "record installment", "cancel payment plan", "plan at risk",
    ],
    audiences: ["finance-officer"],
    routes: [`${R.FINANCE.RECEIVABLES}/payment-plans`],
    access: { mode: "any", permissions: [P.FIN_VIEW_PAYMENT_PLANS] },
    walkthroughId: "walkthrough.school.finance.payment-plans",
    primaryRoute: `${R.FINANCE.RECEIVABLES}/payment-plans`,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "create-the-plan", title: "Create the plan" },
      { id: "record-an-installment", title: "Record an installment" },
      { id: "follow-and-cancel", title: "Follow a plan, or cancel it" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["school.finance.bill-school-fees", "school.finance.record-fee-payments"],
    estimatedMinutes: 5,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "medium",
    status: "published",
    article: () => import("../content/finance-and-payments/payment-plans"),
  },
  {
    id: "school.finance.fee-reminders",
    slug: "send-reminders-for-overdue-fees",
    title: "Send reminders for overdue fees",
    summary: "Set the school's reminder ladder, raise reminders for overdue bills, and send them.",
    category: "finance-and-payments",
    tags: ["dunning", "reminder", "overdue", "school fees", "owing", "debtors", "aging"],
    aliases: [
      "chase fees", "fee reminder", "overdue fees", "remind parents", "debtors list",
      "who is owing", "reminder policy", "run reminders",
    ],
    audiences: ["finance-officer"],
    routes: [`${R.FINANCE.RECEIVABLES}/dunning`],
    access: { mode: "any", permissions: [P.FIN_VIEW_DUNNING] },
    primaryRoute: `${R.FINANCE.RECEIVABLES}/dunning`,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "read-the-aging", title: "See who is overdue" },
      { id: "set-up-a-policy", title: "Set up the reminder ladder" },
      { id: "run-and-send", title: "Raise and send reminders" },
      { id: "one-parent", title: "Remind one parent" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["school.finance.bill-school-fees", "school.finance.payment-plans"],
    estimatedMinutes: 6,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "medium",
    status: "published",
    article: () => import("../content/finance-and-payments/fee-reminders"),
  },
  {
    id: "school.finance.online-fee-payments",
    slug: "collect-fees-online-with-payment-links-and-virtual-accounts",
    title: "Collect fees online with payment links and virtual accounts",
    summary: "Send a parent a payment link, follow online payments, and give a pupil a dedicated account number.",
    category: "finance-and-payments",
    tags: ["online payment", "payment link", "checkout", "virtual account", "collections", "paystack", "transfer"],
    aliases: [
      "pay online", "payment link", "request payment", "parent paid online", "payment pending",
      "dedicated account", "virtual account number", "collections",
    ],
    audiences: ["finance-officer"],
    routes: [
      R.FINANCE.COLLECTIONS,
      `${R.FINANCE.COLLECTIONS}/gateway`,
      `${R.FINANCE.COLLECTIONS}/virtual-accounts`,
      R.FINANCE.PAYMENTS,
      `${R.FINANCE.PAYMENTS}/payouts`,
      `${R.FINANCE.PAYMENTS}/batches`,
      `${R.FINANCE.PAYMENTS}/settlement`,
      `${R.FINANCE.PAYMENTS}/transactions`,
      `${R.FINANCE.PAYMENTS}/webhooks`,
      `${R.FINANCE.PAYMENTS}/held-settlements`,
    ],
    access: { mode: "any", permissions: [P.PAY_VIEW_COLLECTIONS, P.PAY_VIEW_PAYOUTS, P.PAY_VIEW_PAYMENT_REPORTS, P.PAY_VIEW_WEBHOOKS] },
    walkthroughId: "walkthrough.school.finance.online-fee-payments",
    primaryRoute: R.FINANCE.COLLECTIONS,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "send-a-payment-link", title: "Send a payment link for one bill" },
      { id: "create-a-checkout", title: "Create a checkout from Collections" },
      { id: "follow-a-payment", title: "Follow a payment" },
      { id: "virtual-accounts", title: "Give a pupil a virtual account" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["school.finance.record-fee-payments", "school.finance.reconcile-the-bank"],
    estimatedMinutes: 6,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "high",
    status: "published",
    article: () => import("../content/finance-and-payments/online-fee-payments"),
  },
  {
    id: "school.finance.reconcile-the-bank",
    slug: "set-up-a-bank-account-and-reconcile-it",
    title: "Set up a bank account and reconcile it",
    summary: "Add the school's bank accounts, import statements, match every line, and complete the reconciliation.",
    category: "finance-and-payments",
    tags: ["bank", "reconciliation", "statement", "matching", "bank charges", "bank account"],
    aliases: [
      "bank recon", "reconcile bank", "import statement", "upload statement", "match bank line",
      "bank charges", "new bank account", "unreconciled difference",
    ],
    audiences: ["finance-officer", "approver"],
    routes: [R.FINANCE.BANKING, R.FINANCE.BANK_RECON],
    access: { mode: "any", permissions: [P.FIN_VIEW_BANK_ACCOUNTS] },
    walkthroughId: "walkthrough.school.finance.reconcile-the-bank",
    primaryRoute: R.FINANCE.BANK_RECON,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "set-up-the-account", title: "Set up the bank account" },
      { id: "import-the-statement", title: "Import the statement" },
      { id: "match-lines", title: "Match the lines" },
      { id: "resolve-the-rest", title: "Deal with what is left" },
      { id: "complete", title: "Complete the reconciliation" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["school.finance.record-fee-payments", "school.finance.bank-money-and-split", "school.finance.close-a-period"],
    estimatedMinutes: 10,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "high",
    status: "published",
    article: () => import("../content/finance-and-payments/reconcile-the-bank"),
  },
  {
    id: "school.finance.bank-money-and-split",
    slug: "record-bank-money-and-split-a-shared-account",
    title: "Record bank money and split a shared account",
    summary: "Record capital, loans, interest and charges, move money between a branch's accounts, and split a shared bank account into branch accounts.",
    category: "finance-and-payments",
    tags: ["bank", "bank transaction", "bank transfer", "capital", "loan", "branch", "split", "shared account"],
    aliases: [
      "owner capital", "loan received", "bank interest", "bank charge", "drawings", "transfer between accounts",
      "move money to savings", "split bank account by branch", "shared bank account", "account has no branch",
      "void bank transaction",
    ],
    audiences: ["finance-officer", "school-administrator", "approver"],
    routes: [R.FINANCE.BANKING],
    access: { mode: "any", permissions: [P.FIN_VIEW_BANK_ACCOUNTS] },
    primaryRoute: R.FINANCE.BANKING,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "bank-transactions", title: "Record money in or out" },
      { id: "bank-transfers", title: "Move money between two accounts" },
      { id: "approval-and-void", title: "Approval, and voiding a mistake" },
      { id: "split-a-shared-account", title: "Split a shared account by branch" },
      { id: "split-differences", title: "What happens to each branch's difference" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["school.finance.reconcile-the-bank", "school.finance.branches-working-together"],
    estimatedMinutes: 8,
    owner: OWNER,
    reviewedAt: "2026-10-05",
    risk: "high",
    status: "published",
    article: () => import("../content/finance-and-payments/bank-money-and-split"),
  },
  {
    id: "school.finance.staff-expense-claims",
    slug: "pay-back-a-staff-expense-claim",
    title: "Pay back a staff expense claim",
    summary: "Record what a member of staff spent, attach the receipts, approve the claim and reimburse them.",
    category: "finance-and-payments",
    tags: ["expense claim", "reimbursement", "staff", "receipt", "out of pocket"],
    aliases: [
      "staff claim", "reimburse staff", "expense claim", "attach receipt", "approve claim",
      "pay claim", "void claim",
    ],
    audiences: ["finance-officer", "approver"],
    routes: [R.FINANCE.EXPENSES, `${R.FINANCE.EXPENSES}/claims`],
    access: { mode: "any", permissions: [P.FIN_VIEW_EXPENSE_CLAIMS] },
    walkthroughId: "walkthrough.school.finance.staff-expense-claims",
    primaryRoute: `${R.FINANCE.EXPENSES}/claims`,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "create-the-claim", title: "Create the claim" },
      { id: "approve-the-claim", title: "Approve the claim" },
      { id: "pay-the-claim", title: "Pay the member of staff" },
      { id: "void-a-mistake", title: "Void a claim approved in error" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["school.finance.petty-cash", "school.finance.reconcile-the-bank"],
    estimatedMinutes: 6,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "high",
    status: "published",
    article: () => import("../content/finance-and-payments/staff-expense-claims"),
  },
  {
    id: "school.finance.petty-cash",
    slug: "run-a-petty-cash-float",
    title: "Run a petty cash float",
    summary: "Set up a float, record each spend as a voucher, top it up, bank cash above a lower float, and close, reopen or void.",
    category: "finance-and-payments",
    tags: ["petty cash", "float", "voucher", "imprest", "cash", "replenish", "return", "close fund"],
    aliases: [
      "petty cash", "cash tin", "new voucher", "top up float", "replenish petty cash",
      "establish float", "void voucher", "reduce float", "bank petty cash", "close petty cash fund",
      "reopen petty cash", "petty cash return", "cash over and short", "petty cash approval",
    ],
    audiences: ["finance-officer", "approver"],
    routes: [R.FINANCE.EXPENSES, `${R.FINANCE.EXPENSES}/petty-cash`],
    access: { mode: "any", permissions: [P.FIN_VIEW_PETTY_CASH] },
    walkthroughId: "walkthrough.school.finance.petty-cash",
    primaryRoute: `${R.FINANCE.EXPENSES}/petty-cash`,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "establish-the-float", title: "Set up the float" },
      { id: "record-a-voucher", title: "Record a spend" },
      { id: "watch-the-balance", title: "Watch the balance" },
      { id: "replenish", title: "Top up the float" },
      { id: "reduce-the-float", title: "Bank the cash above a lower float" },
      { id: "close-the-fund", title: "Close a fund" },
      { id: "reopen-a-fund", title: "Reopen a closed fund" },
      { id: "returns-and-void", title: "Returns, and voiding one" },
      { id: "approval", title: "When a return needs a second person" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["school.finance.staff-expense-claims", "school.finance.reconcile-the-bank", "school.finance.finance-settings"],
    estimatedMinutes: 9,
    owner: OWNER,
    reviewedAt: "2026-10-05",
    risk: "high",
    status: "published",
    article: () => import("../content/finance-and-payments/petty-cash"),
  },
  {
    id: "school.finance.branches-working-together",
    slug: "send-money-and-share-costs-between-branches",
    title: "Send money and share costs between branches",
    summary: "Send or ask for money between branches, see who owes whom, forward money collected for another branch, share costs and move a pupil's account.",
    category: "finance-and-payments",
    tags: ["branch", "inter-branch", "transfer", "recharge", "held receipt", "shared cost"],
    aliases: [
      "inter-branch transfer", "send money to branch", "ask branch for money", "who owes whom",
      "held receipt", "forward receipt", "recharge cost", "shared cost rule", "move balance to branch",
    ],
    audiences: ["finance-officer", "approver"],
    routes: [
      "/finance/inter-branch", "/finance/inter-branch/transfers", "/finance/inter-branch/balances",
      "/finance/inter-branch/held-receipts", "/finance/inter-branch/recharges", "/finance/inter-branch/cost-rules",
    ],
    access: { mode: "any", permissions: [P.FIN_VIEW_INTERBRANCH, P.FIN_VIEW_PAYMENTS] },
    primaryRoute: "/finance/inter-branch/transfers",
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "send-or-ask", title: "Send money, or ask for it" },
      { id: "who-owes-whom", title: "See who owes whom" },
      { id: "held-receipts", title: "Money collected for another branch" },
      { id: "shared-costs", title: "Share a cost" },
      { id: "move-a-balance", title: "Move a pupil's account to another branch" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["school.finance.reconcile-the-bank", "school.finance.close-a-period"],
    estimatedMinutes: 8,
    owner: OWNER,
    reviewedAt: "2026-10-05",
    risk: "high",
    status: "published",
    article: () => import("../content/finance-and-payments/branches-working-together"),
  },
  {
    id: "school.finance.run-payroll",
    slug: "run-and-pay-the-monthly-payroll",
    title: "Run and pay the monthly payroll",
    summary: "Choose the payroll settings, keep one salary record per person, record joiners' earlier pay, generate, post and pay a run, and issue payslips and statutory returns.",
    category: "finance-and-payments",
    tags: ["payroll", "salary", "payslip", "PAYE", "pension", "NHF", "staff pay", "branch", "earlier pay"],
    aliases: [
      "pay salaries", "run payroll", "salary run", "print payslip", "salary structure",
      "add employee salary", "pension schedule", "paye schedule", "void payroll run", "branch payroll",
      "move staff to another branch", "previous employer", "staff loan", "payroll settings", "annual paye return",
    ],
    audiences: ["finance-officer", "approver"],
    routes: [R.FINANCE.PAYROLL, `${R.FINANCE.SETTINGS}/payroll`],
    access: { mode: "any", permissions: [P.FIN_VIEW_PAYROLL] },
    walkthroughId: "walkthrough.school.finance.run-payroll",
    primaryRoute: R.FINANCE.PAYROLL,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "payroll-settings", title: "Choose the payroll settings" },
      { id: "salary-structures", title: "Set up salary structures" },
      { id: "build-the-roster", title: "Build the roster" },
      { id: "earlier-pay", title: "Record earlier pay" },
      { id: "deductions", title: "Voluntary deductions" },
      { id: "generate-and-post", title: "Generate and post the run" },
      { id: "pay-net-wages", title: "Pay the staff" },
      { id: "payslips-and-returns", title: "Payslips and statutory returns" },
      { id: "correct-a-run", title: "Correct a run" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["school.finance.tax-remittance", "school.finance.reconcile-the-bank"],
    estimatedMinutes: 14,
    owner: OWNER,
    reviewedAt: "2026-10-05",
    risk: "high",
    status: "published",
    article: () => import("../content/finance-and-payments/run-payroll"),
  },
  {
    id: "school.finance.budgets",
    slug: "set-and-track-the-school-budget",
    title: "Set and track the school budget",
    summary: "Create a school-wide or branch budget, add its lines, approve it, and follow spending against it.",
    category: "finance-and-payments",
    tags: ["budget", "forecast", "variance", "overspend", "heatmap", "branch"],
    aliases: [
      "create budget", "approve budget", "budget variance", "over budget", "branch budget",
      "school-wide budget", "budget vs actual",
    ],
    audiences: ["finance-officer", "school-administrator", "approver"],
    routes: [R.FINANCE.BUDGETS, `${R.FINANCE.BUDGETS}/budgets`],
    access: { mode: "any", permissions: [P.FIN_VIEW_BUDGETS] },
    walkthroughId: "walkthrough.school.finance.budgets",
    primaryRoute: `${R.FINANCE.BUDGETS}/budgets`,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "create-the-budget", title: "Create the budget" },
      { id: "add-lines", title: "Add the lines" },
      { id: "approve", title: "Approve the budget" },
      { id: "track-spending", title: "Track spending against it" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["school.finance.financial-reports", "school.finance.chart-of-accounts"],
    estimatedMinutes: 6,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "medium",
    status: "published",
    article: () => import("../content/finance-and-payments/budgets"),
  },
  {
    id: "school.finance.fixed-assets",
    slug: "keep-the-fixed-asset-register",
    title: "Keep the fixed-asset register",
    summary: "Add an asset, capitalise it, post depreciation each month, and dispose of it when it is sold or scrapped.",
    category: "finance-and-payments",
    tags: ["fixed asset", "depreciation", "asset register", "bus", "generator", "disposal"],
    aliases: [
      "add asset", "school bus", "run depreciation", "dispose asset", "sell asset",
      "asset register", "net book value",
    ],
    audiences: ["finance-officer", "approver"],
    routes: [`${R.FINANCE.BUDGETS}/assets`],
    access: { mode: "any", permissions: [P.FIN_VIEW_FIXED_ASSETS] },
    walkthroughId: "walkthrough.school.finance.fixed-assets",
    primaryRoute: `${R.FINANCE.BUDGETS}/assets`,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "add-the-asset", title: "Add the asset" },
      { id: "acquire", title: "Capitalise it" },
      { id: "depreciate", title: "Post depreciation" },
      { id: "dispose", title: "Sell or scrap an asset" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["school.finance.close-a-period", "school.finance.financial-reports"],
    estimatedMinutes: 6,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "high",
    status: "published",
    article: () => import("../content/finance-and-payments/fixed-assets"),
  },
  {
    id: "school.finance.tax-remittance",
    slug: "file-and-pay-paye-pension-and-other-taxes",
    title: "File and pay PAYE, pension and other taxes",
    summary: "Set up each tax the school owes, prepare and file the return, pay each branch's share, and read the payroll schedules and annual PAYE return.",
    category: "finance-and-payments",
    tags: ["tax", "PAYE", "pension", "remittance", "filing", "WHT", "VAT", "NHF", "branch"],
    aliases: [
      "remit paye", "pay pension", "file tax return", "tax remittance", "tax obligation",
      "un-file return", "filing reference", "annual paye return", "branch share of tax", "reverse tax payment",
      "late items", "paye schedule", "pension schedule",
    ],
    audiences: ["finance-officer", "approver"],
    routes: [`${R.FINANCE.BUDGETS}/tax`],
    access: { mode: "any", permissions: [P.FIN_VIEW_TAX] },
    walkthroughId: "walkthrough.school.finance.tax-remittance",
    primaryRoute: `${R.FINANCE.BUDGETS}/tax`,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "create-the-obligation", title: "Set up an obligation" },
      { id: "prepare-and-file", title: "Prepare and file a return" },
      { id: "branch-shares", title: "Each branch's share" },
      { id: "pay", title: "Pay what is owed" },
      { id: "payroll-returns", title: "Payroll returns and the annual PAYE return" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["school.finance.run-payroll", "school.finance.reconcile-the-bank"],
    estimatedMinutes: 8,
    owner: OWNER,
    reviewedAt: "2026-10-05",
    risk: "high",
    status: "published",
    article: () => import("../content/finance-and-payments/tax-remittance"),
  },
  {
    id: "school.finance.journal-entries",
    slug: "find-post-or-reverse-a-journal-entry",
    title: "Find, post or reverse a journal entry",
    summary: "Search the general ledger, post a balanced manual journal, and reverse one posted in error.",
    category: "finance-and-payments",
    tags: ["journal", "general ledger", "ledger", "debit", "credit", "opening balance", "reversal"],
    aliases: [
      "manual journal", "journal entry", "new journal", "opening balances", "reverse journal",
      "journal will not balance", "general ledger",
    ],
    audiences: ["finance-officer", "approver"],
    routes: [R.FINANCE.LEDGER],
    access: { mode: "any", permissions: [P.FIN_VIEW_JOURNALS] },
    walkthroughId: "walkthrough.school.finance.journal-entries",
    primaryRoute: R.FINANCE.LEDGER,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "find-a-journal", title: "Find a journal" },
      { id: "post-a-journal", title: "Post a journal" },
      { id: "drafts-and-approval", title: "Drafts and approval" },
      { id: "reverse-a-journal", title: "Reverse a journal" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["school.finance.chart-of-accounts", "school.finance.close-a-period"],
    estimatedMinutes: 6,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "high",
    status: "published",
    article: () => import("../content/finance-and-payments/journal-entries"),
  },
  {
    id: "school.finance.close-a-period",
    slug: "close-a-month-or-the-fiscal-year",
    title: "Close a month or the fiscal year",
    summary: "Create the fiscal year, close each branch's months and year, force a close, re-open or archive a year, and check the sealed figures.",
    category: "finance-and-payments",
    tags: ["fiscal period", "month end", "close", "year end", "lock", "reopen", "fiscal year", "branch", "archive", "seal"],
    aliases: [
      "month end close", "close period", "reopen period", "lock period", "close fiscal year",
      "new fiscal year", "nothing can post", "posting date refused", "reopen year", "force close",
      "archive year", "show archived years", "branch close", "verify seals", "sealed figures",
      "record keeping", "retention",
    ],
    audiences: ["finance-officer", "school-administrator", "approver"],
    routes: [
      `${R.FINANCE.SETUP}/periods`,
      `${R.FINANCE.REPORTS}/periods`,
      `${R.FINANCE.REPORTS}/seals`,
      `${R.FINANCE.SETTINGS}/fiscal-calendar`,
    ],
    access: { mode: "any", permissions: [P.FIN_VIEW_PERIODS, P.FIN_VIEW_SEALS, P.FIN_VIEW_SETTINGS] },
    walkthroughId: "walkthrough.school.finance.close-a-period",
    primaryRoute: `${R.FINANCE.SETUP}/periods`,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "create-the-calendar", title: "Create the fiscal year" },
      { id: "branches", title: "Each branch closes its own books" },
      { id: "period-statuses", title: "What each status allows" },
      { id: "close-a-month", title: "Close a month" },
      { id: "force-close", title: "Close past a failed check" },
      { id: "close-the-year", title: "Close the fiscal year" },
      { id: "archive-a-year", title: "Archive an old year" },
      { id: "sealed-figures", title: "Check the sealed figures" },
      { id: "record-keeping", title: "How long records are kept" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: [
      "school.finance.reconcile-the-bank", "school.finance.financial-reports", "school.finance.journal-entries",
      "school.finance.deferred-income-deposits-and-doubtful-debts",
    ],
    estimatedMinutes: 12,
    owner: OWNER,
    reviewedAt: "2026-10-05",
    risk: "high",
    status: "published",
    article: () => import("../content/finance-and-payments/close-a-period"),
  },
  {
    id: "school.finance.chart-of-accounts",
    slug: "set-up-accounts-tax-codes-and-cost-centres",
    title: "Set up accounts, tax codes and cost centres",
    summary: "Read the chart of accounts, add the income and expense accounts the school needs, and set up tax codes and cost centres.",
    category: "finance-and-payments",
    tags: ["chart of accounts", "account", "tax code", "cost centre", "cost center", "finance setup"],
    aliases: [
      "new account", "add income account", "tuition account", "account code", "new tax code",
      "new cost centre", "department spending", "finance setup",
    ],
    audiences: ["finance-officer", "school-administrator"],
    routes: [
      R.FINANCE.SETUP,
      `${R.FINANCE.SETUP}/accounts`,
      `${R.FINANCE.SETUP}/tax-codes`,
      `${R.FINANCE.SETUP}/cost-centers`,
    ],
    access: { mode: "any", permissions: [P.FIN_VIEW_ACCOUNTS, P.FIN_VIEW_TAX_CODES, P.FIN_VIEW_COST_CENTERS] },
    walkthroughId: "walkthrough.school.finance.chart-of-accounts",
    primaryRoute: `${R.FINANCE.SETUP}/accounts`,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "read-the-chart", title: "Read the chart" },
      { id: "add-an-account", title: "Add an account" },
      { id: "tax-codes", title: "Tax codes" },
      { id: "cost-centres", title: "Cost centres" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["school.finance.finance-settings", "school.finance.bill-school-fees"],
    estimatedMinutes: 6,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "medium",
    status: "published",
    article: () => import("../content/finance-and-payments/chart-of-accounts"),
  },
  {
    id: "school.finance.finance-settings",
    slug: "review-finance-settings",
    title: "Review finance settings",
    summary: "Understand each Finance Settings section, and change posting accounts, billing defaults and banking defaults safely.",
    category: "finance-and-payments",
    tags: ["finance settings", "settings", "account mapping", "billing defaults", "due days", "collection account"],
    aliases: [
      "finance configuration", "default due days", "collection account", "account mapping",
      "receipt allocation default", "petty cash threshold", "collection target", "approval settings",
    ],
    audiences: ["finance-officer", "school-administrator"],
    routes: [
      R.FINANCE.SETTINGS,
      `${R.FINANCE.SETTINGS}/overview`,
      `${R.FINANCE.SETTINGS}/fiscal-calendar`,
      `${R.FINANCE.SETTINGS}/accounting`,
      `${R.FINANCE.SETTINGS}/documents`,
      `${R.FINANCE.SETTINGS}/banking-cash`,
      `${R.FINANCE.SETTINGS}/reference-data`,
      `${R.FINANCE.SETTINGS}/approvals`,
      `${R.FINANCE.SETTINGS}/receivables`,
    ],
    access: { mode: "any", permissions: [P.FIN_VIEW_SETTINGS] },
    primaryRoute: `${R.FINANCE.SETTINGS}/overview`,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "sections", title: "What each section holds" },
      { id: "accounting-defaults", title: "Accounting defaults" },
      { id: "documents", title: "Documents" },
      { id: "banking-and-cash", title: "Banking and cash" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["school.finance.fee-due-dates", "school.finance.chart-of-accounts"],
    estimatedMinutes: 7,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "high",
    status: "published",
    article: () => import("../content/finance-and-payments/finance-settings"),
  },
  {
    id: "school.finance.fee-due-dates",
    slug: "choose-when-fee-bills-fall-due",
    title: "Choose when fee bills fall due",
    summary: "Pick the school's rule for fee due dates, and see the date each rule gives before you save.",
    category: "finance-and-payments",
    tags: ["fee due date", "due date", "school fees", "term", "session", "finance settings"],
    aliases: [
      "when are fees due", "fee deadline", "end of term", "due date rule", "payment deadline",
      "days after the bill",
    ],
    audiences: ["finance-officer", "school-administrator"],
    routes: [`${R.FINANCE.SETTINGS}/fees`],
    access: { mode: "all", permissions: [P.FIN_VIEW_SETTINGS, P.VIEW_FEES] },
    primaryRoute: `${R.FINANCE.SETTINGS}/fees`,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "choose-the-rule", title: "Choose the rule" },
      { id: "how-dates-work", title: "How the dates are worked out" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["school.finance.bill-school-fees", "school.finance.finance-settings"],
    estimatedMinutes: 3,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "medium",
    status: "published",
    article: () => import("../content/finance-and-payments/fee-due-dates"),
  },
  {
    id: "school.finance.financial-reports",
    slug: "run-the-financial-reports",
    title: "Run the financial reports",
    summary: "Choose the right statement, check that it balances, compare periods, and export it for the board.",
    category: "finance-and-payments",
    tags: ["report", "trial balance", "income statement", "balance sheet", "cash flow", "equity", "cost centre", "export"],
    aliases: [
      "profit and loss", "p and l", "surplus", "deficit", "trial balance out of balance",
      "board report", "spending by department", "export report",
    ],
    audiences: ["finance-officer", "school-administrator", "approver"],
    routes: [
      R.FINANCE.REPORTS,
      `${R.FINANCE.REPORTS}/trial-balance`,
      `${R.FINANCE.REPORTS}/income-statement`,
      `${R.FINANCE.REPORTS}/balance-sheet`,
      `${R.FINANCE.REPORTS}/cash-flow`,
      `${R.FINANCE.REPORTS}/changes-in-equity`,
      `${R.FINANCE.REPORTS}/analytics`,
    ],
    access: { mode: "any", permissions: [P.FIN_VIEW_REPORTS] },
    primaryRoute: `${R.FINANCE.REPORTS}/trial-balance`,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "choose-the-report", title: "Choose the report" },
      { id: "check-the-signals", title: "Check the built-in checks" },
      { id: "export", title: "Export and share" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["school.finance.close-a-period", "school.finance.finance-dashboard"],
    estimatedMinutes: 6,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "low",
    status: "published",
    article: () => import("../content/finance-and-payments/financial-reports"),
  },
  {
    id: "school.finance.finance-dashboard",
    slug: "read-the-finance-dashboard",
    title: "Read the finance dashboard",
    summary: "See fees billed and collected, who is overdue, cash in the bank, and what needs your attention.",
    category: "finance-and-payments",
    tags: ["finance dashboard", "overview", "collection rate", "owing", "cash", "branch"],
    aliases: [
      "finance overview", "collection curve", "how much has been paid", "fees collected",
      "most overdue", "debtors", "needs attention",
    ],
    audiences: ["finance-officer", "school-administrator"],
    routes: [R.FINANCE.INDEX],
    access: { mode: "any", permissions: [
      P.FIN_VIEW_REPORTS, P.FIN_VIEW_INVOICES, P.FIN_VIEW_PAYMENTS, P.FIN_VIEW_BANK_ACCOUNTS,
      P.FIN_VIEW_BUDGETS, P.FIN_VIEW_EXPENSE_CLAIMS, P.FIN_VIEW_PETTY_CASH, P.FIN_VIEW_PAYROLL,
      P.FIN_VIEW_TAX, P.FIN_VIEW_FIXED_ASSETS,
    ] },
    primaryRoute: R.FINANCE.INDEX,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "set-the-view", title: "Set the view" },
      { id: "read-the-overview", title: "Read the overview" },
      { id: "collections", title: "Follow fee collection" },
      { id: "quick-actions", title: "Start work from the dashboard" },
      { id: "common-problems", title: "Common problems" },
    ],
    relatedGuideIds: ["school.finance.financial-reports", "school.finance.fee-reminders", "school.finance.close-a-period"],
    estimatedMinutes: 4,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "low",
    status: "published",
    article: () => import("../content/finance-and-payments/finance-dashboard"),
  },
  {
    id: "school.finance.audit-trail",
    slug: "check-who-changed-what-in-finance",
    title: "Check who changed what in Finance",
    summary: "Filter the finance audit trail and read exactly what an action changed.",
    category: "finance-and-payments",
    tags: ["audit trail", "audit", "history", "who changed", "finance"],
    aliases: [
      "who voided", "who posted", "finance history", "audit log", "field changes", "before and after",
    ],
    audiences: ["finance-officer", "school-administrator"],
    routes: [R.FINANCE.AUDIT],
    access: { mode: "any", permissions: [P.FIN_VIEW_AUDIT] },
    primaryRoute: R.FINANCE.AUDIT,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "find-an-entry", title: "Find an entry" },
      { id: "use-it-well", title: "Use it well" },
    ],
    relatedGuideIds: ["school.finance.journal-entries"],
    estimatedMinutes: 3,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "low",
    status: "published",
    article: () => import("../content/finance-and-payments/finance-audit-trail"),
  },
] as const satisfies readonly GuideRecord[];
