import type { GuideRecord } from "../types";
import { A, OWNER, R } from "./shared";

export const GETTING_STARTED_GUIDES = [
  {
    id: "school.getting-started.basics",
    slug: "get-started-with-xvs",
    title: "Get started with XVS",
    summary: "Find your way around the school: the sidebar, workspace search, branch and session, notifications, and help.",
    category: "getting-started",
    tags: ["dashboard", "navigation", "search", "sidebar", "branch", "session", "academic year", "help"],
    aliases: ["how xvs works", "new user", "tour", "where do i start", "switch branch", "change year", "change session", "read only year", "logout", "sign out"],
    audiences: ["all-users"],
    routes: [R.OVERVIEW.INDEX, R.NOTIFICATIONS],
    actionIds: ["view-dashboard", "view-notifications", "get-help", "view-guides"],
    access: { mode: "authenticated", permissions: [] },
    walkthroughId: "walkthrough.school.getting-started.basics",
    primaryRoute: R.OVERVIEW.INDEX,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "find-your-way-around", title: "Find your way around" },
      { id: "search-and-quick-actions", title: "Search and quick actions" },
      { id: "branch-and-year", title: "Choose your branch and session" },
      { id: "notifications", title: "Notifications" },
      { id: "get-help", title: "Get help" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: [
      "school.getting-started.activate-and-sign-in",
      "school.getting-started.raise-support-ticket",
      "school.getting-started.how-to-guides",
      "school.troubleshooting.permission-denied",
    ],
    estimatedMinutes: 4,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "low",
    featured: true,
    status: "published",
    article: () => import("../content/getting-started/school-basics"),
  },
  {
    id: "school.getting-started.activate-and-sign-in",
    slug: "activate-your-account-and-sign-in",
    title: "Activate your account and sign in",
    summary: "Use your invitation to set your first password, then sign in at your school's address with your email or staff ID.",
    category: "getting-started",
    tags: ["activation", "invitation", "login", "sign in", "password", "staff id", "account access"],
    aliases: ["activate account", "accept invite", "first login", "log in", "invite expired", "link expired", "invalid credentials", "account locked", "account not activated", "email or staff id", "this address does not belong to a school"],
    audiences: ["all-users"],
    routes: [A.ACTIVATE, A.LOGIN],
    access: { mode: "authenticated", permissions: [] },
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "activate-your-account", title: "Activate your account" },
      { id: "sign-in", title: "Sign in" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: [
      "school.getting-started.reset-password",
      "school.getting-started.basics",
      "school.troubleshooting.session-expired",
    ],
    estimatedMinutes: 4,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "medium",
    status: "published",
    article: () => import("../content/getting-started/activate-and-sign-in"),
  },
  {
    id: "school.getting-started.reset-password",
    slug: "reset-a-forgotten-password",
    title: "Reset a forgotten password",
    summary: "Ask for a reset link with your email or staff ID, and set a new password from the email.",
    category: "getting-started",
    tags: ["password", "reset", "forgot password", "account access", "staff id"],
    aliases: ["forgot password", "change password", "cannot log in", "reset link", "reset link expired", "send reset link", "new password"],
    audiences: ["all-users"],
    routes: [A.FORGOT_PASSWORD, A.RESET_PASSWORD, A.LOGIN],
    access: { mode: "authenticated", permissions: [] },
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "request-a-reset-link", title: "Request a reset link" },
      { id: "set-a-new-password", title: "Set a new password" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: [
      "school.getting-started.activate-and-sign-in",
      "school.troubleshooting.session-expired",
    ],
    estimatedMinutes: 3,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "medium",
    status: "published",
    article: () => import("../content/getting-started/reset-password"),
  },
  {
    id: "school.getting-started.raise-support-ticket",
    slug: "raise-and-follow-a-support-ticket",
    title: "Raise and follow a support ticket",
    summary: "Report a problem from the screen it happened on, follow the replies, and send a ticket on to XVS when the school cannot solve it.",
    category: "getting-started",
    tags: ["support", "ticket", "help", "headset", "reply", "escalate", "xvs support"],
    aliases: ["raise an issue", "report a problem", "contact support", "helpdesk", "my tickets", "send to xvs", "escalate ticket", "reopen ticket", "mark resolved", "close ticket", "mute ticket"],
    audiences: ["all-users"],
    routes: [R.SUPPORT.INDEX, R.SUPPORT.DETAIL],
    actionIds: ["get-help", "view-support"],
    access: { mode: "authenticated", permissions: [] },
    walkthroughId: "walkthrough.school.getting-started.raise-support-ticket",
    primaryRoute: R.SUPPORT.INDEX,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "raise-a-ticket", title: "Raise a ticket" },
      { id: "follow-a-ticket", title: "Follow a ticket" },
      { id: "send-to-xvs", title: "Work a ticket and send it to XVS" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: [
      "school.getting-started.how-to-guides",
      "school.getting-started.notifications",
      "school.getting-started.basics",
    ],
    estimatedMinutes: 5,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "low",
    status: "published",
    article: () => import("../content/getting-started/raise-support-ticket"),
  },
  {
    id: "school.getting-started.how-to-guides",
    slug: "find-answers-in-the-how-to-guides",
    title: "Find answers in the how-to guides",
    summary: "Search the guides by task or error, filter by role and area, and report a guide that no longer matches the screen.",
    category: "getting-started",
    tags: ["guides", "help", "how-to", "search", "documentation"],
    aliases: ["help articles", "user guide", "manual", "instructions", "how do i", "tutorial", "outdated guide", "guide not found"],
    audiences: ["all-users"],
    routes: [R.SUPPORT.GUIDES, R.SUPPORT.GUIDE_DETAIL],
    actionIds: ["view-guides"],
    access: { mode: "authenticated", permissions: [] },
    primaryRoute: R.SUPPORT.GUIDES,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "open-the-guides", title: "Open the guides" },
      { id: "find-a-guide", title: "Find a guide" },
      { id: "read-a-guide", title: "Read a guide" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: [
      "school.getting-started.raise-support-ticket",
      "school.getting-started.basics",
    ],
    estimatedMinutes: 3,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "low",
    status: "published",
    article: () => import("../content/getting-started/how-to-guides"),
  },
  {
    id: "school.getting-started.notifications",
    slug: "read-and-clear-notifications",
    title: "Read and clear notifications",
    summary: "Use the bell to open what needs you, and the Notification Centre to find, search and clear older notifications.",
    category: "getting-started",
    tags: ["notifications", "bell", "alerts", "unread", "inbox"],
    aliases: ["notification centre", "notification center", "mark all as read", "clear notifications", "unread notifications", "view all notifications"],
    audiences: ["all-users"],
    routes: [R.NOTIFICATIONS],
    actionIds: ["view-notifications"],
    access: { mode: "authenticated", permissions: [] },
    primaryRoute: R.NOTIFICATIONS,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "use-the-bell", title: "Use the bell" },
      { id: "notification-centre", title: "Use the Notification Centre" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: [
      "school.getting-started.basics",
      "school.getting-started.raise-support-ticket",
    ],
    estimatedMinutes: 2,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "low",
    status: "published",
    article: () => import("../content/getting-started/notifications"),
  },
] as const satisfies readonly GuideRecord[];
