import { P } from "@/permissions";

import type { GuideRecord } from "../types";
import { OWNER, R } from "./shared";

export const PROCUREMENT_AND_INVENTORY_GUIDES = [
  {
    id: "school.procurement.raise-requisition",
    slug: "raise-a-purchase-requisition",
    title: "Raise a purchase requisition",
    summary: "Ask the school to buy something: add the items and reason, check the budget, send it for approval, and correct it if it comes back.",
    category: "procurement-and-inventory",
    tags: ["requisition", "purchase request", "buy", "budget", "cost centre", "approval", "procurement"],
    aliases: ["request to buy", "order supplies", "buy something", "purchase request", "requisition approval", "request revision", "department request"],
    audiences: ["all-users", "procurement-officer", "approver"],
    routes: [R.PROCUREMENT.REQUISITIONS, R.PROCUREMENT.APPROVALS],
    access: { mode: "any", permissions: [P.PROC_VIEW_REQUISITIONS, P.PROC_CREATE_REQUISITION, P.PROC_VIEW_APPROVALS] },
    primaryRoute: R.PROCUREMENT.REQUISITIONS,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "create-the-requisition", title: "Create the requisition" },
      { id: "submit-for-approval", title: "Submit for approval" },
      { id: "approve-in-procurement", title: "Approve a requisition" },
      { id: "follow-and-correct", title: "Follow it and correct it" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["school.procurement.order-receive-and-pay", "school.workflow.decide-approval", "school.workflow.track-and-delegate"],
    estimatedMinutes: 6,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "medium",
    featured: true,
    status: "published",
    article: () => import("../content/procurement-and-inventory/raise-a-requisition"),
  },
  {
    id: "school.procurement.order-receive-and-pay",
    slug: "order-receive-and-pay-a-supplier",
    title: "Order, receive and pay a supplier",
    summary: "Turn an approved requisition into a purchase order, record the delivery, post and pay the supplier's bill, correct it with a void or credit note, return goods, and bring in old bills.",
    category: "procurement-and-inventory",
    tags: [
      "purchase order", "goods receipt", "delivery", "vendor invoice", "supplier bill", "vendor payment", "three-way match",
      "procure to pay", "credit note", "goods return", "opening balance",
    ],
    aliases: [
      "raise po", "order from supplier", "receive goods", "record delivery", "supplier invoice", "pay supplier", "match invoice", "p2p",
      "supplier credit note", "vendor credit note", "void a bill", "return goods", "send goods back", "opening supplier bills",
    ],
    audiences: ["procurement-officer", "finance-officer", "approver"],
    routes: [R.PROCUREMENT.PURCHASE_ORDERS, R.PROCUREMENT.GOODS_RECEIPTS, R.PROCUREMENT.VENDOR_INVOICES, R.PROCUREMENT.VENDOR_PAYMENTS],
    access: { mode: "any", permissions: [
      P.PROC_VIEW_PURCHASE_ORDERS, P.PROC_VIEW_GOODS_RECEIPTS,
      P.PROC_VIEW_VENDOR_INVOICES, P.PROC_VIEW_VENDOR_CREDIT_NOTES, P.PROC_VIEW_VENDOR_PAYMENTS,
    ] },
    walkthroughId: "walkthrough.school.procurement.order-receive-and-pay",
    primaryRoute: R.PROCUREMENT.PURCHASE_ORDERS,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "raise-the-purchase-order", title: "Raise the purchase order" },
      { id: "record-the-delivery", title: "Record the delivery" },
      { id: "record-the-invoice", title: "Record and post the supplier's bill" },
      { id: "pay-the-supplier", title: "Pay the supplier" },
      { id: "correct-a-bill", title: "Correct a posted bill" },
      { id: "return-goods", title: "Send goods back to the supplier" },
      { id: "opening-bills", title: "Bring in bills owed from before" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["school.procurement.raise-requisition", "school.procurement.manage-suppliers", "school.workflow.decide-approval"],
    estimatedMinutes: 16,
    owner: OWNER,
    reviewedAt: "2026-10-05",
    risk: "high",
    status: "published",
    article: () => import("../content/procurement-and-inventory/order-receive-and-pay"),
  },
  {
    id: "school.procurement.manage-suppliers",
    slug: "add-and-manage-suppliers",
    title: "Add and manage suppliers",
    summary: "Set up a supplier with contacts and bank details, clear its checks, put it on hold, and review what the school has bought from it.",
    category: "procurement-and-inventory",
    tags: ["vendor", "supplier", "KYC", "bank details", "on hold", "contacts", "payment terms"],
    aliases: ["add supplier", "new vendor", "supplier bank account", "block supplier", "verify supplier", "supplier on hold"],
    audiences: ["procurement-officer", "finance-officer"],
    routes: [R.PROCUREMENT.VENDORS, `${R.PROCUREMENT.VENDORS}/vendors`],
    access: { mode: "any", permissions: [P.PROC_VIEW_VENDORS, P.PROC_CREATE_VENDOR] },
    walkthroughId: "walkthrough.school.procurement.manage-suppliers",
    primaryRoute: `${R.PROCUREMENT.VENDORS}/vendors`,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "add-a-supplier", title: "Add a supplier" },
      { id: "approve-and-hold", title: "Clear checks, or put a supplier on hold" },
      { id: "review-a-supplier", title: "Review a supplier" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["school.procurement.categories-and-catalogue", "school.procurement.order-receive-and-pay"],
    estimatedMinutes: 7,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "high",
    status: "published",
    article: () => import("../content/procurement-and-inventory/manage-suppliers"),
  },
  {
    id: "school.procurement.categories-and-catalogue",
    slug: "set-up-purchase-categories-and-catalogue",
    title: "Set up purchase categories and the catalogue",
    summary: "Group spending into categories and keep a catalogue of the items the school buys often, with their usual unit and price.",
    category: "procurement-and-inventory",
    tags: ["category", "catalogue", "catalog", "item", "unit of measure", "standard price", "preferred vendor"],
    aliases: ["add catalogue item", "item list", "spend categories", "new category", "usual price"],
    audiences: ["procurement-officer", "finance-officer"],
    routes: [`${R.PROCUREMENT.VENDORS}/categories`, `${R.PROCUREMENT.VENDORS}/catalog`],
    access: { mode: "any", permissions: [P.PROC_VIEW_CATEGORIES, P.PROC_VIEW_CATALOG] },
    primaryRoute: `${R.PROCUREMENT.VENDORS}/catalog`,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "build-categories", title: "Build the categories" },
      { id: "add-catalogue-items", title: "Add catalogue items" },
      { id: "retire-old-entries", title: "Retire what you no longer use" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["school.procurement.manage-suppliers", "school.procurement.raise-requisition"],
    estimatedMinutes: 6,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "low",
    status: "published",
    article: () => import("../content/procurement-and-inventory/categories-and-catalogue"),
  },
  {
    id: "school.procurement.quotes-from-suppliers",
    slug: "get-quotes-from-suppliers-and-award",
    title: "Get quotes from suppliers and award",
    summary: "Send a request for quotation to several suppliers, record their quotes, compare them, award the winner as a purchase order, and buy together across branches.",
    category: "procurement-and-inventory",
    tags: ["RFQ", "request for quotation", "quotation", "quote", "tender", "compare", "award", "sourcing", "branch"],
    aliases: [
      "get quotes", "three quotes", "invite suppliers", "compare prices", "choose supplier", "tender", "bid",
      "buy together", "shared rfq", "branches buying together", "combine requisitions",
    ],
    audiences: ["procurement-officer", "approver"],
    routes: [R.PROCUREMENT.SOURCING, `${R.PROCUREMENT.SOURCING}/rfqs`, `${R.PROCUREMENT.SOURCING}/quotations`],
    access: { mode: "any", permissions: [P.PROC_VIEW_RFQS, P.PROC_VIEW_QUOTATIONS] },
    walkthroughId: "walkthrough.school.procurement.quotes-from-suppliers",
    primaryRoute: `${R.PROCUREMENT.SOURCING}/rfqs`,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "prepare-the-rfq", title: "Prepare the RFQ" },
      { id: "manage-an-open-rfq", title: "Manage an open RFQ" },
      { id: "record-quotations", title: "Record the quotations" },
      { id: "compare-and-award", title: "Compare and award" },
      { id: "buy-together", title: "Buy together across branches" },
      { id: "close-or-cancel", title: "Close or cancel without an award" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["school.procurement.manage-suppliers", "school.procurement.order-receive-and-pay", "school.procurement.settings"],
    estimatedMinutes: 12,
    owner: OWNER,
    reviewedAt: "2026-10-05",
    risk: "high",
    status: "published",
    article: () => import("../content/procurement-and-inventory/quotes-from-suppliers"),
  },
  {
    id: "school.procurement.supplier-contracts",
    slug: "record-and-renew-supplier-contracts",
    title: "Record and renew supplier contracts",
    summary: "Register a standing agreement with a supplier, track its milestones and orders, then renew or end it.",
    category: "procurement-and-inventory",
    tags: ["contract", "agreement", "milestone", "renewal", "terminate", "service contract"],
    aliases: ["supplier agreement", "service agreement", "renew contract", "contract expiring", "end contract", "maintenance contract"],
    audiences: ["procurement-officer", "approver"],
    routes: [R.PROCUREMENT.CONTRACTS],
    access: { mode: "any", permissions: [P.PROC_VIEW_CONTRACTS] },
    walkthroughId: "walkthrough.school.procurement.supplier-contracts",
    primaryRoute: R.PROCUREMENT.CONTRACTS,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "create-the-contract", title: "Create the contract" },
      { id: "follow-the-contract", title: "Follow the contract" },
      { id: "renew-or-end", title: "Renew or end the contract" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["school.procurement.manage-suppliers", "school.procurement.order-receive-and-pay"],
    estimatedMinutes: 7,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "medium",
    status: "published",
    article: () => import("../content/procurement-and-inventory/supplier-contracts"),
  },
  {
    id: "school.procurement.manage-stock",
    slug: "manage-stock-and-stores",
    title: "Manage stock and stores",
    summary: "Set up stock items and stores, issue stock to departments, move it between stores and branches, correct a count, and see what needs reordering.",
    category: "procurement-and-inventory",
    tags: ["inventory", "stock", "store", "issue", "adjustment", "reorder", "stock count", "movements", "transfer"],
    aliases: [
      "stores", "storekeeper", "issue stock", "stock count", "low stock", "reorder", "kitchen store", "exercise books", "stock take",
      "transfer stock", "move stock between stores", "send stock to another branch",
    ],
    audiences: ["procurement-officer"],
    routes: [R.PROCUREMENT.INVENTORY, `${R.PROCUREMENT.INVENTORY}/items`, `${R.PROCUREMENT.INVENTORY}/movements`, `${R.PROCUREMENT.INVENTORY}/locations`],
    access: { mode: "any", permissions: [P.PROC_VIEW_STOCK] },
    walkthroughId: "walkthrough.school.procurement.manage-stock",
    primaryRoute: `${R.PROCUREMENT.INVENTORY}/items`,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "set-up-items-and-stores", title: "Set up stock items and stores" },
      { id: "issue-stock", title: "Issue stock to a department" },
      { id: "transfer-stock", title: "Move stock to another store" },
      { id: "adjust-a-count", title: "Correct a count" },
      { id: "review-stock", title: "Review stock and reorder" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: [
      "school.procurement.order-receive-and-pay", "school.procurement.categories-and-catalogue",
      "school.procurement.overview-and-reports", "school.finance.branches-working-together",
    ],
    estimatedMinutes: 10,
    owner: OWNER,
    reviewedAt: "2026-10-05",
    risk: "medium",
    status: "published",
    article: () => import("../content/procurement-and-inventory/manage-stock"),
  },
  {
    id: "school.procurement.overview-and-reports",
    slug: "read-the-procurement-overview-and-reports",
    title: "Read the procurement overview and reports",
    summary: "See what is waiting, owed and running low, and use the payables, matching, spend and supplier reports.",
    category: "procurement-and-inventory",
    tags: ["dashboard", "overview", "analytics", "AP aging", "GR/IR", "spend", "vendor performance", "assessment"],
    aliases: ["procurement dashboard", "what do we owe", "overdue bills", "spend report", "supplier scorecard", "rate supplier", "purchase report"],
    audiences: ["procurement-officer", "finance-officer", "approver"],
    routes: [
      R.PROCUREMENT.INDEX,
      R.PROCUREMENT.ANALYTICS,
      `${R.PROCUREMENT.ANALYTICS}/ap-aging`,
      `${R.PROCUREMENT.ANALYTICS}/grir`,
      `${R.PROCUREMENT.ANALYTICS}/spend`,
      `${R.PROCUREMENT.ANALYTICS}/performance`,
    ],
    access: { mode: "any", permissions: [
      P.PROC_VIEW_ANALYTICS, P.PROC_VIEW_REQUISITIONS, P.PROC_VIEW_PURCHASE_ORDERS,
      P.PROC_VIEW_VENDOR_INVOICES, P.PROC_VIEW_STOCK,
    ] },
    primaryRoute: R.PROCUREMENT.INDEX,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "read-the-overview", title: "Read the overview" },
      { id: "other-views", title: "Spend and stock views" },
      { id: "use-the-reports", title: "Use the Analytics reports" },
      { id: "assess-a-supplier", title: "Assess a supplier" },
      { id: "act-on-what-you-find", title: "Act on what you find" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["school.procurement.order-receive-and-pay", "school.procurement.manage-stock", "school.procurement.manage-suppliers"],
    estimatedMinutes: 7,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "low",
    status: "published",
    article: () => import("../content/procurement-and-inventory/procurement-overview-and-reports"),
  },
  {
    id: "school.procurement.settings",
    slug: "set-the-schools-purchasing-rules",
    title: "Set the school's purchasing rules",
    summary: "Change the defaults and controls behind purchasing: supplier checks, minimum quotes, invoice matching and more.",
    category: "procurement-and-inventory",
    tags: ["settings", "policy", "matching tolerance", "minimum quotes", "KYC", "non-PO invoice", "defaults"],
    aliases: ["procurement settings", "purchasing policy", "how many quotes", "match tolerance", "allow bills without po", "procurement rules"],
    audiences: ["school-administrator", "finance-officer", "procurement-officer"],
    routes: [
      R.PROCUREMENT.SETTINGS,
      `${R.PROCUREMENT.SETTINGS}/overview`,
      `${R.PROCUREMENT.SETTINGS}/general`,
      `${R.PROCUREMENT.SETTINGS}/purchasing`,
      `${R.PROCUREMENT.SETTINGS}/sourcing-lifecycle`,
      `${R.PROCUREMENT.SETTINGS}/competitive-governance`,
      `${R.PROCUREMENT.SETTINGS}/matching`,
      `${R.PROCUREMENT.SETTINGS}/accounting`,
      `${R.PROCUREMENT.SETTINGS}/approvals`,
      `${R.PROCUREMENT.SETTINGS}/reference-data`,
    ],
    access: { mode: "any", permissions: [P.PROC_VIEW_SETTINGS] },
    walkthroughId: "walkthrough.school.procurement.settings",
    primaryRoute: R.PROCUREMENT.SETTINGS,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "find-your-way", title: "Find the right section" },
      { id: "change-a-rule", title: "Change a rule" },
      { id: "rules-you-cannot-switch-off", title: "Rules you cannot switch off" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["school.procurement.quotes-from-suppliers", "school.procurement.order-receive-and-pay", "school.workflow.adjust-approval-path"],
    estimatedMinutes: 8,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "high",
    status: "published",
    article: () => import("../content/procurement-and-inventory/procurement-settings"),
  },
] as const satisfies readonly GuideRecord[];
