import { P } from "@/permissions";

import type { GuideRecord } from "../types";
import { OWNER, R } from "./shared";

export const ROLES_AND_PERMISSIONS_GUIDES = [
  {
    id: "school.roles.create-and-edit-role",
    slug: "create-and-edit-a-role",
    title: "Create and edit a role",
    summary: "Read the role directory, create a role with the right branch reach and permissions, edit it, give it to people, and take it out of use.",
    category: "roles-and-permissions",
    tags: ["roles", "permissions", "custom role", "branch reach", "school-wide", "assign role", "role directory"],
    aliases: ["new role", "add role", "edit role", "give someone a role", "assign a role", "who can do what", "delete role", "take out of use", "rbac"],
    audiences: ["school-administrator"],
    routes: [R.ROLES.INDEX, R.ROLES.NEW, R.ROLES.DETAIL, R.ROLES.EDIT],
    actionIds: ["view-school-roles", "create-school-role"],
    access: { mode: "any", permissions: [P.VIEW_ROLES, P.CREATE_ROLE, P.MODIFY_ROLE] },
    primaryRoute: R.ROLES.INDEX,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "read-the-directory", title: "Read the role directory" },
      { id: "open-a-role", title: "Open a role" },
      { id: "create-a-role", title: "Create a role" },
      { id: "edit-a-role", title: "Edit a role" },
      { id: "give-the-role-to-people", title: "Give the role to people" },
      { id: "take-a-role-out-of-use", title: "Take a role out of use or delete it" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: [
      "school.roles.role-change-approval",
      "school.roles.field-access",
      "school.setup.confirm-roles-and-invite-staff",
    ],
    estimatedMinutes: 10,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "high",
    featured: true,
    status: "published",
    article: () => import("../content/roles-and-permissions/create-and-edit-role"),
  },
  {
    id: "school.roles.role-change-approval",
    slug: "get-a-role-change-approved",
    title: "Get a role change approved",
    summary: "Know which role changes wait for approval, what the role shows while they wait, and where the request is decided.",
    category: "roles-and-permissions",
    tags: ["approval", "restricted permission", "role change", "waiting for approval", "approvals", "role grant"],
    aliases: ["approval required", "why is my permission not working", "permission pending", "role waiting for approval", "approve role change", "restricted", "grant pending"],
    audiences: ["school-administrator", "approver"],
    routes: [R.ROLES.INDEX, R.ROLES.DETAIL, R.ROLES.EDIT],
    actionIds: ["view-school-roles"],
    access: { mode: "any", permissions: [P.VIEW_ROLES, P.CREATE_ROLE, P.MODIFY_ROLE, P.ASSIGN_ROLE] },
    primaryRoute: R.ROLES.INDEX,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "what-needs-approval", title: "What needs approval" },
      { id: "when-you-save-a-role", title: "When you save a role" },
      { id: "when-you-give-a-role", title: "When you give a role to someone" },
      { id: "follow-the-request", title: "Follow the request" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["school.roles.create-and-edit-role"],
    estimatedMinutes: 5,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "high",
    status: "published",
    article: () => import("../content/roles-and-permissions/role-change-approval"),
  },
  {
    id: "school.roles.field-access",
    slug: "restrict-fields-with-field-access",
    title: "Restrict fields with Field Access",
    summary: "Choose, field by field, what each role may read and change, and put a field back to its default.",
    category: "roles-and-permissions",
    tags: ["field access", "fields", "read", "write", "sensitive", "privacy", "role"],
    aliases: ["hide a field", "field permissions", "read write fields", "who can see phone number", "make a field read only", "reset to default", "sensitive fields"],
    audiences: ["school-administrator"],
    routes: [R.ROLES.FIELD_ACCESS],
    actionIds: ["view-field-access"],
    access: { mode: "all", permissions: [P.VIEW_ROLES, P.VIEW_FIELD_ACCESS] },
    primaryRoute: R.ROLES.FIELD_ACCESS,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "how-read-and-write-work", title: "How Read and Write work" },
      { id: "find-the-fields", title: "Find the fields" },
      { id: "change-and-save", title: "Change and save" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["school.roles.create-and-edit-role"],
    estimatedMinutes: 5,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "high",
    status: "published",
    article: () => import("../content/roles-and-permissions/field-access"),
  },
] as const satisfies readonly GuideRecord[];
