import { P } from "@/permissions";

import type { GuideRecord } from "../types";
import { OWNER, R } from "./shared";

export const SCHOOL_SETUP_GUIDES = [
  {
    id: "school.setup.onboarding-checklist",
    slug: "set-up-your-school-with-the-onboarding-checklist",
    title: "Set up your school with the onboarding checklist",
    summary: "Work through the Onboarding Control Room: read your go-live status, open each step, mark it done or skip it, and know what is closed until go-live.",
    category: "school-setup",
    tags: ["onboarding", "control room", "checklist", "setup", "steps", "blockers", "readiness"],
    aliases: ["how do i set up my school", "onboarding checklist", "control room", "mark as done", "skip a step", "reopen a step", "why is everything locked", "not available yet", "onboarding window"],
    audiences: ["school-administrator", "branch-administrator"],
    routes: [R.ONBOARDING.INDEX, R.ONBOARDING.WELCOME, R.ONBOARDING.NOT_LIVE],
    actionIds: ["view-control-room"],
    access: { mode: "any", permissions: [P.VIEW_ONBOARDING] },
    walkthroughId: "walkthrough.school.setup.onboarding-checklist",
    primaryRoute: R.ONBOARDING.INDEX,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "welcome-screen", title: "The welcome screen" },
      { id: "read-your-status", title: "Read your go-live status" },
      { id: "work-through-the-steps", title: "Work through the steps" },
      { id: "before-go-live", title: "What is open before go-live" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: [
      "school.setup.school-profile",
      "school.setup.confirm-roles-and-invite-staff",
      "school.setup.import-initial-data",
      "school.setup.request-go-live",
    ],
    estimatedMinutes: 6,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "medium",
    featured: true,
    status: "published",
    article: () => import("../content/school-setup/onboarding-checklist"),
  },
  {
    id: "school.setup.school-profile",
    slug: "complete-your-school-profile",
    title: "Complete your school profile",
    summary: "Confirm ownership type, term structure and currency, add your logo, and know which details only XVS can change.",
    category: "school-setup",
    tags: ["school profile", "ownership", "term structure", "currency", "logo", "motto", "registration number"],
    aliases: ["school details", "change currency", "upload logo", "change school name", "sign-in address", "school code", "still to fill in"],
    audiences: ["school-administrator", "branch-administrator"],
    routes: [R.ONBOARDING.PROFILE],
    actionIds: ["view-school-profile"],
    access: { mode: "any", permissions: [P.VIEW_SCHOOL_PROFILE] },
    primaryRoute: R.ONBOARDING.PROFILE,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "what-xvs-sets", title: "What XVS sets" },
      { id: "fill-in-your-details", title: "Fill in your details" },
      { id: "add-your-logo", title: "Add your logo" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["school.setup.onboarding-checklist"],
    estimatedMinutes: 4,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "medium",
    status: "published",
    article: () => import("../content/school-setup/school-profile"),
  },
  {
    id: "school.setup.confirm-roles-and-invite-staff",
    slug: "confirm-roles-and-invite-staff-during-setup",
    title: "Confirm roles and invite staff during setup",
    summary: "Review the roles XVS set up for your school, add your own, confirm the step, and invite the administrators who will run the system.",
    category: "school-setup",
    tags: ["roles", "invitations", "invite", "administrators", "onboarding", "default roles", "custom role"],
    aliases: ["invite staff", "invite admin", "resend invitation", "confirm roles", "default role templates", "add custom role", "save and continue"],
    audiences: ["school-administrator", "branch-administrator"],
    routes: [R.ONBOARDING.ROLES, R.ONBOARDING.ROLE_NEW, R.ONBOARDING.ROLE_DETAIL, R.ONBOARDING.ROLE_EDIT],
    actionIds: ["view-roles", "create-onboarding-role", "view-staff-invitations"],
    access: { mode: "any", permissions: [P.VIEW_ROLES, P.CREATE_ROLE, P.MODIFY_ROLE, P.BROWSE_ADMINISTRATORS] },
    primaryRoute: R.ONBOARDING.ROLES,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "review-the-roles", title: "Review the roles" },
      { id: "add-your-own-role", title: "Add a role of your own" },
      { id: "confirm-the-roles", title: "Confirm the roles" },
      { id: "invite-administrators", title: "Invite administrators" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: [
      "school.setup.onboarding-checklist",
      "school.roles.create-and-edit-role",
      "school.roles.role-change-approval",
    ],
    estimatedMinutes: 8,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "high",
    status: "published",
    article: () => import("../content/school-setup/confirm-roles-and-invite-staff"),
  },
  {
    id: "school.setup.import-initial-data",
    slug: "import-your-school-data-during-setup",
    title: "Import your school's data during setup",
    summary: "Load students, staff and guardians from spreadsheets, check each upload, and close the data step once all three are fully imported.",
    category: "school-setup",
    tags: ["import", "upload", "datasets", "students", "staff", "guardians", "template", "spreadsheet"],
    aliases: ["upload initial datasets", "bulk upload", "csv", "xlsx", "download template", "finish data setup", "partly imported", "fix rows"],
    audiences: ["school-administrator", "admissions-and-records"],
    routes: [R.ONBOARDING.IMPORT],
    actionIds: ["upload-datasets"],
    access: { mode: "any", permissions: [P.VIEW_IMPORT_TEMPLATES] },
    primaryRoute: R.ONBOARDING.IMPORT,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "read-required-datasets", title: "Read the required datasets" },
      { id: "import-a-dataset", title: "Import a dataset" },
      { id: "check-your-uploads", title: "Check your uploads" },
      { id: "finish-data-setup", title: "Finish data setup" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["school.setup.onboarding-checklist", "school.setup.request-go-live"],
    estimatedMinutes: 10,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "medium",
    status: "published",
    article: () => import("../content/school-setup/import-initial-data"),
  },
  {
    id: "school.setup.request-go-live",
    slug: "request-go-live",
    title: "Request go-live",
    summary: "Ask XVS to take your school live, follow the request while it is reviewed, and know what to do if it is declined or activation fails.",
    category: "school-setup",
    tags: ["go-live", "go live", "request", "readiness", "approval", "activation", "declined"],
    aliases: ["launch school", "request go-live", "go live date", "go-live rejected", "activation failed", "withdraw request", "when can we go live", "request history"],
    audiences: ["school-administrator"],
    routes: [R.ONBOARDING.GO_LIVE],
    actionIds: ["view-go-live"],
    access: { mode: "any", permissions: [P.VIEW_GO_LIVE_REQUESTS, P.REQUEST_GO_LIVE] },
    primaryRoute: R.ONBOARDING.GO_LIVE,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "check-readiness", title: "Check you are ready" },
      { id: "send-the-request", title: "Send the request" },
      { id: "while-you-wait", title: "While XVS reviews it" },
      { id: "if-it-is-declined", title: "If XVS declines it" },
      { id: "if-activation-fails", title: "If activation fails" },
      { id: "after-go-live", title: "After go-live" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["school.setup.onboarding-checklist"],
    estimatedMinutes: 5,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "high",
    status: "published",
    article: () => import("../content/school-setup/request-go-live"),
  },
  {
    id: "school.setup.view-branches",
    slug: "view-your-branches",
    title: "View your branches",
    summary: "See every branch your school runs, open one for its code, address and contact details, and know how to get a branch added or corrected.",
    category: "school-setup",
    tags: ["branches", "main branch", "branch code", "address", "branch status"],
    aliases: ["add a branch", "edit branch", "open a branch", "branch details", "change branch address", "suspended branch", "new branch"],
    audiences: ["school-administrator", "branch-administrator"],
    routes: [R.BRANCHES.INDEX],
    actionIds: ["view-branches"],
    access: { mode: "any", permissions: [P.BROWSE_BRANCHES] },
    primaryRoute: R.BRANCHES.INDEX,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "read-the-branch-list", title: "Read the branch list" },
      { id: "open-a-branch", title: "Open a branch" },
      { id: "add-or-change-a-branch", title: "Add or change a branch" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["school.getting-started.basics"],
    estimatedMinutes: 2,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "low",
    status: "published",
    article: () => import("../content/school-setup/view-branches"),
  },
  {
    id: "school.setup.settings-overview",
    slug: "find-your-way-around-settings",
    title: "Find your way around Settings",
    summary: "Open your school's Settings, see which areas your role reaches, and find the settings that live on screens of their own.",
    category: "school-setup",
    tags: ["settings", "configuration", "overview", "more settings", "preferences"],
    aliases: ["where are the settings", "school settings", "change a setting", "all settings", "other settings", "configuration"],
    audiences: ["school-administrator", "branch-administrator"],
    routes: [R.SETTINGS.INDEX, R.SETTINGS.MORE],
    actionIds: ["view-school-settings"],
    access: {
      mode: "any",
      permissions: [P.VIEW_SETTINGS, P.VIEW_SCHOOL_PROFILE, P.MANAGE_NOTIFICATION_SETTINGS, P.MODIFY_STUDENT],
    },
    primaryRoute: R.SETTINGS.INDEX,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "open-settings", title: "Open Settings" },
      { id: "the-overview", title: "Read the overview" },
      { id: "more-settings", title: "Find the settings on other screens" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: [
      "school.setup.settings-school-profile",
      "school.setup.settings-security",
      "school.setup.settings-notifications",
    ],
    estimatedMinutes: 3,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "low",
    status: "published",
    article: () => import("../content/school-setup/settings-overview"),
  },
  {
    id: "school.setup.settings-school-profile",
    slug: "keep-your-school-profile-up-to-date",
    title: "Keep your school profile up to date",
    summary: "Update your address, website, motto and logo after go-live, and know why currency and term structure are fixed once the school is live.",
    category: "school-setup",
    tags: ["school profile", "logo", "crest", "address", "website", "motto", "currency", "term structure"],
    aliases: ["change logo", "change school address", "update motto", "change website", "change currency", "change term structure", "school details"],
    audiences: ["school-administrator", "branch-administrator"],
    routes: [R.SETTINGS.PROFILE],
    actionIds: ["view-school-profile-settings"],
    access: { mode: "any", permissions: [P.VIEW_SCHOOL_PROFILE] },
    primaryRoute: R.SETTINGS.PROFILE,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "what-xvs-sets", title: "What XVS sets" },
      { id: "update-your-details", title: "Update your details" },
      { id: "change-your-logo", title: "Change your logo" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["school.setup.settings-overview", "school.setup.school-profile"],
    estimatedMinutes: 3,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "medium",
    status: "published",
    article: () => import("../content/school-setup/settings-school-profile"),
  },
  {
    id: "school.setup.settings-security",
    slug: "set-sign-in-and-security-rules",
    title: "Set sign-in and security rules",
    summary: "Choose how many wrong passwords lock an account, how long reset links, invitations and support sessions last, for the whole school or one branch, always stricter than the level above.",
    category: "school-setup",
    tags: ["security", "sign-in", "lockout", "password", "reset link", "invitation expiry", "branch"],
    aliases: ["account locked", "lock after wrong password", "how long does a reset link last", "invitation expired", "password policy", "branch security", "support session timeout"],
    audiences: ["school-administrator", "branch-administrator"],
    routes: [R.SETTINGS.SECURITY],
    actionIds: ["view-security-settings"],
    access: { mode: "any", permissions: [P.VIEW_SETTINGS] },
    primaryRoute: R.SETTINGS.SECURITY,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "the-rules", title: "The six rules" },
      { id: "stricter-never-looser", title: "Stricter, never looser" },
      { id: "change-a-rule", title: "Change a rule" },
      { id: "put-a-rule-back", title: "Put a rule back" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: [
      "school.setup.settings-overview",
      "school.getting-started.reset-password",
      "school.staff.invitations",
    ],
    estimatedMinutes: 4,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "high",
    status: "published",
    article: () => import("../content/school-setup/settings-security"),
  },
  {
    id: "school.setup.settings-notifications",
    slug: "choose-which-notifications-send-email",
    title: "Choose which notifications send email",
    summary: "Turn email on or off for each event your school's people are notified about, for the whole school or one branch, and know which ones always send and which stay in the bell.",
    category: "school-setup",
    tags: ["notifications", "email", "bell", "events", "transactional"],
    aliases: ["stop emails", "turn off email", "email notifications", "too many emails", "notification preferences", "always sent"],
    audiences: ["school-administrator"],
    routes: [R.SETTINGS.NOTIFICATIONS],
    actionIds: ["view-notification-settings"],
    access: { mode: "any", permissions: [P.MANAGE_NOTIFICATION_SETTINGS] },
    primaryRoute: R.SETTINGS.NOTIFICATIONS,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "whole-school-or-branch", title: "Choose the whole school or a branch" },
      { id: "read-the-list", title: "Read the list" },
      { id: "turn-email-on-or-off", title: "Turn email on or off" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: [
      "school.setup.settings-overview",
      "school.getting-started.notifications",
      "school.workflow.approval-notifications",
    ],
    estimatedMinutes: 3,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "low",
    status: "published",
    article: () => import("../content/school-setup/settings-notifications"),
  },
  {
    id: "school.setup.settings-enrolment",
    slug: "set-your-enrolment-rules",
    title: "Set your enrolment rules",
    summary: "Choose the age range a new pupil must fall in, the documents and details your school asks for, and whether a full class can take one more.",
    category: "school-setup",
    tags: ["enrolment", "age range", "documents", "required details", "class capacity", "full class"],
    aliases: ["enrolment settings", "age at enrolment", "required documents", "required fields", "class capacity", "hard cap", "never over capacity", "default class size"],
    audiences: ["school-administrator", "admissions-and-records"],
    routes: [R.SETTINGS.ENROLMENT],
    actionIds: ["view-enrolment-settings"],
    access: { mode: "any", permissions: [P.VIEW_SETTINGS] },
    primaryRoute: R.SETTINGS.ENROLMENT,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "age-at-enrolment", title: "Age at enrolment" },
      { id: "documents-to-ask-for", title: "Documents to ask for" },
      { id: "details-required", title: "Details required at enrolment" },
      { id: "class-capacity", title: "Class capacity" },
      { id: "save-the-rules", title: "Save the rules" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: [
      "school.setup.settings-overview",
      "school.students.enrol-student",
      "school.students.promote-students",
      "school.academics.classes-and-arms",
    ],
    estimatedMinutes: 4,
    owner: OWNER,
    reviewedAt: "2026-09-28",
    risk: "medium",
    status: "published",
    article: () => import("../content/school-setup/settings-enrolment"),
  },
  {
    id: "school.setup.settings-guardians",
    slug: "set-your-guardian-rules",
    title: "Set your guardian rules",
    summary: "Choose how many guardians each child needs, whether a new guardian must give an email, how siblings are recognised, and the relationship words your school uses.",
    category: "school-setup",
    tags: ["guardians", "siblings", "relationship", "guardian email", "minimum guardians"],
    aliases: ["guardian settings", "guardians per child", "two guardians", "guardian email required", "sibling matching", "relationship types", "add a relationship", "sponsor"],
    audiences: ["school-administrator", "admissions-and-records"],
    routes: [R.SETTINGS.GUARDIANS],
    actionIds: ["view-guardian-settings"],
    access: { mode: "any", permissions: [P.VIEW_SETTINGS] },
    primaryRoute: R.SETTINGS.GUARDIANS,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "guardians-per-child", title: "Guardians per child" },
      { id: "contact-details", title: "Contact details" },
      { id: "recognising-siblings", title: "Recognising siblings" },
      { id: "your-own-relationships", title: "Your own relationships" },
      { id: "save-the-rules", title: "Save the rules" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: [
      "school.setup.settings-overview",
      "school.setup.settings-enrolment",
      "school.students.guardians",
      "school.students.enrol-student",
    ],
    estimatedMinutes: 4,
    owner: OWNER,
    reviewedAt: "2026-09-28",
    risk: "medium",
    status: "published",
    article: () => import("../content/school-setup/settings-guardians"),
  },
  {
    id: "school.setup.settings-admissions",
    slug: "set-your-admission-steps",
    title: "Set your admission steps",
    summary: "Name the steps an applicant goes through at your school, make a step an offer with a deadline, and choose the documents needed before a child is put on the roll.",
    category: "school-setup",
    tags: ["admissions", "applicants", "admission steps", "offer", "documents", "interview"],
    aliases: ["admission settings", "admission stages", "admission pipeline", "offer deadline", "offer expiry", "interview step", "documents before enrolling"],
    audiences: ["school-administrator", "admissions-and-records"],
    routes: [R.SETTINGS.ADMISSIONS],
    actionIds: ["view-admission-settings"],
    access: { mode: "any", permissions: [P.VIEW_SETTINGS] },
    primaryRoute: R.SETTINGS.ADMISSIONS,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "admission-steps", title: "Name your admission steps" },
      { id: "offer-steps", title: "Make a step an offer" },
      { id: "documents-before-enrolling", title: "Documents needed before enrolling" },
      { id: "save-the-rules", title: "Save the rules" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: [
      "school.setup.settings-overview",
      "school.students.review-applicants",
      "school.setup.settings-enrolment",
    ],
    estimatedMinutes: 4,
    owner: OWNER,
    reviewedAt: "2026-09-28",
    risk: "medium",
    status: "published",
    article: () => import("../content/school-setup/settings-admissions"),
  },
  {
    id: "school.setup.settings-admission-numbers",
    slug: "set-the-admission-number-rule",
    title: "Set the admission number rule",
    summary: "Decide whether a child needs an admission number at enrolment, describe what a valid one looks like, test it, write the hint the form shows, issue numbers automatically, and give a branch a rule of its own.",
    category: "school-setup",
    tags: ["admission number", "enrolment", "format", "pattern", "prefix", "hint", "branch", "automatic numbering"],
    aliases: ["admission number format", "require admission number", "admission number refused", "numbering rule", "prefix and digits", "custom pattern", "issue numbers automatically", "next admission number", "branch admission numbers", "use the school's rule"],
    audiences: ["school-administrator", "admissions-and-records"],
    routes: [R.SETTINGS.ADMISSION_NUMBERS],
    actionIds: ["view-admission-number-settings"],
    access: { mode: "any", permissions: [P.MODIFY_STUDENT] },
    primaryRoute: R.SETTINGS.ADMISSION_NUMBERS,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "whole-school-or-branch", title: "Choose the whole school or a branch" },
      { id: "require-a-number", title: "Decide whether a number is required" },
      { id: "describe-a-valid-number", title: "Describe a valid number" },
      { id: "test-and-save", title: "Test the rule and save it" },
      { id: "issue-automatically", title: "Issue numbers automatically" },
      { id: "use-the-schools-rule", title: "Put a branch back on the school's rule" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: [
      "school.setup.settings-overview",
      "school.setup.settings-enrolment",
      "school.students.enrol-student",
    ],
    estimatedMinutes: 5,
    owner: OWNER,
    reviewedAt: "2026-09-28",
    risk: "medium",
    status: "published",
    article: () => import("../content/school-setup/settings-admission-numbers"),
  },
  {
    id: "school.setup.settings-payroll",
    slug: "choose-how-payroll-is-run",
    title: "Choose how payroll is run",
    summary: "Pay the whole school in one payroll run or let each branch run its own, and clear the people with no branch before switching to per branch.",
    category: "school-setup",
    tags: ["payroll", "per branch", "central", "payroll scope", "branch"],
    aliases: ["per branch payroll", "central payroll", "each branch pays its own staff", "one payroll", "payroll scope", "per-branch payroll is not possible yet"],
    audiences: ["school-administrator", "finance-officer"],
    routes: [R.SETTINGS.PAYROLL],
    actionIds: ["view-payroll-settings"],
    access: { mode: "any", permissions: [P.VIEW_SETTINGS] },
    primaryRoute: R.SETTINGS.PAYROLL,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "the-two-ways", title: "The two ways to run payroll" },
      { id: "switch", title: "Switch between them" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: [
      "school.setup.settings-overview",
      "school.finance.run-payroll",
      "school.staff.posting-and-reach",
    ],
    estimatedMinutes: 3,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "high",
    status: "published",
    article: () => import("../content/school-setup/settings-payroll"),
  },
  {
    id: "school.setup.settings-staff-profiles",
    slug: "choose-who-sees-what-of-a-staff-profile",
    title: "Choose who sees what of a staff profile",
    summary: "Decide which sections of a colleague's profile their line managers, other colleagues and they themselves see when it is opened from the organogram. The contact card is always shown.",
    category: "school-setup",
    tags: ["staff profiles", "privacy", "line managers", "colleagues", "contact card", "visibility", "organogram"],
    aliases: ["who can see staff profiles", "profile visibility", "line manager access", "colleague contact card", "staff privacy", "hide staff details", "can a teacher see leave"],
    audiences: ["school-administrator"],
    routes: [R.SETTINGS.STAFF_PROFILES],
    actionIds: ["view-staff-profile-settings"],
    access: { mode: "any", permissions: [P.VIEW_SETTINGS] },
    primaryRoute: R.SETTINGS.STAFF_PROFILES,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "read-the-grid", title: "Read the grid" },
      { id: "what-a-tick-does", title: "What a tick does" },
      { id: "change-the-rules", title: "Change the rules" },
      { id: "use-the-defaults", title: "Go back to the defaults" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: [
      "school.setup.settings-overview",
      "school.staff.read-organogram",
      "school.staff.find-staff-record",
      "school.roles.field-access",
    ],
    estimatedMinutes: 4,
    owner: OWNER,
    reviewedAt: "2026-09-28",
    risk: "high",
    status: "published",
    article: () => import("../content/school-setup/settings-staff-profiles"),
  },
] as const satisfies readonly GuideRecord[];
