import { P } from "@/permissions";

import type { GuideRecord } from "../types";
import { OWNER, R } from "./shared";

export const STAFF_GUIDES = [
  {
    id: "school.staff.find-staff-record",
    slug: "find-and-read-a-staff-record",
    title: "Find and read a staff record",
    summary: "Search the Staff Directory, filter by role and status, read each tab of a staff profile, fix gaps in the record, and apply for or record leave.",
    category: "staff",
    tags: ["staff directory", "profile", "employment", "account", "leave", "record"],
    aliases: ["find a teacher", "look up staff", "employee record", "staff id", "who works here", "apply for leave", "record leave", "unlock account"],
    audiences: ["school-administrator", "branch-administrator", "teacher"],
    routes: [R.STAFF.INDEX, R.STAFF.PROFILE],
    actionIds: ["view-staff"],
    access: { mode: "any", permissions: [P.BROWSE_TEACHERS] },
    primaryRoute: R.STAFF.INDEX,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "search-and-filter", title: "Search and filter the directory" },
      { id: "counts-and-attention", title: "Use the counts and attention list" },
      { id: "read-the-profile", title: "Read a staff profile" },
      { id: "fix-the-record", title: "Fix the record" },
      { id: "leave", title: "Apply for or record leave" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: [
      "school.staff.add-staff",
      "school.staff.change-employment-status",
      "school.staff.teaching-duties",
    ],
    estimatedMinutes: 6,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "low",
    featured: true,
    status: "published",
    article: () => import("../content/staff/find-staff-record"),
  },
  {
    id: "school.staff.add-staff",
    slug: "add-a-member-of-staff",
    title: "Add a member of staff",
    summary: "Create a staff record and send the invitation in one save: bio, employment, posting, optional teaching duties and qualifications. Import many people from a spreadsheet.",
    category: "staff",
    tags: ["add staff", "invite", "hire", "employment", "posting", "import"],
    aliases: ["add a teacher", "invite a teacher", "new employee", "hire", "onboard somebody", "register staff", "import staff"],
    audiences: ["school-administrator", "branch-administrator"],
    routes: [R.STAFF.ADD, R.STAFF.INDEX],
    actionIds: ["add-staff"],
    access: { mode: "any", permissions: [P.INVITE_TEACHER] },
    walkthroughId: "walkthrough.school.staff.add-staff",
    primaryRoute: R.STAFF.ADD,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "bio-and-employment", title: "Bio and employment" },
      { id: "role-and-duties", title: "Role and teaching duties" },
      { id: "qualifications", title: "Qualifications" },
      { id: "create-and-invite", title: "Create and invite" },
      { id: "import-many-people", title: "Import many people at once" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: [
      "school.staff.invitations",
      "school.staff.posting-and-reach",
      "school.staff.teaching-duties",
    ],
    estimatedMinutes: 6,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "medium",
    featured: true,
    status: "published",
    article: () => import("../content/staff/add-staff"),
  },
  {
    id: "school.staff.invitations",
    slug: "follow-up-staff-invitations",
    title: "Follow up staff invitations",
    summary: "See who has not activated their account, resend a link that went astray, and withdraw an invitation sent in error.",
    category: "staff",
    tags: ["invitation", "activation", "resend", "withdraw", "pending"],
    aliases: ["resend invite", "invitation not received", "who has not accepted", "withdraw an invitation", "activation link", "pending staff"],
    audiences: ["school-administrator", "branch-administrator"],
    routes: [R.STAFF.INVITATIONS],
    actionIds: ["view-pending-invitations"],
    access: { mode: "any", permissions: [P.BROWSE_TEACHERS] },
    primaryRoute: R.STAFF.INVITATIONS,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "read-the-list", title: "Read the list" },
      { id: "resend-an-invitation", title: "Resend an invitation" },
      { id: "withdraw-an-invitation", title: "Withdraw an invitation" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: [
      "school.staff.add-staff",
      "school.staff.find-staff-record",
    ],
    estimatedMinutes: 3,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "medium",
    status: "published",
    article: () => import("../content/staff/invitations"),
  },
  {
    id: "school.staff.posting-and-reach",
    slug: "post-staff-to-branches",
    title: "Post staff to branches and read their reach",
    summary: "See who is based at a branch, who reaches it through a role, and who belongs to the whole school, and change where people are posted.",
    category: "staff",
    tags: ["posting", "branch", "reach", "roster", "school-wide"],
    aliases: ["move a teacher to another branch", "change branch", "based at", "branch roster", "who works at this branch", "reassign a branch", "posted to"],
    audiences: ["school-administrator"],
    routes: [R.STAFF.POSTING],
    actionIds: ["view-staff-posting"],
    access: { mode: "any", permissions: [P.MODIFY_TEACHER] },
    primaryRoute: R.STAFF.POSTING,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "posting-and-reach", title: "Posting and reach are different" },
      { id: "read-a-roster", title: "Read a branch roster" },
      { id: "change-a-posting", title: "Change a posting" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: [
      "school.staff.find-staff-record",
      "school.staff.add-staff",
    ],
    estimatedMinutes: 4,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "medium",
    status: "published",
    article: () => import("../content/staff/posting-and-reach"),
  },
  {
    id: "school.staff.teaching-duties",
    slug: "assign-teaching-duties",
    title: "Assign teaching duties",
    summary: "Find subjects nobody teaches, give each class subject its teachers and main teacher, set class teachers, and follow timetable clashes.",
    category: "staff",
    tags: ["teaching duties", "coverage", "subject teacher", "class teacher", "main teacher", "clashes"],
    aliases: ["who teaches what", "assign a subject", "subject cover", "class teacher", "teaching load", "gaps", "assign teacher to class"],
    audiences: ["school-administrator", "branch-administrator", "teacher"],
    routes: [R.STAFF.TEACHING],
    actionIds: ["view-teaching-duties"],
    access: { mode: "any", permissions: [P.BROWSE_TEACHERS] },
    walkthroughId: "walkthrough.school.staff.teaching-duties",
    primaryRoute: R.STAFF.TEACHING,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "read-coverage", title: "Read the coverage" },
      { id: "staff-a-subject", title: "Staff a class subject" },
      { id: "by-teacher", title: "Change what one teacher carries" },
      { id: "class-teachers", title: "Set class teachers" },
      { id: "timetable-clashes", title: "Timetable clashes" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: [
      "school.staff.add-staff",
      "school.staff.find-staff-record",
    ],
    estimatedMinutes: 6,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "medium",
    status: "published",
    article: () => import("../content/staff/teaching-duties"),
  },
  {
    id: "school.staff.change-employment-status",
    slug: "change-a-staff-employment-status",
    title: "Change a staff member's employment status",
    summary: "Suspend, reinstate or record a resignation or termination, see what the change does to the person's sign-in, and give the dates and reason.",
    category: "staff",
    tags: ["employment status", "resign", "terminate", "suspend", "account"],
    aliases: ["staff resigned", "terminate employment", "suspend a teacher", "reinstate staff", "last working day", "staff left", "exit"],
    audiences: ["school-administrator"],
    routes: [R.STAFF.PROFILE, R.STAFF.INDEX],
    access: { mode: "any", permissions: [P.TRANSITION_TEACHER] },
    primaryRoute: R.STAFF.INDEX,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "employment-and-account", title: "Employment and account are separate" },
      { id: "change-the-status", title: "Change the status" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: [
      "school.staff.find-staff-record",
      "school.staff.invitations",
    ],
    estimatedMinutes: 4,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "high",
    status: "published",
    article: () => import("../content/staff/change-employment-status"),
  },
  {
    id: "school.staff.read-organogram",
    slug: "read-the-organogram",
    title: "Read the organogram",
    summary: "See who reports to whom across the school: switch between People and Posts, narrow to a unit, open and close the chart, zoom, show dotted lines and open a person or a post.",
    category: "staff",
    tags: ["organogram", "org chart", "reporting line", "posts", "units", "dotted lines", "hierarchy"],
    aliases: ["who is my manager", "who reports to whom", "line manager", "organisation chart", "org chart", "find a post", "structure"],
    audiences: ["all-users"],
    routes: [R.STAFF.ORGANOGRAM],
    actionIds: ["view-organogram"],
    access: { mode: "any", permissions: [P.VIEW_SCHOOL_ORGANOGRAM] },
    primaryRoute: R.STAFF.ORGANOGRAM,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "people-and-posts", title: "People and Posts" },
      { id: "find-someone", title: "Find somebody or a post" },
      { id: "open-and-close", title: "Open and close the chart" },
      { id: "zoom-and-move", title: "Zoom and move around" },
      { id: "dotted-lines", title: "See dotted lines" },
      { id: "person-and-post-panels", title: "Open a person or a post" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["school.staff.build-organogram", "school.staff.find-staff-record"],
    estimatedMinutes: 4,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "low",
    status: "published",
    article: () => import("../content/staff/read-organogram"),
  },
  {
    id: "school.staff.build-organogram",
    slug: "build-and-maintain-the-organogram",
    title: "Build and maintain the organogram",
    summary: "Set up divisions, departments and teams, add the posts in them, appoint people as primary or acting holders, draw dotted lines, and keep a branch's structure within its branch.",
    category: "staff",
    tags: ["organogram", "units", "posts", "appoint", "acting", "dotted lines", "headcount", "branch"],
    aliases: ["add a post", "create a department", "appoint somebody", "acting head", "end an appointment", "vacancies", "new unit", "manage organogram"],
    audiences: ["school-administrator", "branch-administrator"],
    routes: [R.STAFF.ORGANOGRAM_MANAGE],
    actionIds: ["manage-organogram", "add-organogram-post"],
    access: {
      mode: "any",
      permissions: [P.CREATE_ORG_STRUCTURE, P.UPDATE_ORG_STRUCTURE, P.DELETE_ORG_STRUCTURE, P.APPOINT_TO_POST],
    },
    primaryRoute: R.STAFF.ORGANOGRAM_MANAGE,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "build-the-units", title: "Build the units" },
      { id: "add-the-posts", title: "Add the posts" },
      { id: "appoint-people", title: "Appoint people to posts" },
      { id: "add-dotted-lines", title: "Add dotted lines" },
      { id: "branch-administrators", title: "If you manage one branch" },
      { id: "change-or-remove", title: "Change or remove a unit or post" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: ["school.staff.read-organogram", "school.staff.posting-and-reach"],
    estimatedMinutes: 10,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "medium",
    status: "published",
    article: () => import("../content/staff/build-organogram"),
  },
] as const satisfies readonly GuideRecord[];
