import { P } from "@/permissions";

import type { GuideRecord } from "../types";
import { OWNER, R } from "./shared";

export const STUDENTS_AND_GUARDIANS_GUIDES = [
  {
    id: "school.students.find-student-record",
    slug: "find-and-read-a-student-record",
    title: "Find and read a student's record",
    summary: "Search the Student Directory, narrow it with filters, work the student work queue, and read every tab of a student's profile.",
    category: "students-and-guardians",
    tags: ["student directory", "profile", "filters", "record", "completeness", "work queue"],
    aliases: ["find a pupil", "look up a child", "search students", "student profile", "admission number", "missing details", "class list"],
    audiences: ["admissions-and-records", "school-administrator", "branch-administrator", "teacher"],
    routes: [R.STUDENTS.INDEX, R.STUDENTS.PROFILE],
    actionIds: ["view-students"],
    access: { mode: "any", permissions: [P.BROWSE_STUDENTS] },
    walkthroughId: "walkthrough.school.students.find-student-record",
    primaryRoute: R.STUDENTS.INDEX,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "search-and-filter", title: "Search and filter the directory" },
      { id: "overview-and-work-queue", title: "Use the overview and work queue" },
      { id: "read-the-profile", title: "Read a student's profile" },
      { id: "fill-missing-information", title: "Fill missing information" },
      { id: "see-an-earlier-day", title: "See the record on an earlier day" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: [
      "school.students.enrol-student",
      "school.students.place-and-transfer",
      "school.students.guardians",
      "school.students.change-status",
    ],
    estimatedMinutes: 6,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "low",
    featured: true,
    status: "published",
    article: () => import("../content/students-and-guardians/find-student-record"),
  },
  {
    id: "school.students.review-applicants",
    slug: "review-applicants-and-admit",
    title: "Review applicants and admit them",
    summary: "Record an application, decide on it, put the student on the roll with an admission number, or close the application with a reason.",
    category: "students-and-guardians",
    tags: ["applicants", "admissions", "application", "enrol", "admission number"],
    aliases: ["admit a child", "admissions", "waiting list", "accept an application", "reject an application", "put on the roll", "close application"],
    audiences: ["admissions-and-records", "school-administrator", "branch-administrator"],
    routes: [R.STUDENTS.APPLICANTS, R.STUDENTS.ENROL],
    actionIds: ["view-applicants"],
    access: { mode: "any", permissions: [P.BROWSE_STUDENTS] },
    primaryRoute: R.STUDENTS.APPLICANTS,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "three-stages", title: "The three stages" },
      { id: "add-an-applicant", title: "Add an applicant" },
      { id: "put-on-the-roll", title: "Put an applicant on the roll" },
      { id: "close-an-application", title: "Close an application" },
      { id: "place-in-a-class", title: "Place them in a class" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: [
      "school.students.enrol-student",
      "school.students.place-and-transfer",
    ],
    estimatedMinutes: 5,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "medium",
    status: "published",
    article: () => import("../content/students-and-guardians/review-applicants"),
  },
  {
    id: "school.students.enrol-student",
    slug: "enrol-a-student",
    title: "Enrol a student",
    summary: "Put one student on the roll by hand: their details, branch and class, guardians, optional contact and medical details, then review and save.",
    category: "students-and-guardians",
    tags: ["enrol", "enrolment", "admission", "new student", "entry class", "guardian"],
    aliases: ["register pupil", "register a child", "add a student", "admit", "new pupil", "intake", "enroll"],
    audiences: ["admissions-and-records", "school-administrator", "branch-administrator"],
    routes: [R.STUDENTS.ENROL],
    actionIds: ["enrol-student"],
    access: { mode: "all", permissions: [P.ENROLL_STUDENT, P.ASSIGN_CLASS] },
    walkthroughId: "walkthrough.school.students.enrol-student",
    primaryRoute: R.STUDENTS.ENROL,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "choose-what-you-create", title: "Choose what you are creating" },
      { id: "fill-the-steps", title: "Fill in the steps" },
      { id: "add-guardians", title: "Add guardians" },
      { id: "review-and-save", title: "Review and save" },
      { id: "duplicates-and-full-classes", title: "Duplicates and full classes" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: [
      "school.students.review-applicants",
      "school.students.import-students",
      "school.students.find-student-record",
      "school.setup.settings-enrolment",
    ],
    estimatedMinutes: 6,
    owner: OWNER,
    reviewedAt: "2026-09-28",
    risk: "medium",
    featured: true,
    status: "published",
    article: () => import("../content/students-and-guardians/enrol-student"),
  },
  {
    id: "school.students.import-students",
    slug: "import-students-from-a-spreadsheet",
    title: "Import students from a spreadsheet",
    summary: "Load a roll from a CSV or Excel file through the Import drawer on the Student Directory, check it, and confirm before anything is written.",
    category: "students-and-guardians",
    tags: ["import", "bulk", "spreadsheet", "csv", "xlsx", "template", "roll"],
    aliases: ["bulk upload students", "upload pupils", "import a roll", "load students from excel", "mass enrolment"],
    audiences: ["admissions-and-records", "school-administrator"],
    routes: [R.STUDENTS.INDEX],
    access: { mode: "all", permissions: [P.UPLOAD_IMPORT_BATCH, P.IMPORT_STUDENTS] },
    primaryRoute: R.STUDENTS.INDEX,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "open-the-import", title: "Open the import" },
      { id: "upload-and-check", title: "Upload and check the file" },
      { id: "confirm-and-import", title: "Confirm and import" },
      { id: "after-the-import", title: "After the import" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: [
      "school.students.enrol-student",
      "school.students.place-and-transfer",
    ],
    estimatedMinutes: 7,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "medium",
    status: "published",
    article: () => import("../content/students-and-guardians/import-students"),
  },
  {
    id: "school.students.place-and-transfer",
    slug: "place-students-and-transfer-classes",
    title: "Place students in classes and move them between classes",
    summary: "Empty the list of students with no class, read a class register, and move a student to another class with a reason and a date.",
    category: "students-and-guardians",
    tags: ["class", "placement", "transfer", "register", "roster", "capacity", "unassigned"],
    aliases: ["move class", "change class", "assign a class", "place a student", "unassigned students", "class register", "class full"],
    audiences: ["admissions-and-records", "school-administrator", "branch-administrator"],
    routes: [R.STUDENTS.ASSIGN, R.STUDENTS.PROFILE],
    actionIds: ["view-class-transfers"],
    access: { mode: "any", permissions: [P.ASSIGN_CLASS] },
    primaryRoute: R.STUDENTS.ASSIGN,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "place-unassigned-students", title: "Place students who have no class" },
      { id: "read-a-class-register", title: "Read a class register" },
      { id: "move-one-student", title: "Move one student" },
      { id: "full-classes", title: "When a class is full" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: [
      "school.students.review-applicants",
      "school.students.promote-students",
      "school.students.find-student-record",
    ],
    estimatedMinutes: 5,
    owner: OWNER,
    reviewedAt: "2026-09-28",
    risk: "medium",
    status: "published",
    article: () => import("../content/students-and-guardians/place-and-transfer"),
  },
  {
    id: "school.students.guardians",
    slug: "keep-guardian-records-right",
    title: "Keep guardian records right",
    summary: "Find a guardian, confirm their name, keep their contact details complete, and link them to the right students with the right primary contact.",
    category: "students-and-guardians",
    tags: ["guardian", "parent", "contact", "primary contact", "siblings", "link"],
    aliases: ["parents", "next of kin", "link a parent", "add a guardian", "change primary contact", "check name", "family", "household"],
    audiences: ["admissions-and-records", "school-administrator", "branch-administrator"],
    routes: [R.STUDENTS.GUARDIANS, R.STUDENTS.GUARDIAN_DETAILS, R.STUDENTS.PROFILE],
    actionIds: ["view-guardians"],
    access: { mode: "any", permissions: [P.BROWSE_STUDENTS] },
    primaryRoute: R.STUDENTS.GUARDIANS,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "find-a-guardian", title: "Find a guardian" },
      { id: "read-a-guardian", title: "Read a guardian's page" },
      { id: "edit-and-confirm-names", title: "Edit details and confirm names" },
      { id: "link-guardians-and-students", title: "Link guardians and students" },
      { id: "primary-contact", title: "The primary contact" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: [
      "school.students.find-student-record",
      "school.students.enrol-student",
    ],
    estimatedMinutes: 5,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "medium",
    status: "published",
    article: () => import("../content/students-and-guardians/guardians"),
  },
  {
    id: "school.students.change-status",
    slug: "change-a-student-status",
    title: "Change a student's status",
    summary: "Suspend, withdraw, transfer out or return a student to Active, using only the moves the school allows from their current status.",
    category: "students-and-guardians",
    tags: ["status", "withdraw", "suspend", "transfer out", "graduate", "lifecycle"],
    aliases: ["withdraw a student", "suspend a pupil", "student left", "leaving school", "reinstate", "reactivate student", "transferred to another school"],
    audiences: ["admissions-and-records", "school-administrator", "branch-administrator"],
    routes: [R.STUDENTS.PROFILE, R.STUDENTS.INDEX],
    access: { mode: "any", permissions: [P.TRANSITION_STUDENT] },
    primaryRoute: R.STUDENTS.INDEX,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "open-change-status", title: "Open Change status" },
      { id: "choose-the-move", title: "Choose the move and give a reason" },
      { id: "final-statuses", title: "Statuses that cannot be left" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: [
      "school.students.find-student-record",
      "school.students.review-applicants",
      "school.students.promote-students",
    ],
    estimatedMinutes: 4,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "high",
    status: "published",
    article: () => import("../content/students-and-guardians/change-status"),
  },
  {
    id: "school.students.promote-students",
    slug: "promote-students-at-year-end",
    title: "Promote students at the end of the year",
    summary: "Move every student on the roll into next year's classes in one run: choose the year, check the level mapping, decide exceptions, and confirm.",
    category: "students-and-guardians",
    tags: ["promotion", "end of session", "graduate", "repeat", "hold", "next year"],
    aliases: ["promote students", "move up a year", "end of year", "graduate a class", "repeat a class", "new session", "year end"],
    audiences: ["school-administrator", "admissions-and-records"],
    routes: [R.STUDENTS.PROMOTION],
    actionIds: ["view-promotion"],
    access: { mode: "any", permissions: [P.PROMOTE_STUDENTS] },
    walkthroughId: "walkthrough.school.students.promote-students",
    primaryRoute: R.STUDENTS.PROMOTION,
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "choose-the-year", title: "Choose the year to promote into" },
      { id: "review-students", title: "Review students" },
      { id: "handle-exceptions", title: "Handle exceptions" },
      { id: "confirm-and-run", title: "Confirm and run" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: [
      "school.students.place-and-transfer",
      "school.students.change-status",
      "school.setup.settings-enrolment",
    ],
    estimatedMinutes: 8,
    owner: OWNER,
    reviewedAt: "2026-09-28",
    risk: "high",
    status: "published",
    article: () => import("../content/students-and-guardians/promote-students"),
  },
] as const satisfies readonly GuideRecord[];
