import { P } from "@/permissions";

import type { GuideRecord } from "../types";
import { A, OWNER, R } from "./shared";

export const TROUBLESHOOTING_GUIDES = [
  {
    id: "school.troubleshooting.permission-denied",
    slug: "access-denied-or-a-button-is-missing",
    title: "Access denied, or a button or menu is missing",
    summary: "Work out whether your role, the school's plan or an archived session is stopping you, and ask for exactly the access you need.",
    category: "troubleshooting",
    tags: ["permission", "access", "role", "403", "missing button", "missing menu", "field access"],
    aliases: ["access denied", "permission denied", "403", "forbidden", "not allowed", "you don't have permission", "button missing", "menu missing", "cannot see", "greyed out", "no add button"],
    audiences: ["all-users"],
    routes: [
      R.OVERVIEW.INDEX,
      R.ROLES.INDEX,
      R.ROLES.FIELD_ACCESS,
      R.STUDENTS.INDEX,
      R.STAFF.INDEX,
      R.WORKFLOW.APPROVALS,
      R.FINANCE.INDEX,
      R.PROCUREMENT.INDEX,
    ],
    access: { mode: "authenticated", permissions: [] },
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "recognise-the-message", title: "Recognise the message" },
      { id: "missing-menu-or-button", title: "A menu item or button is missing" },
      { id: "ask-for-access", title: "Ask for access" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: [
      "school.troubleshooting.read-only-session",
      "school.troubleshooting.not-live-yet",
      "school.getting-started.raise-support-ticket",
    ],
    estimatedMinutes: 4,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "low",
    featured: true,
    status: "published",
    article: () => import("../content/troubleshooting/permission-denied"),
  },
  {
    id: "school.troubleshooting.read-only-session",
    slug: "a-past-session-is-read-only",
    title: "A past session is read-only",
    summary: "Why an archived session cannot be changed, and how to switch back to the active one.",
    category: "troubleshooting",
    tags: ["session", "academic year", "archived", "read-only", "session selector"],
    aliases: ["read only", "read-only year", "archived session", "cannot edit", "cannot add class", "buttons missing", "past year", "last year", "switch session", "change year", "session archived"],
    audiences: ["all-users"],
    routes: [
      R.ACADEMIC_STRUCTURE.INDEX,
      R.ACADEMIC_STRUCTURE.SESSIONS,
      R.ACADEMIC_STRUCTURE.CLASSES,
      R.ACADEMIC_STRUCTURE.SUBJECTS,
      R.ACADEMIC_CALENDAR.INDEX,
      R.ACADEMIC_CALENDAR.EVENTS,
      R.TIMETABLES.CLASSES,
      R.STUDENTS.ASSIGN,
    ],
    access: {
      mode: "any",
      permissions: [
        P.BROWSE_STRUCTURE,
        P.BROWSE_SESSIONS,
        P.BROWSE_CLASSES,
        P.BROWSE_SUBJECTS,
        P.BROWSE_CALENDAR,
        P.BROWSE_TIMETABLES,
        P.BROWSE_STUDENTS,
      ],
    },
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "recognise-it", title: "Recognise a read-only session" },
      { id: "switch-session", title: "Switch to the active session" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: [
      "school.troubleshooting.permission-denied",
      "school.troubleshooting.nothing-found",
      "school.getting-started.basics",
    ],
    estimatedMinutes: 2,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "low",
    status: "published",
    article: () => import("../content/troubleshooting/read-only-session"),
  },
  {
    id: "school.troubleshooting.not-live-yet",
    slug: "a-screen-opens-when-your-school-goes-live",
    title: "A screen opens only when your school goes live",
    summary: "What the not-live notice means before go-live, and which parts of XVS you can use meanwhile.",
    category: "troubleshooting",
    tags: ["go-live", "onboarding", "not live", "setup", "closed screen"],
    aliases: ["not available yet", "opens when your school goes live", "school not live", "tenant not live", "locked screen", "cannot open students", "back to control room"],
    audiences: ["all-users"],
    routes: [R.ONBOARDING.NOT_LIVE, R.ONBOARDING.INDEX, R.OVERVIEW.INDEX],
    access: { mode: "authenticated", permissions: [] },
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "recognise-it", title: "Recognise it" },
      { id: "what-you-can-use", title: "What you can use before go-live" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: [
      "school.troubleshooting.permission-denied",
      "school.getting-started.raise-support-ticket",
    ],
    estimatedMinutes: 2,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "low",
    status: "published",
    article: () => import("../content/troubleshooting/not-live-yet"),
  },
  {
    id: "school.troubleshooting.session-expired",
    slug: "signed-out-or-session-expired",
    title: "Signed out, or your session expired",
    summary: "Why XVS signs you out after inactivity, how to stay signed in, and what to do after it happens.",
    category: "troubleshooting",
    tags: ["session", "timeout", "sign out", "logged out", "inactivity", "401"],
    aliases: ["session expired", "session timed out", "still there", "logged out", "kicked out", "signed out", "continue session", "go to login", "your session has ended", "401", "unauthorized"],
    audiences: ["all-users"],
    routes: [A.LOGIN, R.OVERVIEW.INDEX],
    access: { mode: "authenticated", permissions: [] },
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "stay-signed-in", title: "Stay signed in" },
      { id: "sign-back-in", title: "Sign back in" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: [
      "school.getting-started.activate-and-sign-in",
      "school.getting-started.reset-password",
    ],
    estimatedMinutes: 2,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "low",
    status: "published",
    article: () => import("../content/troubleshooting/session-expired"),
  },
  {
    id: "school.troubleshooting.nothing-found",
    slug: "search-or-filters-show-nothing",
    title: "Search or filters show nothing",
    summary: "Check the branch, session, tab and search that narrow a list before deciding a record is missing.",
    category: "troubleshooting",
    tags: ["search", "filter", "empty list", "branch", "session", "no results"],
    aliases: ["no results", "nothing found", "list is empty", "cannot find student", "cannot find record", "missing record", "no matches", "nothing matches", "search not working", "filter not working"],
    audiences: ["all-users"],
    routes: [R.STUDENTS.INDEX, R.STAFF.INDEX, R.SUPPORT.INDEX, R.NOTIFICATIONS],
    access: { mode: "authenticated", permissions: [] },
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "check-what-narrows-the-list", title: "Check what narrows the list" },
      { id: "search-well", title: "Search well" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: [
      "school.troubleshooting.read-only-session",
      "school.troubleshooting.permission-denied",
      "school.getting-started.basics",
    ],
    estimatedMinutes: 3,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "low",
    status: "published",
    article: () => import("../content/troubleshooting/nothing-found"),
  },
  {
    id: "school.troubleshooting.import-export-failed",
    slug: "an-import-or-export-did-not-finish",
    title: "An import or export did not finish",
    summary: "Read why a data import or an export stopped, fix the cause, and run it again without creating duplicates.",
    category: "troubleshooting",
    tags: ["import", "export", "upload", "spreadsheet", "failed", "download", "data"],
    aliases: ["import failed", "validation failed", "partially imported", "rolled back", "export failed", "retry export", "file expired", "download failed", "upload failed", "spreadsheet errors"],
    audiences: ["school-administrator", "admissions-and-records", "finance-officer"],
    routes: [
      R.DATA_IMPORTS.BATCHES.INDEX,
      R.DATA_IMPORTS.BATCHES.VIEW_PATH,
      R.EXPORT.FILES,
      R.EXPORT.RUN_PATH,
      R.EXPORT.QUEUES,
    ],
    access: {
      mode: "any",
      permissions: [
        P.VIEW_IMPORT_BATCHES,
        P.VIEW_SAVED_EXPORTS,
        P.VIEW_EXPORT_RUNS,
        P.DOWNLOAD_EXPORT_FILE,
      ],
    },
    sections: [
      { id: "before-you-start", title: "Before you start" },
      { id: "an-import-stopped", title: "An import stopped" },
      { id: "an-export-failed", title: "An export failed" },
      { id: "common-problems", title: "Common problems" },
      { id: "completion-check", title: "Completion check" },
    ],
    relatedGuideIds: [
      "school.troubleshooting.permission-denied",
      "school.getting-started.raise-support-ticket",
    ],
    estimatedMinutes: 4,
    owner: OWNER,
    reviewedAt: "2026-09-27",
    risk: "medium",
    status: "published",
    article: () => import("../content/troubleshooting/import-export-failed"),
  },
] as const satisfies readonly GuideRecord[];
