import { P } from "@/permissions";
import { routesPath } from "@/routes/routesPath";

import type { Walkthrough } from "./types";
import { ACADEMICS_WALKTHROUGHS } from "./school/academics";
import { STAFF_WALKTHROUGHS } from "./school/staff";
import { STUDENTS_WALKTHROUGHS } from "./school/students";

const R = routesPath.PROTECTED;

/**
 * Every interactive walkthrough, each tied to the guide that explains the same
 * task in full.
 *
 * A step points at an element by its `data-guide` attribute, never by class or
 * text, so restyling a screen cannot break a tour silently. A step whose
 * element is not on screen (a panel that renders nothing on a quiet day, a
 * button the reader's role hides) is either routed around with a `branch`
 * step or shown as unavailable with a way back to the guide.
 *
 * Steps run in array order and a tour ends after its last step, so a fallback
 * step (no receipt opened, no bank account yet) sits just before `complete`
 * and the main path jumps over it with a second branch on the same target.
 * Both paths then finish on the same closing step.
 *
 * `permissions` lists every code the tour needs, and all of them must be held
 * for it to start: a tour that opens a form needs the code behind the button
 * that opens it, or it would stop at a step the reader can never reach.
 *
 * Finance, procurement, workflow and export screens come from the shared
 * package, and the tours point at the `data-guide` names it renders. Screens
 * this app does not mount (entities, currencies, dimensions, team load) are
 * never named here.
 *
 * Bump `version` whenever steps are added, removed or reordered: saved
 * progress from an older version is discarded rather than resumed at a step
 * that no longer means the same thing.
 */
/** The tours for the shared package's screens and the basics. */
const PACKAGE_WALKTHROUGHS = [
  {
    id: "walkthrough.school.getting-started.basics",
    guideId: "school.getting-started.basics",
    route: R.OVERVIEW.INDEX,
    permissions: [],
    prerequisites: ["Sign in to XVS."],
    version: 1,
    steps: [
      {
        id: "welcome",
        title: "Welcome to XVS",
        body: "This short tour shows where to find your work, start a task, and get help. It never changes anything for you.",
        advance: "next",
      },
      {
        id: "sidebar",
        target: "sidebar.navigation",
        title: "Everything is in the sidebar",
        body: "Areas are grouped the way the school works: people, enrolment and duties, academics, and administration. You only see the areas your role covers.",
        placement: "right",
        advance: "manual",
      },
      {
        id: "lens-branch",
        kind: "branch",
        target: "sidebar.lenses",
        whenPresent: "lenses",
        whenMissing: "workspace-search",
      },
      {
        id: "lenses",
        target: "sidebar.lenses",
        title: "Choose your branch and year",
        body: "On screens that read them, these decide which branch and academic year you are looking at. A past year is read-only.",
        placement: "right",
        advance: "manual",
      },
      {
        id: "workspace-search",
        target: "header.workspace-search",
        title: "Start any task from here",
        body: "Type what you want to do, such as enrol student, or two letters of a name. Matching guides are listed too. On a phone, this opens the same search across the header.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "notifications",
        target: "header.notifications",
        title: "See what needs you",
        body: "Approvals waiting for you, finished imports, and replies to your tickets arrive here. Select one to open the record it is about.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "page-help",
        target: "header.page-help",
        title: "Get help without losing your place",
        body: "Raise a ticket over the screen you are on, or open the guides written for it.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "complete",
        title: "You know the main paths",
        body: "Use the sidebar to find an area, the search box to start a task, and the headset whenever a screen does not do what you expect.",
        advance: "next",
      },
    ],
  },

  // Approvals and workflow

  {
    id: "walkthrough.school.workflow.decide-approval",
    guideId: "school.workflow.decide-approval",
    route: R.WORKFLOW.APPROVALS,
    permissions: [],
    prerequisites: [
      "Know whether you are deciding for yourself or covering for a colleague who delegated to you.",
      "Have any paperwork the request depends on, such as a quotation or a receipt, to hand.",
    ],
    version: 1,
    steps: [
      {
        id: "welcome",
        title: "Review before you decide",
        body: "This tour shows how to find a request waiting for you and what to check before deciding. It never opens a request or records a decision for you.",
        advance: "next",
      },
      {
        id: "filters",
        target: "workflow-approvals.filters",
        title: "Pick the right queue",
        body: "Narrow the list by document type, such as purchase requisitions. My queue is everything waiting for you. On behalf of shows requests you can decide for a colleague who delegated their approvals to you.",
        placement: "right",
        advance: "manual",
      },
      {
        id: "queue",
        target: "workflow-approvals.queue",
        title: "Check the request before Review",
        body: "Each row shows what the request is, who raised it, the step it is waiting at and how long it has been in your queue. Requests you have already voted on are hidden. Review opens the full request.",
        placement: "left",
        advance: "manual",
      },
      {
        id: "decision-boundary",
        title: "Approve, reject and return do different things",
        body: "Approve counts toward the current step and may finish it. Reject either ends the request or sends it back, depending on how the approval path is set up. Return asks the requester to correct it and resubmit. Reject and return need a reason, and every choice asks you to confirm.",
        advance: "next",
      },
      {
        id: "complete",
        title: "The decision stays with you",
        body: "Open Review yourself, read the request, the approval path and its activity, then choose and confirm only the outcome you are authorised to give.",
        advance: "next",
      },
    ],
  },
  {
    id: "walkthrough.school.workflow.track-and-delegate",
    guideId: "school.workflow.track-and-delegate",
    route: R.WORKFLOW.DELEGATIONS,
    permissions: [],
    prerequisites: [
      "Agree with the colleague who will cover for you, and for which dates.",
      "Decide whether the cover is for every kind of request or just one, such as purchase orders.",
    ],
    version: 1,
    steps: [
      {
        id: "welcome",
        title: "Hand over your approvals for a set period",
        body: "This tour explains how cover works while you are away. It never opens the form, picks a colleague, or saves or revokes a delegation.",
        advance: "next",
      },
      {
        id: "new-delegation",
        target: "workflow-delegations.new",
        title: "Set up cover only when it is agreed",
        body: "New Delegation asks who covers for you, the start and end dates, which document type it applies to (or all of them) and an optional reason. An exclusive delegation takes you out of approver queues for the period; otherwise either of you can vote. Check the summary before Save delegation.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "records",
        target: "workflow-delegations.records",
        title: "Check status and scope",
        body: "The tabs above switch between My Delegations, the cover you gave, and Delegated to me, the cover you hold. You can revoke your own Active and Scheduled delegations; Expired and Revoked ones stay listed. Check the dates, document type and Exclusive label before relying on cover.",
        placement: "top",
        advance: "manual",
      },
      {
        id: "complete",
        title: "Follow your own requests from My Submissions",
        body: "A delegation only changes who can vote. To follow a request you raised, resubmit one that was returned or withdraw one, use My Submissions.",
        advance: "next",
      },
    ],
  },

  // Finance

  {
    id: "walkthrough.school.finance.chart-of-accounts",
    guideId: "school.finance.chart-of-accounts",
    route: `${R.FINANCE.SETUP}/accounts`,
    permissions: [P.FIN_VIEW_ACCOUNTS, P.FIN_VIEW_TAX_CODES, P.FIN_VIEW_COST_CENTERS],
    prerequisites: [
      "Have the school's agreed list of accounts, tax codes and cost centres to hand.",
    ],
    version: 1,
    steps: [
      {
        id: "welcome",
        title: "Set up the accounts in order",
        body: "This tour walks through the chart of accounts, tax codes and cost centres that the rest of Finance posts to. It never creates, edits or deactivates anything.",
        advance: "next",
      },
      {
        id: "accounts",
        target: "finance-setup.heading",
        title: "Build the chart before anything posts to it",
        body: "Every journal line lands on one account here. Codes are exactly four digits and the first digit sets the type: 1 Assets, 2 Liabilities, 3 Equity, 4 Income, 5 Expenses. Tick Postable only for accounts that take entries; a parent account groups others of the same type.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "tax-codes",
        route: `${R.FINANCE.SETUP}/tax-codes`,
        target: "finance-setup.heading",
        title: "Tax codes carry the rate and the accounts",
        body: "A tax code, such as VAT at 7.5% or withholding tax, sets the rate and the accounts the tax is collected into and paid from. Add only the codes the school actually charges or deducts.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "cost-centres",
        route: `${R.FINANCE.SETUP}/cost-centers`,
        target: "finance-setup.heading",
        title: "Cost centres say who owns the spending",
        body: "Tag income and spending with the department or branch that owns it, so reports can split them. In a code such as CC-LAG-FAC, the second part names the branch, and the Branch filter reads it from there.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "complete",
        title: "Nothing was changed",
        body: "Create each account, tax code and cost centre yourself. Then open Accounting defaults in Finance Settings, which chooses the account each kind of posting uses, and check it before live work begins.",
        advance: "next",
      },
    ],
  },
  {
    id: "walkthrough.school.finance.journal-entries",
    guideId: "school.finance.journal-entries",
    route: R.FINANCE.LEDGER,
    permissions: [P.FIN_VIEW_JOURNALS, P.FIN_POST_DIRECT_ENTRY],
    prerequisites: [
      "Have the approved paperwork for the entry, such as an opening balance or a correction.",
      "Know the accounts, amounts, date and any cost centre it uses.",
    ],
    version: 1,
    steps: [
      {
        id: "welcome",
        title: "Use a manual journal only when nothing else fits",
        body: "This tour opens the journal form and explains its checks. It never picks an account, fills in a field or posts.",
        advance: "next",
      },
      {
        id: "ledger",
        target: "finance-ledger.header",
        title: "Most entries post themselves",
        body: "Fee invoices, receipts, payroll, purchases and bank work post their own journals from their own screens. Use New journal only for an approved entry with no screen of its own, such as an opening balance or a correction.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "open-editor",
        target: "finance-ledger.new-journal",
        title: "Open the form",
        body: "Select New journal to see the form. Opening it changes nothing, and the tour carries on once it is open.",
        placement: "bottom",
        advance: "target-click",
      },
      {
        id: "evidence",
        target: "finance-journal.header-fields",
        title: "Date, reference and narration",
        body: "Choose a date inside an open period, and write a narration and reference that somebody checking later can trace back to the paperwork.",
        placement: "left",
        advance: "manual",
      },
      {
        id: "lines",
        target: "finance-journal.postings",
        title: "Build the entry line by line",
        body: "Each line needs a postable account, a debit or credit side and an amount. A cost centre is optional. Add line gives you another row; a journal always has at least two.",
        placement: "left",
        advance: "manual",
      },
      {
        id: "balance",
        target: "finance-journal.balance",
        title: "Balanced is not the same as right",
        body: "Post entry stays greyed out until total debits equal total credits and every line has an account. A balanced entry can still use the wrong accounts, so check the treatment as well.",
        placement: "top",
        advance: "manual",
      },
      {
        id: "complete",
        title: "Post entry is your decision",
        body: "The tour stops here. Post entry posts the journal straight away, with no draft and no second confirmation. Select it yourself only after checking everything, then open the journal to confirm the result.",
        advance: "next",
      },
    ],
  },
  {
    id: "walkthrough.school.finance.close-a-period",
    guideId: "school.finance.close-a-period",
    route: `${R.FINANCE.SETUP}/periods`,
    permissions: [P.FIN_VIEW_PERIODS],
    prerequisites: [
      "Agree the close plan for the month, and who owns each outstanding item.",
      "Reconcile the bank and clear draft journals before closing.",
    ],
    version: 1,
    steps: [
      {
        id: "welcome",
        title: "Close the month deliberately",
        body: "This tour explains the fiscal calendar, the close checklist and what each period action does. It never creates a year or confirms any action.",
        advance: "next",
      },
      {
        id: "calendar",
        target: "finance-periods.calendar-controls",
        title: "Work in one fiscal year",
        body: "Choose the fiscal year to review. Create the next year before the last period ends, or anything dated after it cannot post.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "periods-branch",
        kind: "branch",
        target: "finance-periods.periods",
        whenPresent: "period",
        whenMissing: "no-calendar",
      },
      {
        id: "period",
        target: "finance-periods.period",
        title: "Open a period",
        body: "Open allows ordinary posting, Soft-closed allows close entries only, Closed can be re-opened with permission, and Locked is permanent. Select the period you want to review; opening it changes nothing.",
        placement: "top",
        advance: "target-click",
      },
      {
        id: "checklist",
        target: "finance-periods.checklist",
        title: "Blockers stop the close, warnings do not",
        body: "A failed blocker must be fixed at its source before the period can close. A check marked Warning only stays visible for your judgement but does not stop the close.",
        placement: "left",
        advance: "manual",
      },
      {
        id: "actions",
        title: "Each action has a different effect",
        body: "Soft close is reversible. Run close steps runs the month-end checks and blocks further posting. Re-open lets ordinary posting back in and needs another close afterwards. Lock period cannot be undone, and a year's final period cannot be locked until the fiscal year is closed.",
        advance: "manual",
      },
      {
        id: "calendar-rejoin",
        kind: "branch",
        target: "finance-periods.periods",
        whenPresent: "complete",
        whenMissing: "no-calendar",
      },
      {
        id: "no-calendar",
        title: "This year has no periods yet",
        body: "Somebody with permission creates the year with New fiscal year, which opens its posting periods. Until then there is nothing to close.",
        advance: "next",
      },
      {
        id: "complete",
        title: "Every confirmation is yours",
        body: "The tour stops before Soft close, Run close steps, Re-open, Close fiscal year and Lock period. Check the reports and the checklist, then confirm only the action you intend.",
        advance: "next",
      },
    ],
  },
  {
    id: "walkthrough.school.finance.record-fee-payments",
    guideId: "school.finance.record-fee-payments",
    route: `${R.FINANCE.RECEIVABLES}/receipts`,
    permissions: [P.FIN_VIEW_PAYMENTS],
    prerequisites: [
      "Have the bank alert, teller or cash record for the payment to hand.",
      "Know which pupil the money is for and which bills it should settle.",
    ],
    version: 1,
    steps: [
      {
        id: "welcome",
        title: "Follow a payment from receipt to settled bill",
        body: "This tour explains receipts and how they are applied to bills. It never records a receipt, changes an allocation or voids anything.",
        advance: "next",
      },
      {
        id: "summary",
        target: "finance-receipts.summary",
        title: "See what has come in",
        body: "Money received today and this week, and how much is Unallocated: money received but not yet applied to any bill, which sits as the customer's credit.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "record",
        target: "finance-receipts.record",
        title: "Recording money is a separate step",
        body: "Record receipt takes the customer, date, method, amount, bank account and reference, and posts the money in. The tour does not open that form.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "list",
        target: "finance-receipts.list",
        title: "Open an existing receipt",
        body: "Search by receipt, customer or reference, then select a receipt to see how it is applied, and choose Next. Opening it changes nothing.",
        placement: "top",
        advance: "manual",
      },
      {
        id: "allocation-branch",
        kind: "branch",
        target: "finance-receipts.allocation",
        whenPresent: "allocation",
        whenMissing: "allocation-not-open",
      },
      {
        id: "allocation",
        target: "finance-receipts.allocation",
        title: "Check the suggested split",
        body: "If money is still unapplied, Auto-allocate spreads it across the customer's open bills, oldest first or largest first. Check each amount and the Remainder against what the parent said the money was for. The tour stops before Apply allocation.",
        placement: "left",
        advance: "next",
      },
      {
        id: "allocation-rejoin",
        kind: "branch",
        target: "finance-receipts.allocation",
        whenPresent: "complete",
        whenMissing: "allocation-not-open",
      },
      {
        id: "allocation-not-open",
        title: "No receipt was opened",
        body: "The tour will not choose a receipt for you. Open one later to compare its unapplied money with the customer's open bills.",
        advance: "next",
      },
      {
        id: "complete",
        title: "Applying the money is your decision",
        body: "Apply only the split you have checked, then reopen the receipt and the bills to confirm the customer's balance. Nothing was changed here.",
        advance: "next",
      },
    ],
  },
  {
    id: "walkthrough.school.finance.reduce-a-fee-bill",
    guideId: "school.finance.reduce-a-fee-bill",
    route: `${R.FINANCE.RECEIVABLES}/concessions`,
    permissions: [P.FIN_VIEW_CONCESSIONS, P.FIN_CREATE_CONCESSION, P.FIN_VIEW_CREDIT_NOTES, P.FIN_CREATE_CREDIT_NOTE],
    prerequisites: [
      "Have the approval for the reduction, such as a sibling discount, scholarship or head teacher's waiver.",
      "Know the pupil, the bill and the amount or percentage.",
    ],
    version: 1,
    steps: [
      {
        id: "welcome",
        title: "Choose the right way to reduce a bill",
        body: "This tour compares concessions and credit notes, opens their forms and explains what each posts. It never fills in, saves or submits anything.",
        advance: "next",
      },
      {
        id: "concessions",
        title: "A concession reduces one bill",
        body: "Use a waiver, discount or scholarship when policy reduces what a pupil owes on one posted bill. Search the list first, so the same discount is not given twice.",
        advance: "next",
      },
      {
        id: "new-concession",
        target: "finance-concessions.new",
        title: "Open the concession form",
        body: "Select New concession to see its fields. Opening it creates nothing.",
        placement: "bottom",
        advance: "target-click",
      },
      {
        id: "concession-form",
        target: "finance-concessions.form",
        title: "Keep the policy, bill and amount together",
        body: "Choose waiver, discount or scholarship, the customer and the bill, then a fixed amount or a percentage of the bill's balance. The basis or reason is required, for example Sibling discount 10%.",
        placement: "left",
        advance: "manual",
      },
      {
        id: "concession-posting",
        target: "finance-concessions.posting",
        title: "Read what it posts",
        body: "The preview shows the journal the concession will post. Save draft keeps unfinished work without posting it.",
        placement: "left",
        advance: "manual",
      },
      {
        id: "concession-boundary",
        target: "finance-concessions.submit",
        title: "Post or submit stays with you",
        body: "The button reads Post concession, or Submit for approval when the school's approval rules cover it. The tour never selects it. Choose Next to move on to credit notes.",
        placement: "top",
        advance: "manual",
      },
      {
        id: "credit-notes",
        route: `${R.FINANCE.RECEIVABLES}/credit-notes`,
        title: "Credit notes and debit notes",
        body: "A credit note lowers what a customer owes and reverses income, for example after a pupil was billed twice. A debit note adds a further charge. Search the existing notes first.",
        advance: "next",
      },
      {
        id: "issue-note",
        target: "finance-credit-notes.issue",
        title: "Open the note form",
        body: "Select Issue note to see its fields. Opening it changes nothing.",
        placement: "bottom",
        advance: "target-click",
      },
      {
        id: "note-form",
        target: "finance-credit-notes.form",
        title: "Type, customer, account and bill",
        body: "Choose credit or debit, the date, the customer, the income account, an optional bill, the amount, an optional cost centre and a reason. For a credit note, decide whether to leave it as credit or apply it to the oldest bills straight away.",
        placement: "left",
        advance: "manual",
      },
      {
        id: "note-posting",
        target: "finance-credit-notes.posting",
        title: "Read the posting before the label",
        body: "The preview shows exactly which accounts are debited and credited. Stop if it does not match what was approved.",
        placement: "left",
        advance: "manual",
      },
      {
        id: "note-boundary",
        target: "finance-credit-notes.submit",
        title: "Issue or submit stays with you",
        body: "The button reads Issue note, or Submit for approval when the school's approval rules cover it. Never split an amount to avoid approval. The tour stops here without selecting it.",
        placement: "top",
        advance: "next",
      },
    ],
  },
  {
    id: "walkthrough.school.finance.refund-or-write-off",
    guideId: "school.finance.refund-or-write-off",
    route: `${R.FINANCE.RECEIVABLES}/refunds`,
    permissions: [P.FIN_VIEW_REFUNDS, P.FIN_CREATE_REFUND, P.FIN_CREATE_WRITE_OFF],
    prerequisites: [
      "Have the approval for the refund or write-off, and the reason for it.",
      "Check the customer's credit, the bill balance and anything already pending, so nothing is done twice.",
    ],
    version: 1,
    steps: [
      {
        id: "welcome",
        title: "Paying money back is not the same as letting a debt go",
        body: "This tour explains refunds and write-offs on one screen. It never picks a customer, pays out money, posts a write-off, saves a draft or submits anything.",
        advance: "next",
      },
      {
        id: "workspace",
        title: "Check what already exists",
        body: "The figures at the top show refundable credit, the amount written off this year and how many actions are pending approval. Check the list too: an earlier attempt may already have done what you need.",
        advance: "next",
      },
      {
        id: "new-action",
        target: "finance-refunds.new-action",
        title: "Open the form",
        body: "Select New action to see the refund and write-off choices. Opening it changes nothing.",
        placement: "bottom",
        advance: "target-click",
      },
      {
        id: "form",
        target: "finance-refunds.form",
        title: "The action decides the fields",
        body: "A refund needs a date, a customer with credit, the bank account the money leaves from and the amount. A write-off needs a customer, the unpaid bill, a date, the amount and the expense account. Add a reason either way.",
        placement: "left",
        advance: "manual",
      },
      {
        id: "posting",
        target: "finance-refunds.posting",
        title: "See where the value goes",
        body: "A refund pays out the customer's credit, so cash leaves the bank. A write-off records the unpaid fees as a loss and clears them from what the customer owes. Stop if the preview does not match what was approved.",
        placement: "left",
        advance: "manual",
      },
      {
        id: "boundary",
        target: "finance-refunds.submit",
        title: "Draft, approval and posting all have effects",
        body: "Next action chooses whether to post now, submit for approval or save a draft; Post now is not offered when the school's approval rules cover it. The tour never selects this button.",
        placement: "top",
        advance: "next",
      },
    ],
  },
  {
    id: "walkthrough.school.finance.payment-plans",
    guideId: "school.finance.payment-plans",
    route: `${R.FINANCE.RECEIVABLES}/payment-plans`,
    permissions: [P.FIN_VIEW_PAYMENT_PLANS, P.FIN_CREATE_PAYMENT_PLAN, P.FIN_ACTIVATE_PAYMENT_PLAN],
    prerequisites: [
      "Have the installment agreement with the parent: the total, first due date, how often, and how many payments.",
    ],
    version: 1,
    steps: [
      {
        id: "welcome",
        title: "Spread one bill into installments",
        body: "This tour explains how a payment plan is built. It never picks a bill, fills in a field, or creates or cancels a plan.",
        advance: "next",
      },
      {
        id: "workspace",
        title: "Check for an existing plan first",
        body: "Search by plan, customer or bill, and look at the status and next due date, so the same bill is not given two plans.",
        advance: "next",
      },
      {
        id: "new-plan",
        target: "finance-payment-plans.new",
        title: "Open the plan form",
        body: "Select New plan to see its fields. Opening it creates nothing.",
        placement: "bottom",
        advance: "target-click",
      },
      {
        id: "form",
        target: "finance-payment-plans.form",
        title: "Base the plan on the right bill",
        body: "Choose the customer and the open bill, confirm the total, then set the start date, the number of installments (1 to 60) and how often they fall due. The bill itself still records what is owed.",
        placement: "left",
        advance: "manual",
      },
      {
        id: "schedule",
        target: "finance-payment-plans.schedule",
        title: "Compare each installment with the agreement",
        body: "The total is split evenly, and any rounding difference goes on the last installment. Check the dates, amounts and count against what the parent agreed.",
        placement: "left",
        advance: "manual",
      },
      {
        id: "boundary",
        target: "finance-payment-plans.submit",
        title: "Create plan starts tracking at once",
        body: "Create plan sets up the schedule and makes it active straight away. It does not record any payment or reduce the bill. The tour stops here without selecting it.",
        placement: "top",
        advance: "next",
      },
    ],
  },
  {
    id: "walkthrough.school.finance.email-fee-documents",
    guideId: "school.finance.email-fee-documents",
    route: `${R.FINANCE.RECEIVABLES}/invoices`,
    permissions: [P.FIN_VIEW_INVOICES, P.FIN_EMAIL_INVOICE],
    prerequisites: [
      "Know which posted bill you want to send, and to which parent.",
    ],
    version: 1,
    steps: [
      {
        id: "welcome",
        title: "Check an email before it goes to a parent",
        body: "This tour may open a bill and its email preview. It never presses Send or Retry, and never changes a bill, recipient or note.",
        advance: "next",
      },
      {
        id: "invoices",
        target: "finance-invoices.list",
        title: "Open the right bill",
        body: "Select the bill you want to send and check its customer, number, total and balance, then choose Next. Opening a bill sends nothing.",
        placement: "top",
        advance: "manual",
      },
      {
        id: "email-branch",
        kind: "branch",
        target: "finance-email.action",
        whenPresent: "email-action",
        whenMissing: "invoice-not-open",
      },
      {
        id: "email-action",
        target: "finance-email.action",
        title: "Open the email preview",
        body: "Email invoice shows the subject, who it goes to, any BCC copy and earlier attempts. Opening the preview is safe. Select it to carry on.",
        placement: "top",
        advance: "target-click",
      },
      {
        id: "preview",
        target: "finance-email.preview",
        title: "Check every detail",
        body: "Check the subject, To and BCC. Below them are an optional covering note, any reason sending is blocked, and earlier attempts. A sent attempt does not prove the parent read it, and Retry makes a new attempt.",
        placement: "left",
        advance: "next",
      },
      {
        id: "preview-rejoin",
        kind: "branch",
        target: "finance-email.preview",
        whenPresent: "complete",
        whenMissing: "invoice-not-open",
      },
      {
        id: "invoice-not-open",
        title: "No bill preview is open",
        body: "The tour will not choose a parent's bill for you. Open a posted bill later and check its customer and amount before opening Email invoice.",
        advance: "next",
      },
      {
        id: "complete",
        title: "Sending is always your choice",
        body: "The tour stops before Send and Retry. Fix anything wrong at its source first, and send only when the bill and every recipient are right. Nothing was sent here.",
        advance: "next",
      },
    ],
  },
  {
    id: "walkthrough.school.finance.reconcile-the-bank",
    guideId: "school.finance.reconcile-the-bank",
    route: R.FINANCE.BANK_RECON,
    permissions: [P.FIN_VIEW_BANK_ACCOUNTS],
    prerequisites: [
      "Have the full bank statement for the period, with its opening and closing balances.",
      "Post the fees, payments and bank charges you already know about first.",
    ],
    version: 1,
    steps: [
      {
        id: "welcome",
        title: "Explain every difference between bank and books",
        body: "This tour explains the reconciliation screen. It never matches, unmatches or ignores a line, adds an entry, runs auto-match or completes a reconciliation.",
        advance: "next",
      },
      {
        id: "scope",
        target: "finance-bank-reconciliation.scope",
        title: "Start with the right bank account",
        body: "Choose the account that matches the statement in your hand. The screen works one account at a time.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "workbench-branch",
        kind: "branch",
        target: "finance-bank-reconciliation.balances",
        whenPresent: "balances",
        whenMissing: "no-account",
      },
      {
        id: "balances",
        target: "finance-bank-reconciliation.balances",
        title: "Compare the totals first",
        body: "Compare the statement balance, the book balance, the difference and how many lines are matched. Post genuinely missing items from their own screens before explaining single lines.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "matching",
        target: "finance-bank-reconciliation.matching",
        title: "Match only the same transaction",
        body: "Pick an unmatched bank line and the book entry for the same event. Several book lines can be grouped to one bank line, or one book line split across several, but the totals must be equal. Never force a pair just to shrink the difference.",
        placement: "top",
        advance: "manual",
      },
      {
        id: "exceptions",
        target: "finance-bank-reconciliation.exceptions",
        title: "Explain what is left, do not hide it",
        body: "Add adjusting entry books a charge or interest the books are missing. Ignore line is only for a known duplicate or opening line, and has no effect on the books. Auto-match pairs lines by amount and date, but check what it pairs.",
        placement: "top",
        advance: "manual",
      },
      {
        id: "workbench-rejoin",
        kind: "branch",
        target: "finance-bank-reconciliation.balances",
        whenPresent: "complete",
        whenMissing: "no-account",
      },
      {
        id: "no-account",
        title: "No bank account to reconcile",
        body: "Add the school's bank account under Banking first, with the ledger account it posts to. The tour did not create or change anything.",
        advance: "next",
      },
      {
        id: "complete",
        title: "Completing is the reconciler's decision",
        body: "The tour stops before every match and before Complete reconciliation. Finish only when the difference is explained, every ignored line has a reason and missing entries are posted.",
        advance: "next",
      },
    ],
  },
  {
    id: "walkthrough.school.finance.run-payroll",
    guideId: "school.finance.run-payroll",
    route: R.FINANCE.PAYROLL,
    permissions: [P.FIN_VIEW_PAYROLL],
    prerequisites: [
      "Have the approved staff list, salary changes and pay date for the month.",
      "Use this tour where nobody else can see staff pay on your screen.",
    ],
    version: 1,
    steps: [
      {
        id: "welcome",
        title: "Review payroll without moving money",
        body: "This tour explains payroll runs, payslips and statutory returns. It never opens a staff record, creates, posts or pays a run, or cancels anything.",
        advance: "next",
      },
      {
        id: "heading",
        target: "finance-payroll.heading",
        title: "Get the roster right before the run",
        body: "The tabs below split the work. Salary structures set the pay components, Employee salaries is the list of staff who are paid, Payroll runs calculates each month, Payslips gives each staff member their copy, and Statutory returns lists PAYE and pension.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "summary",
        target: "finance-payroll.summary",
        title: "Calculated is not the same as paid",
        body: "Awaiting payment is net pay from a calculated run not yet paid. Calculate & post records salary cost and what is owed; Pay net pays staff only. PAYE and pension are paid separately, under Tax Remittance.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "complete",
        title: "Every payroll step stays with you",
        body: "The tour stops before New payroll run, Calculate & post and Pay net. If the school runs payroll per branch, check which branch a run covers before creating it.",
        advance: "next",
      },
    ],
  },
  {
    id: "walkthrough.school.finance.staff-expense-claims",
    guideId: "school.finance.staff-expense-claims",
    route: `${R.FINANCE.EXPENSES}/claims`,
    permissions: [P.FIN_VIEW_EXPENSE_CLAIMS],
    prerequisites: [
      "Have the staff member's receipts and what the spending was for.",
    ],
    version: 1,
    steps: [
      {
        id: "welcome",
        title: "Keep receipts, approval and payment together",
        body: "This tour explains the claims list and what each status means. It never creates, submits, approves, pays or voids a claim.",
        advance: "next",
      },
      {
        id: "summary",
        target: "finance-expense-claims.summary",
        title: "Read the queue by stage",
        body: "Open claims are drafts and claims not yet paid back. Awaiting payment is approved but not yet reimbursed: the cost is booked, but no money has left the bank.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "controls",
        target: "finance-expense-claims.controls",
        title: "Find the exact claim before acting",
        body: "Search by claimant, purpose or number and filter by status. Check every receipt, expense account and total before the claim moves on.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "complete",
        title: "No claim was changed",
        body: "Submitting, approving, rejecting, paying and voiding remain decisions for the right person. Correct mistakes on the claim itself, and check its history and payment afterwards.",
        advance: "next",
      },
    ],
  },
  {
    id: "walkthrough.school.finance.petty-cash",
    guideId: "school.finance.petty-cash",
    route: `${R.FINANCE.EXPENSES}/petty-cash`,
    permissions: [P.FIN_VIEW_PETTY_CASH],
    prerequisites: [
      "Count the cash in the tin and gather the vouchers before you start.",
    ],
    version: 1,
    steps: [
      {
        id: "welcome",
        title: "Count the tin before topping it up",
        body: "This tour explains the float, its figures and its vouchers. It never sets up or tops up a float, or records a voucher.",
        advance: "next",
      },
      {
        id: "fund-branch",
        kind: "branch",
        target: "finance-petty-cash.workbench",
        whenPresent: "fund",
        whenMissing: "no-fund",
      },
      {
        id: "fund",
        target: "finance-petty-cash.workbench",
        title: "Choose the float and its custodian",
        body: "Pick the float you are checking. Its ceiling, movement register, vouchers and the cash in the tin should all describe the same float.",
        placement: "top",
        advance: "manual",
      },
      {
        id: "summary",
        target: "finance-petty-cash.summary",
        title: "Compare ceiling, cash, spending and shortfall",
        body: "Current balance should match the cash on hand. To replenish is what brings the float back to its ceiling, not permission to raise the ceiling.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "fund-rejoin",
        kind: "branch",
        target: "finance-petty-cash.workbench",
        whenPresent: "complete",
        whenMissing: "no-fund",
      },
      {
        id: "no-fund",
        target: "finance-petty-cash.empty",
        title: "No float has been set up",
        body: "Establish float sets a float up and moves its opening cash from the bank in one step. Agree the custodian, ceiling and bank account first. The tour does not open it.",
        placement: "top",
        advance: "next",
      },
      {
        id: "complete",
        title: "Cash actions stay with the custodian and approver",
        body: "The tour stops before Establish float, New voucher and Replenish. Count the cash and check the vouchers before any of them.",
        advance: "next",
      },
    ],
  },
  {
    id: "walkthrough.school.finance.budgets",
    guideId: "school.finance.budgets",
    route: `${R.FINANCE.BUDGETS}/budgets`,
    permissions: [P.FIN_VIEW_BUDGETS],
    prerequisites: [
      "Have the agreed plan for the fiscal year, and know whether it is for the whole school or one branch.",
    ],
    version: 1,
    steps: [
      {
        id: "welcome",
        title: "Keep the approved plan intact",
        body: "This tour explains how a budget is shaped and read. It never creates, edits, approves or deletes a budget.",
        advance: "next",
      },
      {
        id: "controls",
        target: "finance-budgets.controls",
        title: "A budget follows the chart of accounts",
        body: "Each line is an income or expense account, an optional cost centre and a period, with an amount. A budget is either school-wide or for one branch, and a branch budget is compared with that branch's own postings. Check totals and duplicate lines before approval.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "complete",
        title: "Approving and deleting stay deliberate",
        body: "The tour stops before New budget, line changes, Approve and Delete. Open a budget to compare it with what was actually posted.",
        advance: "next",
      },
    ],
  },
  {
    id: "walkthrough.school.finance.fixed-assets",
    guideId: "school.finance.fixed-assets",
    route: `${R.FINANCE.BUDGETS}/assets`,
    permissions: [P.FIN_VIEW_FIXED_ASSETS],
    prerequisites: [
      "Have the purchase paperwork, cost, useful life and where each asset is kept.",
    ],
    version: 1,
    steps: [
      {
        id: "welcome",
        title: "Keep the register and the books in step",
        body: "This tour explains adding, acquiring, depreciating and disposing of assets. It never changes an asset or posts anything.",
        advance: "next",
      },
      {
        id: "summary",
        target: "finance-assets.summary",
        title: "Cost, depreciation and book value",
        body: "Total cost, accumulated depreciation and net book value should agree with the asset accounts in the ledger. Look into any gap before running depreciation again.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "controls",
        target: "finance-assets.controls",
        title: "Filter, then act on one asset",
        body: "Filter by category and status. Add asset starts a draft; Acquire on the asset books its cost; Run depreciation posts the period's depreciation; Dispose records the sale or scrapping.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "complete",
        title: "No asset was posted",
        body: "The tour stops before Add asset, Acquire, Depreciate to date, Run depreciation and Dispose. Check the preview and paperwork before each.",
        advance: "next",
      },
    ],
  },
  {
    id: "walkthrough.school.finance.tax-remittance",
    guideId: "school.finance.tax-remittance",
    route: `${R.FINANCE.BUDGETS}/tax`,
    permissions: [P.FIN_VIEW_TAX],
    prerequisites: [
      "Know the tax, the period and the due date, and have the filing receipt from the tax office when you record it.",
    ],
    version: 1,
    steps: [
      {
        id: "welcome",
        title: "Preparing, filing and paying are separate",
        body: "This tour explains tax filings and their statuses. It never prepares, files, un-files or pays a return.",
        advance: "next",
      },
      {
        id: "summary",
        target: "finance-tax.summary",
        title: "Read what is still owed",
        body: "Open is prepared but not filed. Filed, awaiting payment has been filed with the tax office but not paid. Paid is fully settled; a part payment stays outstanding.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "controls",
        target: "finance-tax.controls",
        title: "Use the right control for the next step",
        body: "New obligation sets up a tax such as PAYE or pension. New filing prepares one period from the ledger. On a filing, Mark as filed records the tax office's reference, and Pay settles it from the bank.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "complete",
        title: "Filing and paying stay deliberate",
        body: "The tour stops before New obligation, New filing, Mark as filed, Un-file and Pay. Match the schedules, the ledger and the tax office's reference first.",
        advance: "next",
      },
    ],
  },
  {
    id: "walkthrough.school.finance.online-fee-payments",
    guideId: "school.finance.online-fee-payments",
    route: R.FINANCE.COLLECTIONS,
    permissions: [P.PAY_VIEW_COLLECTIONS],
    prerequisites: [
      "Have the payment reference, amount and date the parent gave you.",
    ],
    version: 1,
    steps: [
      {
        id: "welcome",
        title: "Trace an online payment without charging twice",
        body: "This tour explains online payments and virtual accounts. It never creates a payment link or virtual account, or changes one.",
        advance: "next",
      },
      {
        id: "summary",
        target: "finance-collections.summary",
        title: "Pending, failed and settled",
        body: "Pending has not been confirmed by the payment provider yet. Settled money has arrived and should show on the pupil's receipt and balance. Failed never arrived.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "controls",
        target: "finance-collections.controls",
        title: "Look before creating a new link",
        body: "Filter by status and provider to find the payment first. A payment that has not shown on the pupil's balance yet is not proof the parent must pay again. New checkout creates a payment link to send to the parent.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "virtual-accounts",
        route: `${R.FINANCE.COLLECTIONS}/virtual-accounts`,
        target: "finance-virtual-accounts.workbench",
        title: "Virtual accounts pay in by transfer",
        body: "A virtual account gives one customer their own account number. Money transferred to it arrives here as a payment against that customer's balance.",
        placement: "top",
        advance: "manual",
      },
      {
        id: "complete",
        title: "No payment was changed",
        body: "The tour stops before New checkout and any virtual account change. Keep full account details out of screenshots and tickets.",
        advance: "next",
      },
    ],
  },

  // Procurement and inventory

  {
    id: "walkthrough.school.procurement.manage-suppliers",
    guideId: "school.procurement.manage-suppliers",
    route: `${R.PROCUREMENT.VENDORS}/vendors`,
    permissions: [P.PROC_VIEW_VENDORS],
    prerequisites: [
      "Have the supplier's registered name, contact, tax number and bank details, checked with the supplier.",
    ],
    version: 1,
    steps: [
      {
        id: "welcome",
        title: "Check the supplier before you buy",
        body: "This tour explains the supplier list and its controls. It never opens a supplier, shows bank details, or adds, edits or holds a supplier.",
        advance: "next",
      },
      {
        id: "heading",
        target: "procurement-vendors.heading",
        title: "One list of suppliers for the school",
        body: "Every purchase order, bill and payment names a supplier from here. Add Vendor creates a new one, which starts with KYC pending.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "summary",
        target: "procurement-vendors.summary",
        title: "Review the signals first",
        body: "Active suppliers, KYC pending and On Hold show which suppliers are ready for new orders. A supplier on hold cannot take new orders. Total spend is for reporting, not a reason to change a supplier's status.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "list",
        target: "procurement-vendors.list",
        title: "Find the supplier before adding another",
        body: "Search by name, and use the status tabs and the KYC filter. Check for the same supplier under a slightly different name before adding a new record.",
        placement: "top",
        advance: "manual",
      },
      {
        id: "complete",
        title: "Every sensitive change stays deliberate",
        body: "The tour stops before Add Vendor, edits, bank detail changes, KYC decisions and holds. Check the paperwork before each.",
        advance: "next",
      },
    ],
  },
  {
    id: "walkthrough.school.procurement.quotes-from-suppliers",
    guideId: "school.procurement.quotes-from-suppliers",
    route: `${R.PROCUREMENT.SOURCING}/rfqs`,
    permissions: [P.PROC_VIEW_RFQS, P.PROC_VIEW_QUOTATIONS],
    prerequisites: [
      "Have the approved need, the specification, the deadline and the suppliers you will invite.",
    ],
    version: 1,
    steps: [
      {
        id: "welcome",
        title: "Keep the quotes fair and on record",
        body: "This tour explains requests for quotation (RFQs), the quotations that come back, and the award. It never creates, issues, closes, cancels or awards anything.",
        advance: "next",
      },
      {
        id: "rfq-heading",
        target: "procurement-rfqs.heading",
        title: "Start from the approved need",
        body: "An RFQ describes what the school needs, without prices, and sets a deadline for replies. Have the specification and the suppliers to invite ready before New RFQ.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "rfq-summary",
        target: "procurement-rfqs.summary",
        title: "Watch the live requests",
        body: "Draft can still be edited. Open has been sent to suppliers. Responses in and Closing within 7 days show what needs attention, not which quote should win.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "rfq-list",
        target: "procurement-rfqs.list",
        title: "Check the full RFQ",
        body: "Open an RFQ to see its lines, invited suppliers, deadline and replies. Opening one changes nothing. Choose Next to move on to quotations.",
        placement: "top",
        advance: "manual",
      },
      {
        id: "quotation-heading",
        route: `${R.PROCUREMENT.SOURCING}/quotations`,
        target: "procurement-quotations.heading",
        title: "Compare submitted quotes from the same RFQ",
        body: "A quotation belongs to one RFQ and one invited supplier. A draft can still change; only a submitted quote that has not expired can be awarded.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "quotation-list",
        target: "procurement-quotations.list",
        title: "Compare before you award",
        body: "Filter to the RFQ, then compare total, tax, lead time and validity. Award raises a draft purchase order from the winning quote and rejects the others.",
        placement: "top",
        advance: "manual",
      },
      {
        id: "complete",
        title: "The award is your decision",
        body: "The tour stops before Submit, Award, Issue, Close and Cancel. If fewer suppliers replied than the school's rules require, an award needs a written reason from somebody allowed to give one.",
        advance: "next",
      },
    ],
  },
  {
    id: "walkthrough.school.procurement.supplier-contracts",
    guideId: "school.procurement.supplier-contracts",
    route: R.PROCUREMENT.CONTRACTS,
    permissions: [P.PROC_VIEW_CONTRACTS],
    prerequisites: [
      "Have the signed agreement: supplier, term, value, payment terms and renewal notice.",
    ],
    version: 1,
    steps: [
      {
        id: "welcome",
        title: "Keep the register matching the signed agreement",
        body: "This tour explains the contract register. It never creates, edits, activates, renews or terminates a contract.",
        advance: "next",
      },
      {
        id: "heading",
        target: "procurement-contracts.heading",
        title: "Record what was signed",
        body: "Compare the register with the signed agreement before New contract, so the dates, value and terms match exactly.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "summary",
        target: "procurement-contracts.summary",
        title: "Active, expiring and expired",
        body: "Expiring within 30 days is your cue to decide whether to renew. Expiry does not renew or terminate anything by itself.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "list",
        target: "procurement-contracts.list",
        title: "Check the terms before acting",
        body: "Open a contract to see its status, dates, value, payment terms, renewal notice and activity. Opening it changes nothing.",
        placement: "top",
        advance: "manual",
      },
      {
        id: "complete",
        title: "Every change stays deliberate",
        body: "The tour stops before New contract, Activate, Renew and Terminate. Terminating cannot be undone, so check any open orders on the contract first.",
        advance: "next",
      },
    ],
  },
  {
    id: "walkthrough.school.procurement.order-receive-and-pay",
    guideId: "school.procurement.order-receive-and-pay",
    route: R.PROCUREMENT.PURCHASE_ORDERS,
    permissions: [
      P.PROC_VIEW_PURCHASE_ORDERS, P.PROC_VIEW_GOODS_RECEIPTS,
      P.PROC_VIEW_VENDOR_INVOICES, P.PROC_VIEW_VENDOR_PAYMENTS,
    ],
    prerequisites: [
      "Start from an approved requisition; a purchase order can only be raised from one.",
      "Have the delivery note, the supplier's bill and the payment approval for the order you are following.",
    ],
    version: 1,
    steps: [
      {
        id: "welcome",
        title: "Follow one purchase from order to payment",
        body: "This tour connects the purchase order, goods receipt, supplier bill and payment. It only reads, and never opens a document or moves one on.",
        advance: "next",
      },
      {
        id: "po-heading",
        target: "procurement-purchase-orders.heading",
        title: "The order is the commitment",
        body: "A purchase order commits the school to the supplier. Check the requisition it came from, the supplier, delivery details, lines and approval before it is issued.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "po-summary",
        target: "procurement-purchase-orders.summary",
        title: "See what is still to arrive",
        body: "Open orders, Partially received and Awaiting receipt show which deliveries are still outstanding.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "receipt-heading",
        route: R.PROCUREMENT.GOODS_RECEIPTS,
        target: "procurement-goods-receipts.heading",
        title: "Record only what was accepted",
        body: "A goods receipt records a delivery against an open order. Accepted and rejected quantities and any inspection notes must match what actually arrived at the store.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "invoice-heading",
        route: R.PROCUREMENT.VENDOR_INVOICES,
        target: "procurement-vendor-invoices.heading",
        title: "Match the supplier's bill",
        body: "Enter the supplier's own bill number and link the order. The bill is checked against what was ordered and what was received; approving it does not clear a blocking mismatch.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "invoice-summary",
        target: "procurement-vendor-invoices.summary",
        title: "Review, approved, overdue and disputed",
        body: "Each figure is different work. Open the bill and its 3-way match before correcting the order, the receipt or the bill.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "payment-heading",
        route: R.PROCUREMENT.VENDOR_PAYMENTS,
        target: "procurement-vendor-payments.heading",
        title: "Pay only the approved bill",
        body: "A payment needs an active, KYC-verified supplier that is not on hold, and must complete approval before it posts. Check the bills it settles, the bank account, the date and the reference.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "complete",
        title: "Every step stays with the right person",
        body: "The tour stops before every create, approve, post and payment action. After each stage, check that the order, receipt, bill and payment still agree.",
        advance: "next",
      },
    ],
  },
  {
    id: "walkthrough.school.procurement.manage-stock",
    guideId: "school.procurement.manage-stock",
    route: `${R.PROCUREMENT.INVENTORY}/items`,
    permissions: [P.PROC_VIEW_STOCK],
    prerequisites: [
      "Have the latest stock count for the store you are checking.",
    ],
    version: 1,
    steps: [
      {
        id: "welcome",
        title: "Keep the shelves and the books in step",
        body: "This tour explains stock items, the movement history and stores. It never changes a quantity, value, item or store.",
        advance: "next",
      },
      {
        id: "item-heading",
        target: "procurement-stock-items.heading",
        title: "Start with the item",
        body: "Each stock item has a code, a unit, the accounts it posts to and a reorder level. Open an item to issue or adjust it.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "item-summary",
        target: "procurement-stock-items.summary",
        title: "Reorder and value signals",
        body: "Items tracked, Low stock, Out of stock and Total value show what needs reordering. They are not a substitute for a physical count.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "movement-list",
        route: `${R.PROCUREMENT.INVENTORY}/movements`,
        target: "procurement-stock-movements.list",
        title: "Trace every movement",
        body: "Filter to receipts, issues or adjustments. Follow the date, item, quantity, value and running balance from the first movement that looks wrong.",
        placement: "top",
        advance: "manual",
      },
      {
        id: "location-list",
        route: `${R.PROCUREMENT.INVENTORY}/locations`,
        target: "procurement-stock-locations.list",
        title: "Where the stock actually sits",
        body: "Each store keeps its own quantities. Exactly one store is the default, used by any movement that does not name a store, and it cannot be deactivated until another store is made the default.",
        placement: "top",
        advance: "manual",
      },
      {
        id: "complete",
        title: "No stock was changed",
        body: "The tour stops before New stock item, New location, Make default, Deactivate, Issue and Adjust. Use a real count for every adjustment.",
        advance: "next",
      },
    ],
  },
  {
    id: "walkthrough.school.procurement.settings",
    guideId: "school.procurement.settings",
    route: R.PROCUREMENT.SETTINGS,
    permissions: [P.PROC_VIEW_SETTINGS],
    prerequisites: [
      "Know the purchasing rule the school has agreed, and write down the current value before changing it.",
    ],
    version: 1,
    steps: [
      {
        id: "welcome",
        title: "Review the rules before changing them",
        body: "This tour walks through the school's purchasing rules. It never edits a setting, follows a link out or saves.",
        advance: "next",
      },
      {
        id: "overview",
        target: "procurement-settings.overview",
        title: "Procurement shares Finance's books",
        body: "Procurement uses the same books, currency, periods and accounts as Finance, and the same approval system as the rest of XVS.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "sections",
        target: "procurement-settings.sections",
        title: "The rules, section by section",
        body: "General defaults and purchasing policy shape new documents. Sourcing and competitive governance shape quotes. Invoice matching checks supplier bills. Accounting and approvals are managed in Finance and Workflow.",
        placement: "top",
        advance: "manual",
      },
      {
        id: "purchasing",
        route: `${R.PROCUREMENT.SETTINGS}/purchasing`,
        target: "procurement-settings.purchasing",
        title: "Supplier, lead time and receipt rules",
        body: "Set the supplier KYC requirement, the default requisition lead days and whether a goods receipt needs a purchase order. Some rules always apply, such as an approved requisition before a purchase order.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "competition",
        route: `${R.PROCUREMENT.SETTINGS}/competitive-governance`,
        target: "procurement-settings.competition",
        title: "How many quotes are enough",
        body: "The minimum suppliers invited and quotations submitted apply to the next RFQ issued or awarded. Going below them needs a separate permission and a written reason.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "matching",
        route: `${R.PROCUREMENT.SETTINGS}/matching`,
        target: "procurement-settings.matching",
        title: "How close a bill must match",
        body: "Quantity and price tolerances decide when a supplier bill is blocked for review, and whether bills without a purchase order are allowed. Overriding a block needs its own permission.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "accounting",
        route: `${R.PROCUREMENT.SETTINGS}/accounting`,
        target: "procurement-settings.accounting",
        title: "One place for the accounts",
        body: "The accounts purchases post to are set in Finance Settings, so there is one source for them. This page shows what Procurement expects.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "approvals",
        route: `${R.PROCUREMENT.SETTINGS}/approvals`,
        target: "procurement-settings.approvals",
        title: "Approvals are set in Workflow",
        body: "Requisitions, purchase orders, supplier bills and payments each follow an approval path. Viewing this page does not let you change those paths or approve anything.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "complete",
        title: "No rule was changed",
        body: "The tour stops before every Save. Record the old and new value, who agreed the change and when it takes effect before you save one.",
        advance: "next",
      },
    ],
  },

  // Data imports and exports

  {
    id: "walkthrough.school.data.import-spreadsheet",
    guideId: "school.data.import-spreadsheet",
    route: R.DATA_IMPORTS.BATCHES.INDEX,
    permissions: [P.VIEW_IMPORT_BATCHES, P.UPLOAD_IMPORT_BATCH],
    prerequisites: [
      "Have the filled-in template, and know how many rows it should create.",
      "Keep pupils' and staff members' details out of screenshots and tickets.",
    ],
    version: 1,
    steps: [
      {
        id: "welcome",
        title: "Upload, check, then import",
        body: "This tour explains how an import runs. It never uploads a file, validates, imports, deletes or rolls anything back.",
        advance: "next",
      },
      {
        id: "heading",
        target: "data-import-batches.heading",
        title: "Check the history first",
        body: "Look for an earlier upload of the same file before starting another, so the same pupils or staff are not added twice.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "summary",
        target: "data-import-batches.summary",
        title: "Read the imports by state",
        body: "In flight is still running. Needs attention covers files that failed their checks or failed to import. Select a card to filter the list.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "upload",
        route: R.DATA_IMPORTS.BATCHES.NEW,
        target: "data-import-batches.upload",
        title: "Choose the template, then the file",
        body: "Pick the template that matches your file, then drop the CSV or XLSX. Next come the header comparison, the checks and a final confirmation. The tour does not pick a file or move the steps on.",
        placement: "top",
        advance: "manual",
      },
      {
        id: "complete",
        title: "Importing stays your decision",
        body: "Fix every error the checks find, read the warnings, and confirm only when the row count is what you expected. Then open a few imported records to be sure.",
        advance: "next",
      },
    ],
  },
  {
    id: "walkthrough.school.data.import-templates",
    guideId: "school.data.import-templates",
    route: R.DATA_IMPORTS.TEMPLATES.INDEX,
    permissions: [P.VIEW_IMPORT_TEMPLATES],
    prerequisites: ["Know which kind of record you are importing, such as students or staff."],
    version: 1,
    steps: [
      {
        id: "welcome",
        title: "Start from the right template",
        body: "This tour shows where to find the spreadsheet layout for a kind of record. It never downloads or changes a template.",
        advance: "next",
      },
      {
        id: "heading",
        target: "data-import-templates.heading",
        title: "Find the template",
        body: "Search by code, name or kind of record. Each row's menu offers View Details, to read what every column expects, and View CSV or View XLSX. Download is inside the file viewer.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "summary",
        target: "data-import-templates.summary",
        title: "Only active templates can be used",
        body: "The cards count the templates you can use. An upload accepts only an Active template, so always download a fresh copy rather than reusing an old file.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "complete",
        title: "Fill it in, then import",
        body: "Keep the column headings exactly as downloaded, fill in the rows, then upload the file from Import Batches. Nothing was downloaded here.",
        advance: "next",
      },
    ],
  },
  {
    id: "walkthrough.school.data.saved-export",
    guideId: "school.data.saved-export",
    route: R.EXPORT.SAVED,
    permissions: [P.VIEW_SAVED_EXPORTS, P.CREATE_EXPORT],
    prerequisites: ["Know what the file is for, who will receive it, and the fewest columns it needs."],
    version: 1,
    steps: [
      {
        id: "welcome",
        title: "Take only the data you need",
        body: "This tour explains how an export is built. It never picks data, saves, runs or deletes an export.",
        advance: "next",
      },
      {
        id: "saved",
        target: "data-exports.heading",
        title: "Saved exports are reusable",
        body: "Each saved export is a recipe you can run again. Editing one changes future files only; files already produced stay as they were.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "heading",
        route: R.EXPORT.NEW,
        target: "data-export-builder.heading",
        title: "A new export",
        body: "The heading shows which data the export reads once you have chosen it.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "steps",
        target: "data-export-builder.steps",
        title: "Four steps, in order",
        body: "Data chooses what to export. Columns picks the fields and filters: take as few as you need, and note that fields marked Sensitive need extra permission. File sets the format. Review shows exactly what will be produced.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "actions",
        target: "data-export-builder.actions",
        title: "Saving and running are different",
        body: "Save without running keeps the recipe for later. Save and run also queues a file straight away, so use it only after the review.",
        placement: "top",
        advance: "manual",
      },
      {
        id: "complete",
        title: "No data was exported",
        body: "The tour stops before every save and run. Follow a run under Files or Queues, and treat the downloaded file as confidential.",
        advance: "next",
      },
    ],
  },
  {
    id: "walkthrough.school.data.export-and-download",
    guideId: "school.data.export-and-download",
    route: R.EXPORT.FILES,
    permissions: [P.VIEW_EXPORT_RUNS],
    prerequisites: ["Know roughly when you started the export and what it was called."],
    version: 1,
    steps: [
      {
        id: "welcome",
        title: "Find your file, and what happened to it",
        body: "This tour explains where exported files land and how to follow one that is still running or went wrong. It never downloads, retries or cancels anything.",
        advance: "next",
      },
      {
        id: "files",
        target: "data-export-files.heading",
        title: "Every export run is listed here",
        body: "Files are kept for a set number of days after the run, then expire. The run and its history stay, and an expired file needs a fresh run.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "files-summary",
        target: "data-export-files.summary",
        title: "Ready, expiring and needs attention",
        body: "Needs attention covers runs that failed or only partly completed. Open the run to see what was left out before using the file.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "queues",
        route: R.EXPORT.QUEUES,
        target: "data-export-queues.heading",
        title: "Background work you started",
        body: "Imports, exports and emails you started show here while they run. Queued and Running are not failures, so do not start the same export again just because it is slow.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "queues-summary",
        target: "data-export-queues.summary",
        title: "In progress or finished",
        body: "The counts separate queued, running, finished and failed work. Filter by status or type and open a task to see its progress and result.",
        placement: "bottom",
        advance: "manual",
      },
      {
        id: "complete",
        title: "Fix the cause before trying again",
        body: "Use the recorded reason to correct and rerun. Never attach a downloaded file or pupils' details to a support ticket.",
        advance: "next",
      },
    ],
  },
] as const satisfies readonly Walkthrough[];

/**
 * Every walkthrough. The school's own screens keep their tours in
 * ./school/<area>.ts, so each area is written and reviewed apart.
 */
export const WALKTHROUGH_REGISTRY: readonly Walkthrough[] = [
  ...PACKAGE_WALKTHROUGHS,
  ...STUDENTS_WALKTHROUGHS,
  ...STAFF_WALKTHROUGHS,
  ...ACADEMICS_WALKTHROUGHS,
];

export function findWalkthrough(id: string): Walkthrough | undefined {
  return (WALKTHROUGH_REGISTRY as readonly Walkthrough[]).find((walkthrough) => walkthrough.id === id);
}
